### ISSUE TITLE
Improve the [ambience] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#107]
We need to try to improve (or check if no improved made) the __ambience__ mod with this tweaked mod : 

#### Description
Ambiance Redo 0.5 released with code changes, smaller sound files thanks to Kilbith and some timing changes...
#### Link
https://github.com/tenplus1/ambience

**Comment by Ombridride** [comment]
@ObaniGemini @crabman77 @LeMagnesium @gravgun 
Nobody interrested about this check/possible improved of the [ambience] mod ?

**Comment by LeMagnesium** [comment]
I will update it before the end of the day. It should just take a bit of time because we manipulated a lot of thigns in that mod.

**Comment by Ombridride** [comment]
Yes, i understand that point, take your time :)

**Comment by Ombridride** [comment]
@LeMagnesium Need to talk with you on IRC, please come :D

**Comment by LeMagnesium** [comment]
Ok, I will be clear.
This was re-written. So **either I destroy everything** and we use the new version with little addons like soundset, **either we keep our old heavy version**, which is the only way of maintaining such mechanisms as the music player. I cannot "improve" that mod, I can update it, or leave it as it's now. Period.
Maybe @tenplus1 would be helpful to say something if he has time to waste to read our old version's code but I doubt about that.

**Comment by Ombridride** [comment]
The goal is to use the new code wich is improved and Tidied.

So we nned to destroy everything and re-write/re-add all of our sounds into the mod ! (its a hug work... But it will be very interrest for server performances/ressources consumption)

**Comment by Ombridride** [comment]
We finally take the Tenplus1 version of this mod, it's lighter, we just need to re-add one music !

@ObaniGemini can you choose a music to add ?

**Comment by ObaniGemini** [comment]
One music ? 0.o
Hem... Let me think about it

**Comment by Ombridride** [comment]
Up

**Comment by Ombridride** [comment]
Up, need a name...

**Comment by ObaniGemini** [comment]
Ambivalent.ogg (Yes I know it's the first music of the mod)

**Comment by LeMagnesium** [comment]
You might want to get players to vote about that, but we don't have enough time for this. Ambivalent will be good then.

**Comment by Ombridride** [comment]
Ok, now assigned to @crabman77 

The idea(from @crabman77) is to create a mod with just this music and a loop for playing it. 
It's better because we don't touch the [ambience] mod is this case.

**Comment by ObaniGemini** [comment]
No, 20 30 minutes is a good time. And has most of the music of the mod are quite repetitive and calm, they fit easily has ambience musics.

**Comment by ObaniGemini** [comment]
Has been done some weeks ago
