### ISSUE TITLE
Spawning monster eggs recipe

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#135]
Sometimes you want to have an egg of monster, to make a zoo or whatever you want.
they exist already but are admin-only objects.

It could be nice to craft them, maybe with a chicken egg and:

sand for a sandmonster
dirt for a dirtmonster
a mese shard for the mese monster
etc. ...

Sure it's easy and fast to code (even if i have no idea how to make it.)

**Comment by Ombridride** [comment]
It's already in-game but not for "normal" players, only for administrators, sure it's easy to give this possibility to players, but we need to check many things **before we introduce spawing monster eggs to normal players** and it's not the priority for the moment...

**Comment by LeMagnesium** [comment]
> before we introduce spawing monster eggs to normal players

Specify please.

**Comment by Ombridride** [comment]
I take this issue, you will see what we need to check

**Comment by LeMagnesium** [comment]
What's up with that issue? Has any progress been made?

**Comment by ObaniGemini** [comment]
I think this shall be closed, egg is an admin-only feature.

**Comment by LeMagnesium** [comment]
According to @Ombridride's instructions I created 4 eggs for stone, dirt, sand and tree monsters. They're very difficult to craft, some more than the others, but still obtainable by players.
You can give me your opinions on the recipe, 2 of them are obvious, and the other 2 pretty random : https://github.com/LeMagnesium/minetest-minetestforfun-server/commit/7b3ca6b6330c18bade15a6d5cee4b5c70f910e35

**Comment by Ombridride** [comment]
(comments added to the commit)

**Comment by ObaniGemini** [comment]
(same here)

**Comment by LeMagnesium** [comment]
Updated, now comes with nyancat rainbows : https://github.com/LeMagnesium/minetest-minetestforfun-server/commit/1c6573b1e90b9363587522af08239dab2fc0c8c4

**Comment by Ombridride** [comment]
Perfect for me, it's interesting and ocnsistent

**Comment by LeMagnesium** [comment]
Do you agree on merging it then?

**Comment by ObaniGemini** [comment]
Shouldn't it be group:tree instead of default:tree ?

**Comment by LeMagnesium** [comment]
> Shouldn't it be group:tree instead of default:tree ?

Since the monster is apparently made out of "standard" tree, I used `default:tree` for both coherence and limitation of the collision between recipes.

**Comment by LeMagnesium** [comment]
There, merged.
https://github.com/MinetestForFun/server-minetestforfun/commit/1c6573b1e90b9363587522af08239dab2fc0c8c4
