### ISSUE TITLE
[money] Various bugs in shops 

### ISSUE THREAD

**Issue by LeMagnesium** [MinetestForFun/server-minetestforfun#140]
This issues is related to the [money](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/money) mod by @kilbith .
Various shops appeared to be broken, as they didn't exchange items, and caused crashes of the server.
**Please note that this mod is partially merged from it's source and modified by @Ombridride**

### Need to be fixed
Here are some of the problems :
 - Barter shops do not exchange
 - A partially empty message is shown when trading is completed (due to the removal of the command-based money system)
 - Normal shops do not detect items in inventorys, and eventually crash servers in some cases

### Ideas
 - Amputate money from its normal shops? Knowing that we use an item-based money system (coins), it would clear the code, and solve problems about shops and their compatibilities.

**Comment by kilbith** [comment]
J'ai pas ajouté les Barters shops dans mon fork, pour info.

Par ailleurs je recommande pas ce mod, trop d'accès en écriture/lecture sur un même fichier texte (ce qui veut dire une opération à la fois sur le serveur, donc : lenteur).

Vous devriez essayer quelque chose de plus évolué comme : https://github.com/t4im/economies

Voilou, bon courage pour la suite.

**Comment by Ombridride** [comment]
Can you keep us informed with the progression of this issue please @LeMagnesium ?

**Comment by LeMagnesium** [comment]
Fixed all of it.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f7bd110aa22f7c9eb25d287733f9a6411a60aeac

**Comment by Ombridride** [comment]
The textures of the barter shops aren't right.

for the moment the texture is just a normal chest, need to add great textured barter shops textures ;)
(like the jp ones)

closed this issue when it's done, thank you in advance :)

**Comment by LeMagnesium** [comment]
![?](https://lut.im/8bCoQ77e/wN3ano2z)

Good enough?
https://github.com/MinetestForFun/server-minetestforfun/commit/70b526345953075706858de72708cb40566f4155
