### ISSUE TITLE
Quest system

### ISSUE THREAD

**Issue by ElementW** [MinetestForFun/server-minetestforfun#145]
69ce8e826682e79716c114f7a429e11a4f2fc00b introduced the [quests](/TeTpaAka/quests) framework as well as some API proxy to simulate repeating quests.
However, given the things we might want to do, i.e. a quest system *à la World Of Warcraft*, a certain amount of work might be required. The quests should be as follows:
* [x] Able to have an icon
* [x] Able to be periodically renewing
* [x] Have an option to display only specific quests in the HUD
  * [x] Rework the HUD code as it is inflexible
* [x] Can be made of tasks, subquests, counting towards the quest completion
  * [x] Tasks display can be dependent on the level of completion of other tasks, and be disabled under other task conditions, allowing for branching paths in the quest development
  * [x] Have callbacks (`on_available`, `on_disabled`, triggered upon the required conditions are met)
* [x] Have a callback be called upon cancelling the quest

I've began work on [my fork](/gravgun/quests) and then will do a big PR to the author. The API changes are non-breaking.
Update: **DONE!** Was a tedious *task*! (heh, very punny)

MFF-side code such as the one that handles quest progress must stay on our side, only the relevant changes for [quests] must be made in the fork. From there on, we'll be able to fully harness the possibilities that the mod offers to have the quest system be as fit as we want it. Speaking of our side, here's what must be implemented as possible quest objectives:
**General:**
* [ ] Interaction with node N in list L(N)
  * [x] Digging → `minetest.register_on_dignode`
  * [x] Punching → `minetest.register_on_punchnode`
  * [ ] Right-clicking → ?
  * [x] Placing → `minetest.register_on_placenode`
  * [x] Including groups
  * [ ] With specific tools → callback parameters
    * [ ] Including groups!
  * [ ] At location L in list L(L)
    * [ ] Radius
* [ ] Travel N nodes → timer, each 0.5s or so
  * [ ] Whatever the transportation mean
  * [ ] By walking
  * [ ] By boat
  * [ ] By minecart
  * [ ] Handle the case of teleportation, otherwise it breaks things
    * Implement by doing a distance check (if too much then ignore)
    * Includes nether portal and warpstone-related teleportation
* [ ] Go to a certain location on map → same timer as above
  * [ ] Specified, otherwise default, radius around said point
  * [ ] Possibility to wildcard position on Y axis (i.e. no depth requirement)
* [ ] Go N nodes deep/high → same timer as above
  * [ ] Handle the case of the Nether where it should **not** trigger this objective
    * [ ] Unless explicitly stated. That is, "Go to the Nether" quest.
* [ ] Craft N of thing T → `minetest.register_on_craft`
  * [ ] Including groups!!
  * [ ] Using other thing O in list L(O)
    * ~~[ ] Including groups~~ Not this time, not really useful.

**Extended** (i.e. **knowingly** not possible without further mod modification):
* [ ] Pickup N of thing T in list L(T) → `item_drop` edit to add item pickup callback
  * [ ] Including groups!!!
  * [ ] Have them at the same time in inventory
  * [ ] Also check the bags!
* [ ] Drop N items of thing T in list L(T) → `item_drop` edit to add item drop callback
  * [ ] Including groups!!!!
* [ ] Reach a certain playerstat[us] stat level → Requires `playerstat[us]` to be introduced

**Hypothetical** (likely possible but need info):
* [ ] Defeat N mobs → ?
  * [ ] Of type T in list L(T)
  * [ ] Using weapon W in list L(W)
    * [ ] Including groups!!!!!
* [ ] Use item I in list L(I) N times → ?
* [ ] Use magical spell M in list L(M) N times → ?
* [ ] Wear pieces of armor A in list L(A) → ?
  * [ ] At the same time

**3rd party** (impossible/hard/needless to implement in `mff_quests` core itself, callbacks on said mods would be better, used in a `glue.lua` file or something):
* [ ] Speak to NPC N in list L(N) → Requires an NPC mod
  * [ ] Choose dialogue option O in list L(O) → Use NPC mod callback
* [ ] Buy/sell N of items I in list L(I) → NPC / buying/vending-machine mod required with appropriate callbacks

When info is known (or not) about a specific objective's implementation details, it can be moved back and forth between the lists.

**Comment by ObaniGemini** [comment]
"Go to a certain location on map"

I think there should be something for it starts quests (secret quests)

**Comment by mgl512** [comment]
Could the quest text be hidden in the HUD ?  I find it rather annoying to have it on my screen while I'm not actually dedicated to fulfill any quest.

**Comment by gravgun** [comment]
@mgl512 You can already hide the quest HUD in the settings...

**Comment by Ombridride** [comment]
@mgl512 look at your inventory, you can see a new icone, it's a __yellow exclamation mark__, just click on it and check what you can do :)

**Comment by mgl512** [comment]
Oh... :-$

**Comment by ObaniGemini** [comment]
@gravgun for "defeat N mobs", I've heard it would be possible with 0.4.13. And maybe could we add "defeat N players of F faction" :dancer:

**Comment by Ombridride** [comment]
Indeed @ObaniGemini, It will be possible in 0.4.13, we forced/pushed this feature to the minetest repository 1 or 2 mounths ago... (it was a long time we asked for this feature)

For example, In 0.4.13, we will able to create "Hall of Fame" / "graveyard" on the website with who killed who, PNJ killed player ? player killed PNJ ? player killed player with different pseudo ? etc...

**Comment by Ombridride** [comment]
@gravgun As-tu avancé sur ce gros projet ? Peux tu nous tenir informé s'il te plait ?

**Comment by gravgun** [comment]
@Ombridride No I didn't continue work on `quests` since a little while... Mainly because I spend most of my time on [glPortal](/glPortal/glPortal) right now.

**Comment by Ombridride** [comment]
Ok, thank you for informing me :D

**Comment by gravgun** [comment]
This is a bit delayed, I'm facing an issue with `quests`', simple quests are overlapped by tasked ones in the HUD for no apparent reason. Not updating until I fix this.

**Comment by Ombridride** [comment]
New feature needed : 
- [ ] Add a chat message to the player which just completed a quest, this message needs to contain : the name of the completed quests, the name of its reward and a message wich tell to the player it's in its inventory
Example : Congratulation, you completed the quest "Dig 20 stones"; your reward is a "Supper Apple" *1, this reward(s) is now in your inventory !

**Comment by Ombridride** [comment]
Strange thing found : 
![strange](http://i.imgur.com/fefwn9V.png)

**Comment by gravgun** [comment]
@Ombridride That issue you mention with HUD elements was fixed by a dumb fix in 4ea9175240064130923d376b183e3e8ef06d20a1.

**Comment by Ombridride** [comment]
@ElementW As we spoke about it a few days/weeks ago, do you planned to give us a "small" stable (but unfinished because no more features added) version of your quest system ?

**Comment by Ombridride** [comment]
I close this issue because the quests system isn't maintained anymore, @ElementW don't want to work anymore on it.

For the knowed bugs, there are fixed. And we will keep the stable version of quests for the daily quests.
