### ISSUE TITLE
Tweak the minerals generation

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#151]
#### Discussion

- Ataron : Mais tu veux en rajouter un ou garder les mêmes mais plus bas ?
- MinetestForFun : garder les meme et en rajouter pour plus bas
- MinetestForFun : pour le diamant et mithril
- MinetestForFun : comme ça ont augmente le taux de diamant/mithril en profondeur
- MinetestForFun : je crois qu'actuellement, il est inutile de miner en dessous de -2048 car le taux ne change pas entre -2048 et -19600
- MinetestForFun : le but c'est de niveler le taux, l'augmenter plus on s'approche de -19600 et cela pour encourager le minage en profondeur, pour acquérir de meilleur taux de récompenses (diams/mithril)

#### Taux de génération de minerais

Actuellement, en dessous de -x, aucune chance supplémentaire de trouver du minerais n'est donnée, le but de ce ticket est d'ajouter entre -5 000 et -19600 des chances supplémentaire de dropper des minerais rare tel que le diamants et mithril !

- [x] Augmentation du taux de diamant entre -2048 et -31000=> pas ait finalement, le taux est assez haut
- [x] Augmentation du taux du mithril entre -2048 et -31000

#### Tableur

- [ ] Créer un onglet et mettre TOUTE les chances des minerais avec profondeur dedans

**Comment by Gael-de-Sailly** [comment]
De très rares grands filons de mithril à grande profondeur, suffisament grands pour attirer les joueurs, mais suffisament rares pour ne pas ruiner le gameplay.

PS : désolé pour les petites erreurs d'assignee, je pensais qu'on pouvait mettre plusieurs personnes à la fois

**Comment by Ombridride** [comment]
Gael, il faut que tu me dises stp ou modifier les chunck générés en profondeur, je ne le retrouve nulle part ! :/

Pour les minerais en profondeur, j'aurais bien vu un diamond et mithril x2 en -19600, donc en -2048 et -19600, on decend de plus en plus vers un taux de plus en plus haut atteingant 200% de ce que l'o ntrouve normalement.

**Comment by ObaniGemini** [comment]
200% ? sachant qu'il y a plus de 17000 blocs d'écart entre ces deux valeurs, 400% ne serait-il pas déjà un peu plus approprié ?

**Comment by Ombridride** [comment]
On verra en temps voulu, il ne faut pas que la valeur soit trop élevé.

300% pourrait etre un juste milieu

**Comment by ObaniGemini** [comment]
Je ne sais pas si vous vous rendez compte de ce que c'est de miner 17000 blocs

**Comment by Ombridride** [comment]
un joueur qui pose une home a -18000 et a une maison au spawn peut etre problématique. Qu'il est deja +300% en plus GRACE a son courage d'aller "une fois" en -18000, je pense que ce ni trop abusé, ni pas assez.

**Comment by Gael-de-Sailly** [comment]
On ne peut pas augmenter la quantité de minerais de façon continue. C'est forcément par seuils.
Pour l'instant le mithril est défini comme 1 bloc sur 11³, à partir de -1024, et n'augmente pas en profondeur.
Je propose d'ajouter trois seuils :
1. À partir de -2048, filons de 2 blocs sur 15³ en plus
2. À partir de -4096, filons de 5 blocs sur 22³ en plus
3. À partir de -12288, filons de 20 blocs sur 28³ en plus
Ça donne un taux de 362 % après -12288. Mais je pense que c'est plutôt la taille des filons, même rares, qui va motiver les joueurs, plutôt que le taux.

Il est aussi possible d'atteindre “facilement” les grandes profondeurs en allant dans le nether et en minant vers le haut, il ne faut pas l'oublier. Donc éventuellement baisser (un peu) la quantité de minerais entre -16384 et -19600.

PS : quel est l'intérêt d'utiliser des puissances de 2 ?

**Comment by Ombridride** [comment]
```
Il est aussi possible d'atteindre “facilement” les grandes profondeurs en allant dans le nether et en minant vers le haut, il ne faut pas l'oublier. Donc éventuellement baisser (un peu) la quantité de minerais entre -16384 et -19600.
```
=> useless, on peu pas remonté du nether, a partie de -19600 on est retp dans le nether.

**Comment by Gael-de-Sailly** [comment]
Pour le nether : je ne savais pas qu'on était retransporté à -20000.

Pour le mithril, si tout s'additionne, c'est fait exprès. Chacun de ces 4 paramètres génère à peu près le même nombre de minerais :
* 1÷11³ = 0,075%
* 2÷15³ = 0,059%
* 5÷22³ = 0,047%
* 20÷28³ = 0,091%
Donc si on ne les additionne pas, on n'augmente pas la quantité de mithril.

Je ne vois vraiment pas où c'est dit que le mithril atteint son taux maximal à -2048.
À ma connaissance il n'y a qu'un seul `minetest.register_ore` pour le mithril, dans moreores, avec une profondeur de -1024 à -31000.

**Comment by Ombridride** [comment]
Oui -1024, je me suis trompé pour le taux max actuel.

Quand j'avais refais les taux des minerais il y a longtemps, je ne m'y étais pas pris comme toi... Tes calculs ne semble pas incorrecte, mais quelque chose me chagrine...

As-tu testé en local ?

**Comment by Ombridride** [comment]
@Gael-de-Sailly tu peux nous tenir informer sur cette amélioration ?

**Comment by Gael-de-Sailly** [comment]
Non je n'ai pas testé. Je suis à nouveau en vacances, je pensais rester plus actif que ça ces derniers jours. Mais là il fait tellement moche que je ne vois que ça à faire.

Je vais tester aujourd'hui.

**Comment by Gael-de-Sailly** [comment]
Rectification : l'ordi n'arrive pas à faire tourner MFF.

**Comment by Ombridride** [comment]
désactive des mods, tu n'as pas besoin de grand chose pour tester la generation de minerai
mapgen, mods de generation de minerais, et rien d'autre

**Comment by ObaniGemini** [comment]
Up, this issue seems forgotten

**Comment by Gael-de-Sailly** [comment]
Not forgotten, that's done, except the spreadsheet that will be completed soon.

**Comment by ObaniGemini** [comment]
Ok thanks, I thought it was already done ^^

**Comment by Gael-de-Sailly** [comment]
https://github.com/Gael-de-Sailly/minetest-minetestforfun-server/blob/ores_spreadsheet/other_things/Tableau-valeurs-MFF.ods

**Comment by Ombridride** [comment]
Perfect, thank you @ObaniGemini  to re-up this issue and thank you @Gael-de-Sailly for the spreadsheet update :)
