### ISSUE TITLE
[item_drop] : add item pickup and drop callbacks

### ISSUE THREAD

**Issue by gravgun** [MinetestForFun/server-minetestforfun#155]
For a plethora of tiny, interesting and useful reasons (such as quests, see #145, and future money pickup/drop mechanisms), at least two callbacks must be implemented in `item_drop`:

* `on_pickup(picker, itemstack)`
* `on_drop(dropper, drop_entity, itemstack)`

Please note this must *not* be done as an inventory watchdog timer, since we *don't* want to handle cases where there are no actual drops/pickups, that is, item giving/removal from a script or command, which is left to be handled by the mods who want to be notified about it.

**Comment by LeMagnesium** [comment]
`on_pickup` would be easily implementable in `item_drop` itself, but `on_drop` would not be. Drop is an engine feature, and there is no API to handle or manipulate it in any way.
Even though these two callbacks would be great to have, one of them actually requires to be hardcoded into the engine.

**Comment by LeMagnesium** [comment]
I thought about an `on_drop` callback, and the only way to launch methods registered in that callback table would be to override `__builtin:items` to start them when they're activated. What do you think of that idea?

**Comment by gravgun** [comment]
73fb22c48193a8acff6a511bfb8b30e67a473288

**Comment by Ombridride** [comment]
Great, im happy to see this issue done ! :)
