### ISSUE TITLE
Instant resurrection

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#161]
Many players usebug with the resurrection formspec and click very fast on the __resurrect__ button to resurrect instantly where they was dead before, it's maybe a core usebug BUT, maybe we can reduce its impact :

- Add a timer to the resurrect formspec
- Remove the formspec and force the player to wait 5/10sec before an automatic resurrection
- Any other ideas ?

**Comment by ObaniGemini** [comment]
Some say you just need to keep pushing forward button to respawn at the same place you died. Personnaly I don't think it works, so if it's only lag, I agree with those proposals :)

**Comment by Cyberpangolin** [comment]
+1 A short timer sounds good.

**Comment by ObaniGemini** [comment]
And when timer is over, click on "respawn now"

**Comment by LeMagnesium** [comment]
On some older version of minetest, dying while pushing space bar would always respawn you where you died.
By the way we have no control over the respawn formspec, it's a builtin feature. Yet, we may create a mod that register a player's position whenever they die, and where they respawn, and check. But that's just another mod, and it's too much for just some respawn bug due to lag.

**Comment by ObaniGemini** [comment]
Does this still work on 0.4.13 ?

**Comment by LeMagnesium** [comment]
Apparently it's even worse in 0.4.13 and you only need to be moving (ie. sinking) to trigger it.

**Comment by ObaniGemini** [comment]
Can we close this issue ?

**Comment by Ombridride** [comment]
We can't close an issue without a solution.

**Comment by LeMagnesium** [comment]
> without a solution.

We don't have any; we don't have the power to. The only person who have the power to solve that are the developpers. This problem is part of a bigger problem that is anticipation of both sides (server and client) in the game; and that won't be fixed soon.

**Comment by Ombridride** [comment]
@crabman77 can you inform us about your progress in this issue ?

**Comment by crabman77** [comment]
On ne peut rien faire pour le reste, c'est l'engine.

**Comment by Ombridride** [comment]
Linked to https://github.com/minetest/minetest/issues/3664

Closed in our issues tracker because it's now posted on Minetest issues.

**Comment by crabman77** [comment]
fixed soon, we must use minetest.register_on_dieplayer instead of minetest.register_on_respawnplayer in bed mod, player is teleported instantly on dead.

old fix can be removed.

**Comment by Ombridride** [comment]
Happy to read this, thank you for your following of this issue @crabman77

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/c54bdbef03fe98821f8e67fe79efa116feb52b6e
