### ISSUE TITLE
The texture of the lever is glitched

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#162]
The texture of the lever is glitched

**Comment by ObaniGemini** [comment]
What do you mean "glitched" ? Do not hesitate to post photos and to describe the problem you find :)

**Comment by Ombridride** [comment]
glitched = bugged, indeed with the last update of mesecons, the interruptor texture is strange : need to check this !

**Comment by LeMagnesium** [comment]
A screenshot would be appreciated indeed.
![screenshot_20150731_205012](https://cloud.githubusercontent.com/assets/6785985/9014985/29f0aa24-37c6-11e5-9a2a-edf58493b1ea.png)
![screenshot_20150731_205015](https://cloud.githubusercontent.com/assets/6785985/9014986/29f0a56a-37c6-11e5-9bf6-2664c110c504.png)

I actually think this is not a glitch. look at the textures in `mesecons_walllever`, they are correctly fitting the lever.

**Comment by Ombridride** [comment]
I reported this issue to the jeija repository : https://github.com/Jeija/minetest-mod-mesecons/issues/237

**Comment by VanessaE** [comment]
Works fine in the upstream Mesecons.  Are you sure you're not using an older model of the wall lever?  The way textures were used on it has changed at least once since introducing that model.

**Comment by LeMagnesium** [comment]
I re-updated it right now, it works perfectly fine now.
https://github.com/MinetestForFun/server-minetestforfun/commit/3a930c81180e0b1a12d7391b11ab12eb100df3a6

![Wall Lever](https://lut.im/VNqudjfK/oQM4Stcj)

**Comment by Ombridride** [comment]
Thank you for your intervention @VanessaE ! :)
