### ISSUE TITLE
Only 2 Factions

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#165]
#### This is a proposal about factions mod.

                              "2 kingdoms fighting for a same place"

The idea would be to force players to join one of the two teams. It would reintroduce team fight in MFF, or economy and diplomacy (Buy industries, exchange them, take them,...)

##### a modified factions mode : 
- allow faction creation only for admin
- allow faction admin to give his status to another player by destroying his  admin status

##### areas mod : 
- areas could add player's faction in the area name.
- opened areas for a "n" faction.

##### privileges in shops depending on your faction (if "x" faction, "n" prize)

**Comment by Cyberpangolin** [comment]
"attack ennemy's industries"
hum, I think that it's an opened door for griefing, and I'm totally against it. I would prefer keypoints, of "flags" that you should capture by staying near them, and give points to your team, and access to special zones with bonus items.

Idem, I think that "forcing" a player to choose his/her team at the beginning is bad. I want to choose and to know who I am with.

I would prefer a way to remember "you should choose your team!", with a "stay neutral for now" button. A neutral guy could be attacked or protected by anyone.

Another thing, maybe the teams should be proportional with (the square root of?) the time ingame: if I am in team 1 and I played 324 hours, I may be "more important" than someone who came 10 minuts ago.

there should be a way to chat with our team only.

Last thing: please consider reduce drastically the mobs spawning if this is done: I want to stay a minimum alive!

Thanks for your idea Obani :), I hope you are not afraid by my ideas :P

**Comment by gravgun** [comment]
I agree with @Cyberpangolin, attacking and all would promote griefing. That's not bad *per se* but it must **not** be serverwide, hence I propose to have a restricted (large) zone on the map where faction fights takes place.

**Comment by ObaniGemini** [comment]
Thanks you for your answer @Cyberpangolin .
For the "grief" part, I thought about it because it's easier to make work and more "war-like". But the capture of strategic points is also a very good idea, as if it would add some work to our developpers :D.

For the way to choose a team, the problem is that there would be to many neutral players. So a good idea would be to add a limit date to choose team (example : 10 hours of playing ). For that we could use the system of award mod (50h played) and change the hud for the button "stay neutral for now" doesn't appear.

@gravgun : for faction fights, I think there should not be specific places. But I'm actually thinking about making some big arenas to fight against many players :)

**Comment by Cyberpangolin** [comment]
An example of strategic point: My factory. When finished, it will have the ability to produce you for free some food, some wood, and oil, and it will automatically cook your mining products for you ;)

we should find other big useful buildings like that.

**Comment by mgl512** [comment]
Why not play OpenArena instead, or this factions war on a Lord of the Test server, if it still exists ?
Minetest is not even close to a wargame. It would just be "Race for the best stuff, use weapon / eat restorative or cheat". Hope you don't lag in one of those simplistic fights and repeat. And if you're a builder, an explorer or someone peaceful, please leave.

**Comment by ObaniGemini** [comment]
@mgl512 this not so much about team fight. Maybe should I talk about guild or maybe keep the faction  name ?

**Comment by Cyberpangolin** [comment]
guilds sounds more peaceful, I would prefer that.

**Comment by ObaniGemini** [comment]
In fact, the first idea was the team fighting. But the more I think about it, the more I think that it would be good that people are in one of two factions.

And the more I think about it, the more I think many people wouldn't like to fight or to make attacks against the other faction.

But has factions would be like nations without a precise territory, and that fighting wouldn't be a pleasant thing for some players, economy would be also an important thing, and diplomacy so.

As told by @Cyberpangolin , a good idea would be to add key points that could be bought, taken, exchanged by the countries. Those key points could be factories, shops, castles,...

Also, there could be competitions for let the fight exist in MinetestForFun server, and to add some funny attractions (races, labyrinths,...).

What do you think about it ? :D

**Comment by ObaniGemini** [comment]
Factions were removed and no one seems interested by the idea, so I close the issue
