### ISSUE TITLE
Quest configure HUD bug

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#174]
Go into the configure menu in the quest button
click on enable HUD
--> enable HUD is set on.
then on autohide HUD
--> enable HUD goes back to off, autohide is set on

now let's troll it:
re-click on enable HUD

--> Autohide stays on.
You can then make what you want with them: activate one, both, or none.

As I don't understand what should be auto-hidden, I let you see if:
OR we need one choice only, the gui should be adapted to explain that (put a rectangle around both)
OR enable HUD should not be un-thicked.

Idem: Remove the central messages thick, enable HUD is automatically un-thicked. Maybe you don't want the central messages but you want the quest HUD...

![capture du 2015-07-28 09 42 07](https://cloud.githubusercontent.com/assets/12512762/8926194/25e5d0cc-350e-11e5-982d-f02b838f14ba.png)
Please note the yellow text on the right, two of them are superposing. Due to this bug?

**Comment by gravgun** [comment]
The text shadow (too dark) also suggests an abnormally high number of text HUD elements are drawn. Please note I didn't make any changes (until now) on the config page, but changed the way the HUD code works, so things might have broken.

**Comment by gravgun** [comment]
A bit late, but this is fixed since MinetestForFun/quests@1fec0e3e2efd2897acd0231646e0bce80b78872b.
