### ISSUE TITLE
Convert globalstep + timer into minetest.after

### ISSUE THREAD

**Issue by ElementW** [MinetestForFun/server-minetestforfun#179]
Some mods implement their tick logic using globalstep callbacks and a timer variable. This is heavy because the Lua VM must execute every callback for each server step, however if there is a timer (generally 1s) most of the time no actual code gets executed, just the timer variable {in,de}cremented.
Replacing this technique by [`minetest.after`](http://dev.minetest.net/minetest.after) would reduce code duplication as well as increase performance since all the timers this function creates are handled by the same loop (in [builtin/game/misc.lua#9](/minetest/minetest/blob/master/builtin/game/misc.lua#L9)), reducing the need to do context switches (locals) and allowing LuaJIT to streamline timer ticking to the maximum possible extent, thus increasing performance.

**Comment by Ombridride** [comment]
+ 10 000 !

**Comment by Ombridride** [comment]
=> WARNING : La consommation de RAM du serveur a explosé depuis l'incorporation des clases <=

**Comment by LeMagnesium** [comment]
Are you looking for something shaped like this?
http://zerobin.qbuissondebon.info/?6b50b35bbcc33ffe#mllFfsOvOw65UrW2paR0q4TO7cOBn7d5E4i/LWUpuQE=

**Comment by gravgun** [comment]
`shutdown`: d77c8c24798a230f7119efacfbe9d2af53d0228f

**Comment by Ombridride** [comment]
The RAM used was due to Obani WorldEdit abuse ! :D Now stable and Completly good since we reboot daily the server for a __RAM reset__ between 4:30AM and 5hAM :)

!(graphs_now)[http://i.imgur.com/0iImx4Z.png]

**Comment by gravgun** [comment]
Left to do as of now:
- [ ] `3d_armor`
- [ ] `chatplus`
- [ ] `hbarmor`
- [ ] `hbhunger`
- [ ] `hudbars` (maybe not)
- [ ] `irc`
- [ ] `mana`
- [ ] `maze`
- [ ] `mesecons`' actionqueue, probably not since it could dangerously alter mesecons, and is already a function queue implementation
- [ ] `nether`
- [ ] `pipeworks`
- [ ] `plantlife_modpack/nature_classic`
- [ ] `random_messages` (the absolute fuck?)
- [ ] `riesenpilz`
- [ ] `runes`
- [ ] `snow`
- [x] ~~`sprint`~~ No, that'd greatly deter user experience
- [ ] `tsm_pyramids`
- [ ] `unified_inventory`
- [ ] `worldedge`
- [ ] `action_timers` (?)
- [ ] `biome_lib`
- [ ] `fishing`

**Comment by Ombridride** [comment]
Happy to see you continue this important work @gravgun 

I hope you will done it quickly :)

**Comment by HybridDog** [comment]
If you grow big trees, e.g. when abms catch up and makes them grow all at once, you maybe could use a scheduler.
https://github.com/HybridDog/function_delayer
l am not sure if it really works because l didn't manage to do tests for it yet.

**Comment by gravgun** [comment]
Unassigning myself, the Level 4 + 5 work I'm doing on Skyblock being the last contributions I'll make to any Minetest-related repo.

I just can't stand that sh!t engine anymore, same for its developers.

**Comment by HybridDog** [comment]
>I just can't stand that sh!t engine anymore, same for its developers.

It could be worse, when supertuxkart gets developed, the newer version lags a lot more then the older one. It's actually just a cart racing game, but you need a new fast computer to be able to play it without those lags.

**Comment by Ombridride** [comment]
>It could be worse, when supertuxkart gets developed, the newer version lags a lot more then the older one. It's actually just a cart racing game, but you need a new fast computer to be able to play it without those lags.

In my point of view, the newer version of SuperTuxKart is really great, it's an awesome modelization work and the developpers are really smart about the future of they racing game. Yes, with the new models you need a more powerful computer, it's just normal.

>  Minetest is playable on fairly every pc.
Not really, Minetest is incredibly heavy and poorly made, but we deal with it (i just repeat all our dev team and other Minetest devs i know always said, i'm not an enough good dev to see the core engine and understand it clearly)

**Comment by LeMagnesium** [comment]
> Minetest is playable on fairly every pc.

I think the most important word here is `fairly`.
I can't fully blame the developers for the quality of the engine, considering our lags are the result of about 210 mods loaded and running at once. But even on client-side, minetest (in its development version usually, but also in the last releases) tends to be heavier and heavier. I've already seen Minetest eating up to 2~3Gib of memory on my laptop, of which about 70% came from one or two clients running at once, and the last 30% about the dedicated server running.
But not only because of the quality of the engine, @gravgun is mostly angry at the mindset and development methods that have Minetest's developers, of sometimes refusing to add content to the lua game since "it should be done by a mod" or turning down pull-request for minor codestyle issues, or simply [forgetting about them](https://github.com/minetest/minetest/pull/3443). I think that's the explanation he gave us.

**Comment by HybridDog** [comment]
l think freeminer tries to get rid of such problems, but there are not very many people helping it

**Comment by gravgun** [comment]
And I'm not willing to help Freeminer either. Going through git revisions (even the ones before they forked from MT) makes me puke, the code is as ugly and inefficient as it is now.

**Comment by neoascetic** [comment]
@gravgun This is sad. Do you know a better voxel game/engine with good modding facilities?

**Comment by gravgun** [comment]
@neoascetic The one I'll be making. But so far, Minecraft is proprietary, anything inheriting from Minetest is crap to me, Terasology is awfully slow (Java, eh!), ... So I decided I'd be making [my own engine](https://github.com/gravgun/Diggler). Right now it's not in a working state (and I don't have much time to spend on it currently) but it aims at being extremely moddable (you can read [in its spec](https://github.com/gravgun/Diggler/blob/master/doc/spec.md) that I declare war to Minetest's dev and mod community with it -- that is, once I finish skyblock's level 4 and 5).

**Comment by ObaniGemini** [comment]
@gravgun : I think you're going the wrong way. Free/Open-Source is also about fraternity. So you might not declare war to Minetest, but tell that you want to follow the Minetest concept without making all the things that you don't like in Minetest. Here, it is just like if you wanted to have all the Minetest community against you, which shall not be the goal. As your project is just at an early WIP state, it would be easy for Minetest community people seeing your project to depreciate it.

But being more peaceful would only bring new developers to it IMO. This war declaration you want to make would only end in two possibilities : end of Minetest or end of your project (which is more probable at this point).

Let Minetest kill itself, and make talk about your project. Peacekeepers were always better considerated than war children in Free/Open-Source community.

**Comment by Ombridride** [comment]
@ObaniGemini 
Minetest needs to be at least 75% rewritten, create a new Free alternative to Minetest is the best thing to do, im with @gravgun ;)

**Comment by neoascetic** [comment]
Am I right saying that it is enough to rewrite server-side and leave clients as-is?

**Comment by ObaniGemini** [comment]
> @ObaniGemini
Minetest needs to be at least 75% rewritten, create a new Free alternative to Minetest is the best thing to do, im with @gravgun ;)

As I am. But declaring war to Minetest is not a good solution.

**Comment by gravgun** [comment]
@ObaniGemini That war thing was just written in a rage wave. I know F(L)OSS is about community. But nothing is wrong saying X or Y's community is (mostly) made up of people we might not like.

For instance, look at how many people say Linus Torvalds is a jerk. He is, he knows, the story is over. Like Linux, dislike it, OSS is also about choice.

In the same vein, I dislike `node.js` for being an overall bad piece of software, but I spit at its community for being full of idiots spending more time talking about social justice than making the project better.

Minetest is a good project overall. It works. It has mods. It has a community. OSS is about involvement and improvements, but only if you want to. I don't want to participate to MT's ecosystem anymore. There are things you don't fix without a LOT of work, and MT is one of those. I won't fork MT, I won't take any implementation source from MT. You sometimes must reinvent the wheel because the ones already created aren't round enough.

**Comment by ObaniGemini** [comment]
@gravgun : that was a good answer. But what you write is not always showing what you think. This comment helps more to understand your idea about this subject than what you tell in your repo, that could be badly interpreted. Also, nice work on the doc ;)

**Comment by neoascetic** [comment]
`minetest.after` seems to be fixed in the latest master by minetest/minetest#3593

**Comment by Ombridride** [comment]
Thank you for the information @neoascetic hope it will be merged soon...

**Comment by ObaniGemini** [comment]
It was merged 9 days ago https://github.com/minetest/minetest/commit/4ac1e9bccbd0222ab779b3fc4d2144d60e1f2b49 https://github.com/minetest/minetest/commit/ad884f23d4e73d38ce0f529de49591dd66cee44d

**Comment by Ombridride** [comment]
Ok, thank you for the information, weneed to wait 0.4.14-stable now :)

**Comment by Ombridride** [comment]
All of our servers are now on Minetest 0.4.14-Release, is it possible to done this issue ?

**Comment by HybridDog** [comment]
Ombridride, the function_delayer mod can be used to automatically delay the execution of the step if the server is lagging.
https://github.com/HybridDog/titanium/blob/master/init.lua#L334-L339

**Comment by Ombridride** [comment]
Up, someone can finish this task please ?

**Comment by LeMagnesium** [comment]
I'm gonna continue that.

**Comment by AcidNinjaFWHR** [comment]
We have 25 files that still use the register_globalstep. as @LeMagnesium told me, some cannot be changed, but maybe some do. We have to check these.

- [ ] minetestforfun_game/mods/default/player.lua (L 119)
- [ ] minetestforfun_game/mods/default/functions.lua (L 265)
- [ ] other_things/irc-old-save/init.lua (L 58)
- [ ] mods/mesecons/mesecons/actionqueue.lua (L 61)
- [ ] mods/mesecons/mesecons/util.lua (L 257)
- [ ] mods/hbhunger/init.lua (L 100)
- [ ] mods/riesenpilz/init.lua (L 812)
- [ ] mods/biome_lib/init.lua (L 429)
- [ ] mods/unified_inventory/item_names.lua (L 38)
- [ ] mods/cozy/init.lua (L 1)
- [ ] mods/sprint/wsprint.lua (L 41)
- [ ] mods/sprint/esprint.lua (L 84)
- [ ] mods/pipeworks/luaentity.lua (L 57)
- [ ] mods/pipeworks/luaentity.lua (L 312)
- [ ] mods/hudbars/init.lua (L 354)
- [ ] mods/maze/init.lua (L 410)
- [ ] mods/runes/amulets.lua (L 64)
- [ ] mods/runes/handlers.lua (L 111)
- [ ] mods/random_messages/init.lua (L 107)
- [ ] mods/snow/src/snowball.lua (L 70)
- [ ] mods/snow/src/falling_snow.lua (L 62)
- [ ] mods/snow/src/falling_snow.lua (L 230)
- [ ] mods/plantlife_modpack/nature_classic/global_function.lua (L 15)
- [ ] mods/tsm_pyramids/room.lua (L 65)
- [ ] mods/action_timers/init.lua (L 51)

**Comment by HybridDog** [comment]
>mods/riesenpilz/init.lua

no
>mods/maze/init.lua

fixed,
you use my version, which uses voxelmanip, don't you?
>mods/snow/src/snowball.lua

fixed
>mods/snow/src/falling_snow.lua

fixed
> mods/snow/src/falling_snow.lua

no

**Comment by ElementW** [comment]
@AcidNinjaFWHR Refer to [my list comment](https://github.com/MinetestForFun/server-minetestforfun/issues/179#issuecomment-137957145) for the mods which we shouldn't edit.

**Comment by Darcidride** [comment]
I think we need to merge all lists to one last list. With the actual @HybridDog comments and @ElementW comments, and also with the already converted mods... 
In this way, it will be easier to finish this huge work..

**Comment by LeMagnesium** [comment]
After checking which mods I shouldn't, couldn't and could easy alter quickly, I compiled a final list of what hasn't been done yet. Also, we will not change default, the things in there **need** globalsteps.

 - [ ] HBhunger
 - [ ] HUDBars
 - [X] PipeWorks (https://github.com/MinetestForFun/server-minetestforfun/commit/e538a7a152ed0e5a705964e601a7bf859a35b610) (https://github.com/MinetestForFun/server-minetestforfun/commit/7bf6c9e16e4c44a28a572efa7114c7f228c40a67)
 - [X] Random_Messages (https://github.com/MinetestForFun/server-minetestforfun/commit/7bf6c9e16e4c44a28a572efa7114c7f228c40a67)
 - [ ] Runes (the rune's globalstep will become a glyph)
 - [ ] PlantLife's Nature Classic (Although I haven't fully assessed whether or not it is worth tempering with)
 - [X] Snow (https://github.com/MinetestForFun/server-minetestforfun/commit/b769c03b620a36d7e048b9ac0712de08e0625307)
 - [X] TSM_Pyramids (https://github.com/MinetestForFun/server-minetestforfun/commit/66c55825e8c378e09b221f6fb6a3a11dbbbc9009)
 - [X] Action_Timers (https://github.com/MinetestForFun/server-minetestforfun/commit/f3001afa7b37931fed479e024fcd306d6b6d2a32)

Default, Mesecons, Riesenpilz, Sprint, Unified_Inventory and Biome_Lib shouldn't be touched in my opinion.

**Comment by Darcidride** [comment]
@Coethium 
Don't forget to update the @LeMagnesium list with your commits ;)

**Comment by Coethium** [comment]
PlantLife's Nature Classic : i think it can keep globalstep, it makes things only when server is fast to response, does nothing when server is slow to respond.

**Comment by Darcidride** [comment]
That's right, i think we can keep them
