### ISSUE TITLE
problem with the giant fern trunk

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#180]
normaly the giant Fern is cut by itself when i cut the first bottom trunk.
When it's in area, juste one is cutted.

The trunk give 2 trunk by node it's ok ?

the tree fern crow give too many sapling.

**Comment by farfadet46** [comment]
i can get 10 sapling(be placing,remove it) before the tree fern crow break

**Comment by LeMagnesium** [comment]
All of this sounds like area is messing with the autodig system, it should either be removed or improved.

**Comment by ObaniGemini** [comment]
Up, this issue seems forgotten

**Comment by LeMagnesium** [comment]
I first fixed the double drop. https://github.com/MinetestForFun/server-minetestforfun/commit/58bfcadec6c3eb1b0d4992f12cb9d7d8da1bbf9a
About `[areas]` blocking the drop system, I cannot do anything.. Ferns' trunks use `after_dig_node` which doesn't give the name of the digger..
TODO: Check the tree fern crow.

**Comment by crabman77** [comment]
fix autodig https://github.com/MinetestForFun/server-minetestforfun/commit/c60abcd1cf987fcada3687b5c137cfe863aa6709
reste TODO: Check the tree fern crown.

**Comment by LeMagnesium** [comment]
It works. Issue fixed.
![](https://lut.im/YtFDi1lRaN/sKnswqZZU51aHFVR)

**Comment by LeMagnesium** [comment]
It is okay now : 

![](https://lut.im/nnUkHiu3hW/lTHsNLpsOIE8MwVw)

Can we close?

**Comment by Ombridride** [comment]
Yes, we can close it.
