### ISSUE TITLE
Snow mapgen bugs

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#189]
The snow mapgen seems to sometimes have a bug with the snow_trees generation, indeed instead of leaves, sometimes they are created with stone/gravel, like in caves...

![snow_biome_tree_mapgen_bug](http://i.imgur.com/h1LjXjw.jpg)

**Comment by Gael-de-Sailly** [comment]
That's very strange but that's the wanted behaviour of this mod. That's the "alpine" biome that transforms trees into stone to create peaks.

**Comment by Ombridride** [comment]
Ok, need to remove this feature, no needed and certainly never over, that's not very beautiful...

**Comment by ObaniGemini** [comment]
I don't agree, but maybe I'm the only one to think this ^^. I think it isn't a bad idea, it just looks too much like trees...

**Comment by Ombridride** [comment]
Hi @Gael-de-Sailly, can you done this tweak please ?

Or keep us informed about the progression of this task ?

**Comment by ObaniGemini** [comment]
@Ombridride : Can we keep this in the mapgen ? If they aren't rare enough so maybe dicrease their generation, but actually, I think it's a very cool mapgen addition. It permits to make races or some kind of floating villages.
As snow mapgens are not really enjoyable mapgens to build actually, could we keep this mapgen feature ? :D

**Comment by Ombridride** [comment]
No, we will removed this feature.

It's a bugged mapgen feature and it's not beautiful

You can use actual bugged already generated areas if you want to do races wth it ;)

**Comment by ObaniGemini** [comment]
:(

**Comment by Ombridride** [comment]
No no and no... This "feature"/"bug"(name it like you want) is __UNFINISHED__, we can't add it ;)

(PS : stop "up" this issue please, thank you in advance)

**Comment by ObaniGemini** [comment]
Can we close it ?

**Comment by Ombridride** [comment]
No, this issue isn't fixed, need a mapgen dev to removed this stone useless feature.

**Comment by Gael-de-Sailly** [comment]
Please, I don't know well this code, and I've not a lot of time.

**Comment by Ombridride** [comment]
No problem, just need an another person to do this job :)

**Comment by ObaniGemini** [comment]
Maybe can we just ask @paramat ?

**Comment by paramat** [comment]
Just remove this block of code 366 to 377 https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/snow/src/mapgen_v6.lua#L366

**Comment by Ombridride** [comment]
Thank you @paramat 

https://github.com/MinetestForFun/server-minetestforfun/commit/ef68f144464de84222242744591824f03c1e4bb0

This unfinished feature is now disabled, closed the issue.
