### ISSUE TITLE
Spiders and poison

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#196]
Add poisonous spiders fro mthe __Adventuretest [Alpha]__ subgame

No need to tweak a lot, just change the actual spiders with this feature (and add it to the api)

**Comment by ObaniGemini** [comment]
Up, this issue seems forgotten

**Comment by LeMagnesium** [comment]
I was cloning the repository this afternoon to do it.

**Comment by ObaniGemini** [comment]
+1. And with sharks now it's even worse. Close the issue ?

**Comment by Ombridride** [comment]
If we add poisonous attacks to the spider,s it's a new type of attack (debuff/damage over time), it's a good point for futur bosses and if it'w merged to the mobs redo API, it will be maybe added to the C++ future mobs core api...

It also add a new way to kill spiders, nobody will want to be touched by this monsters anymore, the bow/spells will be your friend. 

An idea is also too reduce the resistance of the spiders be cause they will be more dangerous with this poison

**Comment by LeMagnesium** [comment]
**I do not want to modify mobs' API** it's already very heavy, and difficult to merge. This feature is not worth the bother of modifying the existing unstable and unsure code.

**Comment by Ombridride** [comment]
Won't be added, to many tweaks to the API is needed... 
Maybe this feature will interest @TenPlus1

If it's added to the mobs redo initial mod, we will add it with pleasure. :)

I closed the issue
