### ISSUE TITLE
MTsatellite automappercolors mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#197]
10 times faster ??? https://forum.minetest.net/viewtopic.php?f=14&t=10278&start=50

**Comment by Ombridride** [comment]
@gravgun Can you checked this modified automappercolor script please ?

**Comment by gravgun** [comment]
This is basically a Go rewrite of my script. No doubt it will run way faster than my Python script (even if using PyPy). The only change is that it can control transparency options according to node drawtypes.

But other than that, nothing else changed. Really low priority "issue", to implement if we have time.

**Comment by gravgun** [comment]
BTW I have zero control over the server's configuration, so that's up to you @Ombridride, not up to me. As I said, go ahead.

**Comment by Ombridride** [comment]
It was assigned to you because of the check ;)
And yes, this task is for me. But not really a priority because your python script is already instant server side :)

**Comment by Ombridride** [comment]
Will be applied when the server will me on Debian 8, i need to planned an upgrade campaign

**Comment by Ombridride** [comment]
Closed here, can be followde here https://github.com/MinetestForFun/server-minetestforfun/issues/456
