### ISSUE TITLE
HUD bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#214]
#### HUD bug 

Between the quests hud and the bag_slot mod...

![hud_bug](http://i.imgur.com/kelVdAI.png)

**Comment by gravgun** [comment]
I'm aware of this and said yesterday on IRC that I'll fix it soon.

**Comment by Ombridride** [comment]
No problem, i seen this error ingame yesterday.
So i created an issue about this hud error because I don't want to forget it ! :)

**Comment by farfadet46** [comment]
hum, i have the same issue but you have closed it :)

you can see the last picture wen you can see the bag is on place of the quest.

https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/195

**Comment by gravgun** [comment]
@farfadet46 The issue you faced with the Quests GUI isn't related to the `quests` code, it's impossible that `inventoy_icon`'s text and images end up here by normal scripting behaviour. This can't be anything else than a bug in MT Core.

**Comment by gravgun** [comment]
... Or is it? I need to code `mff_introspect` so I'll be able to observe the server-side state of both mods' GUI, since that never happened to me either locally or on the server.

**Comment by Ombridride** [comment]
@gravgun 
After tests, it happens when you check/uncheck "quests hud > configuration" AND have bags NOT EMPTY

more bags not empty you have, more frequent/easy will be the bug ;)

**Comment by Ombridride** [comment]
@gravgun do you planned to fix this issue, if it's not fixable, just close it please

**Comment by gravgun** [comment]
@Ombridride Nope, not fixable, the engine is once again to blame for this sh!t.

**Comment by Ombridride** [comment]
Ok, great job ! :)
