### ISSUE TITLE
Class node texture !

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#216]
Need to be done before the merge of this week-end !

Pour Mg : 

Il faut faire de ta priorité la texturisation des bloc de classes, je ne mergerais MFF qu'une fois ceux ci fait (je compte merger ce week end, ça serait bien car on prend trop de retard sur la branche là)

Tu me disais vouloir y faire avec un ancien mod que tu as en réserve, piedestal+outil dessu cliquable, sac pour adventurer, épée warrior, bow hunter, livre pour wizard, merci par avance ! :) (et l'idée est très bonne en passant)

**Comment by LeMagnesium** [comment]
Je suis assigné aux textures maintenant?
Tout ce que j'ai fait c'était les pedestals avec la petite entité flottante au dessus : 
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/6d63e415b1f77b0eca50aa6a8ff637b687cdb0bd

**Comment by Ombridride** [comment]
Le ticket a été fait avant que tu me communiques qu'@Ataron finirait la texturisation, n'hésite pas à lui assigner le ticket dans ce cas là :)

**Comment by LeMagnesium** [comment]
En fait, ni moi ni @Ataron n'étions partant pour faire des textures pour les pedestals, mais je me suis rappelé du système de coloration : 
![Class Switches](https://lut.im/zJMbjIKL/5zBPuXz2)

https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/e281845f457e8ec21b4199df51a45727abc8764a

**Comment by Ataron** [comment]
Si vous voulez je peux essayer de faire qq chose, j'ai les couleurs mais je n'ai pas a quoi ca doit ressembler alors je tenterais un truc.

**Comment by Ombridride** [comment]
Pas mal !

Les couleurs sont bien, cependant :
1) La couleur du hunter devrait celon moi être plus "verte".
2)  Pour les matières des piedestals, en couleur unique ça fait bizarre. Je verrais donc plus le hunter en "bois", l'adventurer en "laine", le warrior en "métal", et l'admin autant le laisser comme ça :)

**Comment by Ombridride** [comment]
Tested right now after the merge :
![pedestal_calsses_colors](http://i.imgur.com/LhqWxaH.png)

Parcontre les couleurs des classes, ça ne va pas pour les couleurs actuels :
- L'adventurer est rouge, il devrait etre marron
- Le warrior est bleu, mais pas assez foncé
- Le hunter est vert cacky, pas assez vert flashy/clair

**Comment by LeMagnesium** [comment]
![Better now?](https://lut.im/sHUvkuUV/S1l4eMOn)

Meilleurs?
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/2cd80bccf1bd8ed2bc230a3093d682cef3e3237c

**Comment by Ombridride** [comment]
ça a l'air beaucoup mieux, a voir en jeu :)

**Comment by ObaniGemini** [comment]
Besoin de reorganiser le spawn

**Comment by Ombridride** [comment]
Tu as des idées par rapport à cela ?

**Comment by ObaniGemini** [comment]
Pas vraiment. Mais le spawn actuel pose un gros problème (trop petit)

**Comment by farfadet46** [comment]
le premier problème qui vient a l'esprit c'est surtout que les nouveau qui utilisent le warp arrive au pied de la tour et doivent remonter pour pouvoir choisir une zone. et rien ne leur dit qu'il faut remonter dans la tour. du coup ils tournent en rond sur l'ile du spawn sans savoir trop quoi faire vue qu'il est zoné.

**Comment by ObaniGemini** [comment]
Autre problème avec les textures : les résolutions ne sont pas les mêmes. et perso tant qu'à faire du 2d je préfère qu'il soit pixel art

**Comment by farfadet46** [comment]
+1 pixel art :)

**Comment by Ombridride** [comment]
Encore une fois @ObaniGemini, si tu peux améliorer va y n'hésite pas ;)

**Comment by ObaniGemini** [comment]
Je m'y atèle quand je peux

**Comment by Ombridride** [comment]
Closed the issue.

Textures are great like this, if @ObaniGemini wants to create new textures or tweak the actual textures, post it to a new issue.
