### ISSUE TITLE
Add some mobs

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#232]
#### Need to test it in local before all ! 
(the 3D model and the model animation are the most importants thing to check)

##### Into Water
Water mobs from here : https://forum.minetest.net/viewtopic.php?f=9&t=12652&hilit=mobs

##### Surface Agressive monsters
If well reallised, from here : https://forum.minetest.net/viewtopic.php?f=9&t=13049&
view=unread#p187330

##### Ent
I will also add the "Ent" mob of this issue : https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/134

Need to choose the mobs to add (and of course tweak)

**Comment by farfadet46** [comment]
i think mob in ocean is a good idea. but we need a tuba to hunt it ?

**Comment by Ombridride** [comment]
No, we won't add a tuba/scaphandre, the actual air/bubbles supply system is great :p

Maybe we will increase the air supply of the hunter... :)

**Comment by LeMagnesium** [comment]
I personally think we already have enough monsters at the surface of our world, yet, oceans and rivers lack ennemies or peaceful mobs.

**Comment by Ombridride** [comment]
We will implement world bosses, like the Ent, it will spawn only on a node, on an island.

For oceans, the shark will be a good thing.

**Comment by farfadet46** [comment]
+1 for shark and maybe somes peacefull fish ?

**Comment by LeMagnesium** [comment]
I think we should also add turtles, jellyfish, or fish. Their are all peaceful.

**Comment by ObaniGemini** [comment]
Shall we all have a PC like Cyberpangolin has ?

**Comment by Ombridride** [comment]
@ObaniGemini 
Off topic comment, the mobs mod __isn't__ a "ressources eater" mod

**Comment by LeMagnesium** [comment]
Mobs use memory. They don't have any memory leak, but an important amount of them loaded for a client can be a real ressources eater. We just need to be sure that we won't have 10 species of mobs, or 40 of them at the same spot on the map.

**Comment by Ombridride** [comment]
with the actual 20+ mobs => https://github.com/MinetestForFun/minetest-minetestforfun-server/wiki/Making-the-subgame-more-lightweight

Add 2/3 mbos aren't a problem, 1.5 MB is taken by 1 mob

Our ethic is more "one to five mobs on the screen at the same time, no more"

**Comment by paly2** [comment]
I think, if there are more mobs, it would be good to reduce the spawn probability of all mobs, to maintain the average quantity of mobs

**Comment by Ombridride** [comment]
After every new monster add, we decrease the spawn of other monsters if they spawn on the same node.

So don't worry, we always adjust the spawn rate.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/1ef54505344025af4e020223e268e77220b70c33

**Comment by Ombridride** [comment]
No need to add jellyfish, just add the shark.

**Comment by ObaniGemini** [comment]
Would this be useful ?
https://github.com/blert2112/mobs_sky
It adds bats, butterflies and birds

**Comment by Ombridride** [comment]
#### For the water mobs

There are now done, the big sharks and medium sharks has been implemented and balanced.

#### For the bosses

We need to try the "pumpkin king/boom from Not-So-Simple-Mobs" and the "Ent from lott"

This two mobs need to become aggressive bosses

**Comment by ObaniGemini** [comment]
Sharks have a too light texture IMO. I would make it darker personally, but that's just a proposal ;)

**Comment by ObaniGemini** [comment]
Here is what I did for sharks : 
- https://imgrush.com/gm6utIj77Dzw (shark_second)
- https://imgrush.com/xT5XmbuEpTRl (shark_third)
- http://www.pasteall.org/61446 (init.lua)

- init.lua : added a color set and reorganized sharks coloration
 - shark_second : made it be square, it had some stranged effects on borders. Tried to fix a bug when near of the monsters at textures junction, but it seems unsolvable (core-related ?)
- shark_third : modified eye texture (bigger), modified scars texture, but it's not so much better (If you want to try to make a new one...), and modified lines (they now correctly fit together). I also modified grey nuances with gamma.

P.S: sharks are now much more dark :p

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/6310c475aac41b616ef505a1c8aedefb416c49af
I think I still need to improve the spawn block but so far it works.

**Comment by Ombridride** [comment]
Needs screenshots of the pumpkin king boss and the small pumpkins, and i need to balance it a lot... and think about drops of bosses...

I think the Obani new textures for the sharks are great, the texture junction is a know bug, we can't fix it. For the color, if it's darker, it's better. you textures seems to be good

**Comment by ObaniGemini** [comment]
Maybe should we add pumpkins and make them be a drop for pumpkin bosses ?

**Comment by LeMagnesium** [comment]
@Ombridride It's your role to balance bosses, and the drops are fine for me; I would maybe add a coin or nyans but I leave that decision to you.

![](https://lut.im/aS1x7Ci0C7/p1UwvIGD.png)

**Comment by Ombridride** [comment]
The Pumpking is near over, just need a last thing : when a pumpboom explode, they do damage to another NPC (pumpboom/pumpking) and knockback them...

So, we need to tweak this pumpboom explosion to NOT inflict damages to other NPC (pumpboom/pumpking especially)

**Comment by LeMagnesium** [comment]
We cannot modify that individually, pumpbooms use mobs' explosion method. We would need to modify the API.

**Comment by Ombridride** [comment]
if it's a small API tweak, just comment it well and it will be ok

**Comment by Ombridride** [comment]
The pumpboom "explode" feature isn't right ! When a pumpboom explode, the dropped items are removed ! so the PumpKing drops can be removed if a pumpboom is near the boss...

**Comment by LeMagnesium** [comment]
> Also, the PumpKing spawn isn't limited to 1...

There is no way of doing this accurately. We cannot keep track of every entity spawned that is a pumpking. The way to regulate this mob is to set its life span as the interval between two calls to the spawn ABM.
I'm going to check the pumpboom explosions but I will need to tweak the API.

**Comment by Ombridride** [comment]
The way to regulate this mob is to set its life span as the interval between two calls to the spawn ABM. => this is already the case, 6 Pumpking when i checked it today.

**Comment by LeMagnesium** [comment]
This is because the engine is bugged : when you unload a chunck with ABM-triggering nodes in it, whenever you will go back and reload those chuncks, the engine will apply all missed ABMs.
That's why there is no **accurate** way of regulating a mob specie.

**Comment by crabman77** [comment]
limit spawn number https://github.com/MinetestForFun/server-minetestforfun/commit/f7f73c20042940fecc98898a100837de00db9799

**Comment by Ombridride** [comment]
The lastest mob this issue need to add is the Ent. Need to work on this soon :)

I think we will do a "Pumpkin" like room, but with forest and minions like treemonsters

**Comment by Ombridride** [comment]
Work over on PumpBoom/PumpKing and Sharks, i closed this issue.

If you want follow our work about the Ent, follow this issue https://github.com/MinetestForFun/server-minetestforfun/issues/134
