### ISSUE TITLE
About dyes...

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#245]
According to the crafting guide, you can make 2 white dye with grey dye and white dye
2 grey dye should be obtained by mixing dark grey dye and white dye.
the dark grey dye should be obtained from coal

What you really have:
2 grey dye from a mix of black and white
2 light grey from grey and white
black dye frome coal.

--> there is something to do. Or correct the craft guide, or correct the crafts.
If the guide is corrected, please add white + light grey = 2 white.

If it's due to a general colour update (a mod?), every other color should be checked.

**Comment by LeMagnesium** [comment]
So, if I get it correctly (because you didn't say explicitely the problem), .. no, repeat, please, because I don't get what the problem is. `dye` has never been modified by us, it's directly provided from `minetest game`.

**Comment by LeMagnesium** [comment]
Is that what you want?
![ScrShot1](https://lut.im/RXavAhXj/JoZyDTqJ)

![ScrShot2](https://lut.im/FFSXfhx6/QjQbHfdQ)

**Comment by Cyberpangolin** [comment]
The problem is that dye crafting does NOT match with the guide. Hope it's better explained like this.
I m sorry, I wont have time to talk about it until wednesday I think... I'm even not sure I will have time to log in on MFF up to that date...

**Comment by LeMagnesium** [comment]
The dye crafting **matches** the guide, every time. The guide is built according to craft recipes, it's impossible that it doesn't work. Have you checked the "Alternate" recipes?

**Comment by Cyberpangolin** [comment]
As we discussed tonight, you have a very simple example:
The guide says crafting a coal alone gives you dark grey, BUT if you try it gives you black. and, I just found that black is in the crafting guide too.
Maybe a simple way could be to make a script that checks every double-craft recipe, where there are conflicts, and keep only interesting ones. I'don't know at all if it exists, but for sure it would make us avoid any double-craft.

**Comment by LeMagnesium** [comment]
I fixed the coal issue, but after investigating a bit, I discovered that `unified_dyes` was creating a gigantic amount of conflicts within dyes' recipes. Yet, I cannot fiddle in `unifieddyes` automated registration system, it's impossible, and would break a lot of other mods. The best solution would be to remove this mod, but it would disable seacoral, stained_glass and coloredwood.

**Comment by LeMagnesium** [comment]
I fixed all the recipes.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f16dc55e92872c9950939b259f5248596fead13a

**Comment by Cyberpangolin** [comment]
I repoen it: I own already 23 different dyes (there might be more but I don't have them for now), but looking for dye does only give 11 results.

In my chest:
![capture du 2016-01-07 13 49 52](https://cloud.githubusercontent.com/assets/12512762/12170936/c8ae264e-b545-11e5-9c30-ff2ce3b0f807.png)

in the guide:
![capture du 2016-01-07 13 49 42](https://cloud.githubusercontent.com/assets/12512762/12170941/d55421a0-b545-11e5-90dd-95a83b836b23.png)

All different colors come from the flower you can see in the chest mixed together + sometimes black dye coming from coal.

**Comment by Ombridride** [comment]
If you caft a colormachine and look at the dyes you can craft with it, i think you will see easily the missing craft recipes you mention

But you're right, if some dyes are missing in the inventory craft guide, we need to add them :)
