### ISSUE TITLE
Invisible parts on "cow_brown" texture (new cow texture)

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#25]
Looking for someone can convert it here : https://forum.minetest.net/viewtopic.php?f=4&t=10623&p=171005#p171005

**Comment by davedevils** [comment]
why not change model ?

**Comment by Ombridride** [comment]
We want to change the model of the cow mob because the actual model of the cow mob is very ugly... this model in 128x128 px is really detailed and beautiful, but the work on it to be usable with the .x model is dfficult...

**Comment by crabman77** [comment]
I have extracted this calc of blender,it's very hard to texturing. 
http://www.hostingpics.net/viewer.php?id=643848cowcalctextures.png

**Comment by Ombridride** [comment]
The goal is to take parts of the "cow_brown" texture and paste it on the actual cow texture file, and we need to keep the same model file (the actual cow model file from mobs redo mod) for compatibility issues...
So first, we need to know where are the parts (leggs/chest/head/etc...) of the actual cow model, and next we need to paste parts of the "cow_brown" textures to a new 128x128px file

**Comment by Ombridride** [comment]
Nobody wants brown cows with a better resolution ? :D

**Comment by farfadet46** [comment]
si quelqu'un peut me faire des screen in-game de la vache avec cette texture pour voir ou sont les couleurs.

![8cowcalctextures](https://cloud.githubusercontent.com/assets/11613522/9292869/720f85f0-440f-11e5-8bdc-6909b9af79da.png)

sinon je le ferais avec blender dans la semaine.

**Comment by crabman77** [comment]
voila les screens de l' arcowciel :)
![cow_textures](https://cloud.githubusercontent.com/assets/7189389/9293033/480a97c6-441a-11e5-8d61-792ef7cfe41c.png)

**Comment by Ombridride** [comment]
Content que cette texture qui traîne depuis des lustres avance ! Merci pour votre travail :)

(Rappel, il ne faut pas reprendre le modèle blender, juste la texture et l'adapter au modèle actuel de notre mod mobs)

**Comment by farfadet46** [comment]
cool merci crabman ;)

je vais tenter ce soir de refaire cette texture mais du coup ne vaut il mieux pas changer le modèle + la texture ? car le modèle de la vache est vraiment bizarre ^^

**Comment by crabman77** [comment]
si tu sais faire des modeles blender pourquoi pas, du moment quelle fini pas à 5 pattes :)

**Comment by farfadet46** [comment]
haha :p j'ai déjà fait pas mal de modèles, mais le problème c'est plus au niveau de l'animation sous blender.

**Comment by farfadet46** [comment]
![mobs_cow](https://cloud.githubusercontent.com/assets/11613522/9295411/640a3c08-446d-11e5-9822-d55877938b58.png)
il faudra la retravailler un chouilla mais c'est un bon début :)

**Comment by crabman77** [comment]
vraiment bien, juste un petit trou sur le dos.
![cow_textures2](https://cloud.githubusercontent.com/assets/7189389/9295449/c552e824-446e-11e5-9518-3921930c602c.png)

**Comment by Ombridride** [comment]
Je me répète : 

Le but ce n'est pas du tout de refaire un autre modèle (ce qui va alourdir le mod "mobs")

Le but c'est simplement de __redimentionner__ et __repositionner__ les textures de la _cow brown_ pour un modèle en carré 1:1, pour réutiliser par la suite le modèle déja animé et modelé de mobs, que nous utilisons actuellement

Est-ce bien compris ? A vous voir parler j'en ai pas l'impression, dite le moi si je m'exprime mal ! :p

**Comment by LeMagnesium** [comment]
En fait ils ont juste réussi à créer une planche anatomique du modèle, le but n'était pas de créer une nouvelle texture mais d'obtenir un template sur lequel démarrer (ce dont on manquait au début).

**Comment by farfadet46** [comment]
@Ombridride zut de zut. j'ai pas enregistré le modele...
il me faudra faire quelques test si tu veut que je conçoive un nouveau modele de vache car je n'ai jamais esayé d'exporter une animation en fichier ".x" mais pourquoi pas si le modele plais.

@crabman77 peut tu essayer cette texture ? j'ai comblé les trous :p !
[texturevache](https://cloud.githubusercontent.com/assets/11613522/9303502/b3c72974-44de-11e5-9e63-e13d0c8b4b05.png)

**Comment by Ombridride** [comment]
@farfadet46 
Il ne nous faut pas du .x mais du .b3d :)
une fois que le modèle "marron" sera fait, il serait bien d'en faire 2/3 autres avec des couleurs différentes (toute maron, blanche et taché noir, etc...)

**Comment by farfadet46** [comment]
vous avez les script d'import/export pour ce format sous blender ?

**Comment by crabman77** [comment]
Encore une fuite.

![screenshot_20150817_155300](https://cloud.githubusercontent.com/assets/7189389/9306420/83b0d752-44f8-11e5-8e48-cc64a2012396.png)

**Comment by farfadet46** [comment]
pffff tu le cherche XD sinon les sabot te plaisent ?

**Comment by crabman77** [comment]
quels sabots? j'ai regardé mais pas vu de changement.
![screenshot_20150817_155145](https://cloud.githubusercontent.com/assets/7189389/9307088/7ce9335c-44fc-11e5-9ac4-f7777ce00eda.png)

**Comment by farfadet46** [comment]
ok j'ai du zappé de remonter le sabot alors.
Enfin j'aime pas de toute façons :(

**Comment by farfadet46** [comment]
sinon j'ai finalement réussi a créer une animation "simple" sous blender.
![1](https://cloud.githubusercontent.com/assets/11613522/9307707/5a21f45e-4500-11e5-936b-3398eecd6dcd.gif)

**Comment by Ombridride** [comment]
Bravo ! :D plus qu'a animer la vavache :p

**Comment by farfadet46** [comment]
j pose ça la pour mémo :D
http://wiki.minetest.com/wiki/Using_Blender

**Comment by farfadet46** [comment]
![vache](https://cloud.githubusercontent.com/assets/11613522/9310117/0b7e12e8-450e-11e5-882b-bdad1f065908.PNG)

Qu'en pensez vous ? pas assez low-poly non ?

**Comment by farfadet46** [comment]
BON ! :D ma vache existe (en fichier .x) mais elle existe !
![screenshot_20150817_184251](https://cloud.githubusercontent.com/assets/11613522/9310419/e6633f04-450f-11e5-9a16-0d3316effb24.png)

**Comment by Ombridride** [comment]
Euh, le design n'est plus dutout cohérent avec ce que l'on charchait initialement :/

Là c'est tout rond, comme le nouveau homedecor_modpack (que je trouve de plus en plus moche...)

Il nous faut une vache "carré", qui rentre dans l'esprit du "bloc", celle de MC est par exemple bien réussite, mais le but n'est pas _forcément_ de copier ce bord là...

**Comment by farfadet46** [comment]
okidac :) je refait tout ça

**Comment by farfadet46** [comment]
voila la texture sans transparence.
![640a3c08-446d-11e5-9822-d55877938b58](https://cloud.githubusercontent.com/assets/11613522/9410705/f585dcc0-4821-11e5-82c8-1691ac6c3aa6.png)

**Comment by Ombridride** [comment]
Cette texture s'applique donc au modèle actuel ?

Pour le nouveau modèle, prend ton temps, rien ne presse :)

(même si tu as les compétences pour nous faire une superbe vache à lait :p)

**Comment by farfadet46** [comment]
oui la texture est pour le modèle actuel :)

**Comment by farfadet46** [comment]
ça avance.
je poste ça ici pour laisser une trace :)
![000](https://cloud.githubusercontent.com/assets/11613522/9418138/26047ebc-4852-11e5-9b2a-73fe68969b19.gif)
![capture](https://cloud.githubusercontent.com/assets/11613522/9418139/2606c49c-4852-11e5-957d-7aacc186ee99.PNG)

**Comment by farfadet46** [comment]
je poste ça là pour pouvoir le retrouver plus tard.

-- model animation
	animation = {
		speed_normal = 15,		speed_run = 15,
		stand_start = 0,		stand_end = 30,
		walk_start = 35,		walk_end = 65,
		run_start = 105,		run_end = 135,
		punch_start = 70,		punch_end = 100,
	},

**Comment by farfadet46** [comment]
sinon j'ai fait le big mob :/
![screenshot_20150821_230646](https://cloud.githubusercontent.com/assets/11613522/9419127/5a0cbc86-4859-11e5-9c6c-89ea707db89d.png)

**Comment by Ataron** [comment]
Ah oui niveau proportions o_o

**Comment by LeMagnesium** [comment]
C'est rien ça, on le fixe avec le `visual_size`.

**Comment by farfadet46** [comment]
bon j'ai pratiquement terminée la vachette. reste plus qu'a fignoler les animations.

**Comment by ObaniGemini** [comment]
C'est magnifique !

**Comment by farfadet46** [comment]
merci :)

**Comment by LeMagnesium** [comment]
Le plugin blender pour exporter en B3D n'est pas officiel, mais on peut le trouver en ligne (je ne sais plus où).

**Comment by farfadet46** [comment]
c'est bon j'ai trouvé (difficilement je trouvais tout le temps un plugin obsolète incompatible)

**Comment by Ombridride** [comment]
Génial, hâte de mettre une texture sur un modèle et une animation si bien réalisé :)

**Comment by farfadet46** [comment]
Et avec ceci madame ?
![screenshot_20150824_221716](https://cloud.githubusercontent.com/assets/11613522/9473802/1efc4cc2-4b5d-11e5-9dca-54e68408e6f8.png)
![vachette2](https://cloud.githubusercontent.com/assets/11613522/9473805/232d51c4-4b5d-11e5-8214-c87f4dca97a2.png)

**Comment by ObaniGemini** [comment]
La texture est un peu trop flashy, je pense qu'il faudrait l'assombrir un peu et même peut-être la flouter légèrement.

**Comment by crabman77** [comment]
La flouter? on peut la passer en 16x16 aussi. Elle est géniale, ont ne voit pas les pixel ressortir.
Par contre elle a l'air mince et la tête ressemble a un cochon.

**Comment by Ombridride** [comment]
Il ne faut surtout pas la flouter.

En effet elle fait penser à un cochon :/

Je trouve les couleurs trop "cartooné" (unicolore, sans noise, trop coloré et clair)

**Comment by farfadet46** [comment]
pour ce qui est des texture il faudra demander a des personnes + qualifiée que moi, c'est forcé.
pour ce qui est de "mince" = "large" ?

j'ai pas envoyé la bonne en fait je lui avais ajouté un léger noise :
![vachette](https://cloud.githubusercontent.com/assets/11613522/9476041/cd64c0e8-4b6a-11e5-85b9-077ecfdd4cba.png)

**Comment by crabman77** [comment]
bah la tête est aussi grosse que le corp. il faudrait qu'elle(la vache pas la tête) soit plus massive.

**Comment by Ombridride** [comment]
C'est plus le moment de revoir le modèle...

En plus, la prise de vue de @farfadet46 accentue la tête du à la perpective par rapport au corp.

Pour la texture c'est mieux, cependant le gris clair et le rose est toujours autant clair par rappport au marron foncé, ça ne va pas,e but c'est de réduire l'écart de clarté entre les 3 couelurs, pas de réduire la clarté des 3 couleurs :)

**Comment by ObaniGemini** [comment]
@crabman77 : Tu as déjà vu une vache ? ^^

**Comment by farfadet46** [comment]
en effet, c'est pas trop le moment de me demander de revoir complétement le modèle XD

**Comment by farfadet46** [comment]
![1280px-taureau_tarine](https://cloud.githubusercontent.com/assets/11613522/9478292/261827a0-4b77-11e5-9cc1-6861a50fa695.JPG)
![vache111](https://cloud.githubusercontent.com/assets/11613522/9478309/3c83506e-4b77-11e5-9069-454cb7cb5c90.PNG)
c'est assez ressemblant je trouve :p

**Comment by crabman77** [comment]
ouai mais c'est un taureau ça :)
enfaite la tête est trop haute, grosse et pas de coup.
![99737_vf5lafx52ueu8wolb3ck14qwbhgq8t_vl_h161221_l](https://cloud.githubusercontent.com/assets/7189389/9478411/10bfeb58-4b78-11e5-8027-00d60b200017.jpg)

**Comment by farfadet46** [comment]
c'est du cube qu'on veut :p

**Comment by Ombridride** [comment]
pas de cou pitié...

Ne touchons plus le modèle svp

**Comment by ObaniGemini** [comment]
Le modèle est très bien comme ça, même si il n'est pas réaliste, c'est pas le but. Maintenant il faut s'atteler au texturing

**Comment by Ombridride** [comment]
j'ai testé rapidement ceci, dite moi ce que vous en pensez, je n'en suis moi même pas totalement satisfait...

![test_texture_cow_darker](http://i.imgur.com/3ZOmbjb.png)

(désolé pour le contour blanc, outil windaube du taff)

**Comment by farfadet46** [comment]
tu utilise quel outil ?
prend paint.net si tu peut perso je ne peut plus m'en passer :)

**Comment by Ombridride** [comment]
Je ne parles pas de l'outil de retouche d'image, je n'utilise que Gimp et inkscape pour cela.

Je parle de l'outil d'upload de fichier du taff qui met un contour blanc autour de la zone d'image prise ;)

Meric d'avoir enlevé le contour blanc, j'aurais pu le faire, mais ça aurait pas été automatisé donc chiant... :p

**Comment by farfadet46** [comment]
![screenshot_20150826_202056](https://cloud.githubusercontent.com/assets/11613522/9502197/238b0f70-4c30-11e5-8ab5-37d56176f683.png)

**Comment by Ombridride** [comment]
That's better, need other textures now :)

**Comment by farfadet46** [comment]
ok but if we use the b3d format the name of the texture is writed in. we need make so many model for all different textures ?

**Comment by Ombridride** [comment]
non, un modele et on applique la texture dessu grace a notre api de mobs

**Comment by farfadet46** [comment]
voici l'archive de la vachette 1 couleur a tester...
https://up1.ca/#GF-lfV6s5QquitovUTQXvg

**Comment by Ombridride** [comment]
Je me l'assigne, je le ferais ce soir ou demain, je me suis pris du temps pour bosser sur les mobs.

Donc, tu pourra bientot voir ta vâche en jeu :)

**Comment by crabman77** [comment]
le model est ajouté https://github.com/MinetestForFun/server-minetestforfun/commit/bbbd2927d2c3f4f9617803797f588531e3c4b6d1

**Comment by farfadet46** [comment]
il a été validé ?

et sinon il faudra aussi refaire l’icône d'inventaire :
server-minetestforfun/mods/mobs/textures/mobs_cow_inv.png

**Comment by Ombridride** [comment]
le modèle est validé, pour l'icone d'inventaire, c'est pas prioritaire, et il faut faire un ticket séparé pour cela.

Cette issue est fermé.

**Comment by crabman77** [comment]
texture inventaire faite https://github.com/MinetestForFun/server-minetestforfun/commit/df1fcfb6253a916ec2cdaebaff19725b2aa4bccb
