### ISSUE TITLE
Item disparaît de l'armure et de l'inventaire

### ISSUE THREAD

**Issue by fabienwang** [MinetestForFun/server-minetestforfun#253]
If by mistake we put a second item on the armor formspec. ex : chest
the newer putted item will be erased for ever, normally, this item is just putted again in your inventory.

Bug wich needs to be upstream ( https://github.com/stujones11/minetest-3d_armor/issues/36 )

**Comment by fabienwang** [comment]
J'ai ajouté un label Upstream,
quand l'erreur provient du mod d'origine, où l'on rapporte également le bug à l'auteur du mod, et on doit alors suivre l'évolution de celui-ci pour inclure la correction s'il y a… :)

**Comment by LeMagnesium** [comment]
Pas mal comme label. Enfin bref, je vais fixer ça.
On a pas mal de bugs à remonter sur le repo upstream.. On s'en chargera.

**Comment by Ombridride** [comment]
As tu vérifié le graveyard par curiosité ? c'est peut être un cas particulier...

**Comment by LeMagnesium** [comment]
Je viens de comprendre le problème, ça vient de l'engine, et de la gestion de la quantité maximum d'items autorisés.

**Comment by Ombridride** [comment]
On peut faire un "drop" de l'item si quelqu'un essai d'entre mettre deux pièces d'armures avec le nom "chestplate/leggings/boots/helmet/etc..." sur lui pour fixer cela

**Comment by LeMagnesium** [comment]
Non, ce que voulait dire @fabienwang visiblement c'est ceci :
 - Prend une stack de 5 dirt
 - Met une dirt dans une case vide de l'inventaire armor
 - Essaye mettre dans la même case le reste de la dirt
 - Le reste de la dirt disparaît

On peut facilement contourner en interdisant tout ce qui n'est pas armor/shield, il vaut juste espérer que ça n'engendrera pas d'autres variations du bug.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f5e8bc08b7a749c6ddab4a814ec3059ddf5faabe

Comme ça, plus moyen de faire disparaître autre chose. On ne pourra pas non plus faire disparaître les items des armures puisqu'elles on un `stack_max = 1`.

**Comment by fabienwang** [comment]
Yop.

Le problème était ce qui a été décrit à savoir:

1) mettre une armure sur soi genre une en bois
2) avant qu'elle expire, mettre un chest en mese dans l'armure
3) observez, le chest en mese a simplement disparu de l'armure et de l'inventaire.

Je n'ai pas retesté pour confirmer que c'est résolu, n'ayant pas d'armure sous la main.

**Comment by LeMagnesium** [comment]
1) J'ai mis une armure en bois
2) Avant qu'elle n'expire, un beau chestplate en or neuf dans une case vide : 
![Chestplate](https://lut.im/3JXWxjcz/3nOTNPCK)

3) Après destruction du reste de l'armure :
![Chestplate2](https://lut.im/wllEHLlg/cb4OdiVK)

C'est toujours là... Donc je ne sais pas ce qui s'est passé. Si tu pouvais faire des screens à chaque étape ça serait bien.

**Comment by LeMagnesium** [comment]
Ni @fabienwang ni moi n'arrivons à reproduire le bug. Il semble fixé.

**Comment by LeMagnesium** [comment]
Je viens de réussir à reproduire le problème, voici la démarche précise :
 - mettez une pièce A d'armure dans une case a de l'inventaire.
 - poser une pièce B d'armure dans une case b de l'inventaire.
 - saisissez la pièce B et cliquez sur la pièce A dans la case a, vous récupérez la pièce A.
 - Restez sans poser la pièce A, elle disparaît au bout de quelques secondes.

**Comment by Ombridride** [comment]
I think we need to translate this issue in english and send it to minetest-core / 3d_armor :)

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/0b2f6d8453cb55a547c70a947accfe8afd8965fb

**Comment by Ombridride** [comment]
WTF ? It works, really ?!

**Comment by Ombridride** [comment]
Add @stujones11 because he surely wants this fix.

**Comment by crabman77** [comment]
C'est corrigé pour l'inventaire de l'armure à l'inventaire de l'armure, mais il y a encore de l'inventaire de l'armure à l'inventaire simple.

Un truc étrange, j'ai 2 items identiques dans l'inventaire simple, si je fait un échange avec un des 2 items, le 2eme item disparait.

**Comment by LeMagnesium** [comment]
C'est ce que je dis : le fait de faire un raffraichissement de l'inventaire armure enlève l'item qui est en "drag". C'est un bug de l'engine.

**Comment by crabman77** [comment]
on prend l'item, on échange, le nouveau se retrouve à la place de l'ancien mais entre temps pclasses a cru que c'était vide et le re-set vide, du coup il disparaît.
puis il update aussi l'inventaire en même temps alors que l'item est entrain d'être déplacé.

**Comment by LeMagnesium** [comment]
En effet, pclasses ne détecte rien. Ma solution serait de ne lancer le vacuum qu'à certains moments.

**Comment by crabman77** [comment]
Ce doit être fixé et optimisé en prime. https://github.com/MinetestForFun/server-minetestforfun/commit/e44dd3e74b28aae4cb353f567e8ba7cd22e03699 https://github.com/MinetestForFun/server-minetestforfun/commit/a0f2f09e90a12ffae3e9f0653088f2ee9292827b
