### ISSUE TITLE
improve sound, convert stereo to mono to play  positional

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#256]
To play positionnal sounds, mono must be used.

http://dev.minetest.net/minetest.sound_play
>> "Only OGG files are supported. For positional playing of sounds, only single-channel (mono) files are supported. Otherwise OpenAL will play them non-positionally."

**subgame**
before 769,9ko after 548,2ko
- [X]  beds --  0ko --  0ko
- [X]  boats --  0ko --  0ko
- [X]  bucket --  0ko --  0ko
- [X]  creative --  0ko --  0ko
- [X]  default --  625,0ko --  435,7ko
- [X]  doors --  32,1ko --  18,6ko
- [X]  dye --  0ko --  0ko
- [X]  farming --  0ko --  0ko
- [X]  fire --  112,8ko --  93,9ko
- [X]  flowers --  0ko --  0ko
- [X]  screwdriver --  0ko --  0ko
- [X]  sethome --  0ko --  0ko
- [X]  stairs --  0ko --  0ko
- [X]  vessels --  0ko --  0ko
- [X]  wool --  0ko --  0ko
- [X]  xpanes --  0ko --  0ko

**mods**
before 4194,6ko  after  2832,1ko
- [X]  3d_armor --  0ko --  0ko
- [X]  3d_armor_classes --  0ko --  0ko
- [X]  action_timers --  0ko --  0ko
- [X]  areas --  0ko --  0ko
- [X]  arrow_signs --  0ko --  0ko
- [X]  automappercolors --  0ko --  0ko
- [X]  bedrock --  24,2ko --  17,0ko
- [X]  biome_lib --  0ko --  0ko
- [X]  bobblocks --  51,0ko --  40,7ko
- [X]  broomstick --  0ko --  0ko
- [X]  builtin_falling --  0ko --  0ko
- [X]  builtin_item --  8,7ko --  8,7ko
- [X]  carts --  0ko --  0ko
- [X]  chatplus --  0ko --  0ko
- [X]  chesttools --  0ko --  0ko
- [X]  christmas_craft --  69,6ko --  50,9ko
- [X]  coloredwood --  0ko --  0ko
- [X]  colormachine --  0ko --  0ko
- [X]  colouredstonebricks --  0ko --  0ko
- [X]  columnia --  0ko --  0ko
- [X]  connected_chests --  0ko --  0ko
- [X]  darkage --  0ko --  0ko
- [X]  death_messages --  400,8ko --  144,9ko
- [X]  dropondie --  0ko --  0ko
- [X]  eventobjects --  0ko --  0ko
- [X]  factions --  0ko --  0ko
- [X]  fail --  65,4ko --  25,7ko
- [X]  fences --  0ko --  0ko
- [X]  food --  0ko --  0ko
- [X]  framedglass --  0ko --  0ko
- [X]  gauges --  0ko --  0ko
- [X]  glow --  0ko --  0ko
- [X]  hbarmor --  0ko --  0ko
- [X]  hbhunger --  61ko --  9,5ko
- [X]  homedecor_modpack --  259ko --  199ko
- [X]  hudbars --  0ko --  0ko
- [X]  interact --  0ko --  0ko
- [X]  inventorycheck --  0ko --  0ko
- [X]  inventory_icon --  0ko --  0ko
- [X]  invtweak --  10,4ko --  5,2ko
- [X]  irc --  0ko --  0ko
- [X]  irc_commands --  0ko --  0ko
- [X]  item_drop --  32,4ko --  21,8ko
- [X]  jukebox --  1,9mo --  757ko
- [X]  jumping --  0ko --  0ko
- [X]  lantern --  0ko --  0ko
- [X]  lavatemple --  5,1ko --  4,6ko
- [X]  locked_sign --  0ko --  0ko
- [X]  mana --  0ko --  0ko
- [X]  mapfix --  0ko --  0ko
- [X]  maptools --  0ko --  0ko
- [X]  markers --  0ko --  0ko
- [X]  maze --  0ko --  0ko
- [X]  mesecons --  455,5ko --  233,5ko
- [X]  metatools --  0ko --  0ko
- [X]  _misc --  0ko --  0ko
- [X]  mobs --  1,2 Mo --  833,5 ko
- [X]  money --  0ko --  0ko
- [X]  moreblocks --  0ko --  0ko
- [X]  more_chests --  0ko --  0ko
- [X]  moreores --  0ko --  0ko
- [X]  moretrees --  0ko --  0ko
- [X]  multitest --  5,2ko --  4ko
- [X]  name_restrictions --  0ko --  0ko
- [X]  names_per_ip --  0ko --  0ko
- [X]  nether --  271,8ko --  164,6ko
- [X]  news --  0ko --  0ko
- [X]  notice --  0ko --  0ko
- [X]  paintings --  0ko --  0ko
- [X]  pclasses --  0ko --  0ko
- [X]  peace_areas --  0ko --  0ko
- [X]  pipeworks --  0ko --  0ko
- [X]  plantlife_modpack --  0ko --  0ko
- [X]  player_inactive --  0ko --  0ko
- [X]  quartz --  0ko --  0ko
- [X]  quests --  0ko --  0ko
- [X]  random_messages --  0ko --  0ko
- [X]  returnmirror --  59,2ko --  24,6ko
- [X]  riesenpilz --  21,9ko --  21,9ko
- [X]  rofl --  0ko --  0ko
- [X]  runes --  0ko --  0ko
- [X]  sea --  0ko --  0ko
- [X]  shutdown --  48,9ko --  33ko
- [X]  snowdrift --  0ko --  0ko
- [X]  solarmana --  0ko --  0ko
- [X]  soundset --  0ko --  0ko
- [X]  spawn --  0ko --  0ko
- [X]  sponge --  0ko --  0ko
- [X]  sprint --  0ko --  0ko
- [X]  stained_glass --  0ko --  0ko
- [X]  throwing --  76,3ko --  35,6ko
- [X]  track_players --  0ko --  0ko
- [X]  treasurer --  0ko --  0ko
- [X]  trm_pyramids --  0ko --  0ko
- [X]  tsm_pyramids --  120ko --  64,3ko
- [X]  unifieddyes --  0ko --  0ko
- [X]  unified_inventory --  196ko --  122,4ko
- [X]  u_skins --  0ko --  0ko
- [X]  vector_extras --  0ko --  0ko
- [X]  warps --  74,1ko --  31,6ko
- [X]  watershed --  0ko --  0ko
- [X]  whoison --  0ko --  0ko
- [X]  worldedge --  0ko --  0ko
- [X]  WorldEdit --  0ko --  0ko
- [X]  xban2 --  0ko --  0ko

**Comment by Cyberpangolin** [comment]
If I remember well, all mobs sounds I have done are already in mono. Anyway, I note it to make sure every new mob sound I make is in mono.

**Comment by crabman77** [comment]
mod mobs done 1,2mo to 833,5 ko. https://github.com/MinetestForFun/server-minetestforfun/commit/167a0fe2e324119ae328e6886c72b3576938f60f
wolf and zombie They were in 2 channels.

**Comment by crabman77** [comment]
Fixed subgame https://github.com/MinetestForFun/server-minetestforfun/commit/a069481169225a5e44a509420898d60ae480c187  and https://github.com/MinetestForFun/server-minetestforfun/commit/9ba20f49a615968a2223700f8ff5000f4647693b

**Comment by crabman77** [comment]
Fixed mods https://github.com/MinetestForFun/server-minetestforfun/commit/f31916674a4c7013f9fcbf1589d850b6592279d3 and https://github.com/MinetestForFun/server-minetestforfun/commit/5856d4d6f33d44c60299d563910e677f1a0313b2

**Comment by ObaniGemini** [comment]
Does it also lights the medias to charge???

**Comment by fabienwang** [comment]
Yes @ObaniGemini , change from stereo to mono reduces a bit the filesize, which inescapably reduces bandwidth & time needed for clients to load these sounds.

**Comment by gravgun** [comment]
On a side note @fabienwang @ObaniGemini converting to mono doesn't only reduce filesize, it reduce the music's size in RAM since only 1 channel is stored instead of 2.
