### ISSUE TITLE
Unknown tree node

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#257]
I was travelling in mountain when I found this . It is a tree. The trunk is normal, I verified it (default:tree), but *the leaves are unknown nodes*.
![screenshot_20150831_005602](https://cloud.githubusercontent.com/assets/11649956/9575445/2e33e9e4-4fd0-11e5-8e4f-10f80bd3ecb0.png)

**Comment by LeMagnesium** [comment]
@Ombridride: I thought you got my commit which re-added snow but without the mapgen.
Until the next merge I will add aliases

**Comment by LeMagnesium** [comment]
eb470a2e3bc6ae57ae0274eff0a5c7ccfe10e194 (before snow removal)
![Before](https://lut.im/sRvNrfqD/UInKI3dI)

0f258b989baae40a0d484f508db181a5258d5362 (after second commit, adding back snow, disabling mapgen)
![After](https://lut.im/rRSxkvHl/DlrYkYji)

It's a merge error.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/aa9647ff4ede1239f82b4f87e2a64d903d5549bd

Somehow it was disabled.

**Comment by Ombridride** [comment]
Yes, that was idiot, i will merge the game again as soon as possible for fix this error.

**Comment by Ombridride** [comment]
Done, it works.
