### ISSUE TITLE
Ice texture

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#258]
Need to re-add our 32px Ice texture and not the default one !

This is at least the 10th times this error is done.......

Bad ice texture here (16px) :
![bad_ice](http://i.imgur.com/qDv1LT6.png)

(Surely a @LeMagnesium mistake... :()

**Comment by LeMagnesium** [comment]
You took the screenshot on the server when snow mod and its variation of default_ice.png were removed.
Now it's back. And copied to MFFGame. (https://github.com/MinetestForFun/server-minetestforfun/commit/ea5b55a8b1032f8c9feb5c9cbf8678d4f82c702b)

![Ice](https://lut.im/r7HcHEZg/DT2twWm8)
