### ISSUE TITLE
Update warps mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#260]
Fix this crash
https://forum.minetest.net/viewtopic.php?f=9&t=12005&view=unread#p184445

Nobody has do this on the server but need to fix it anyway...

**Comment by LeMagnesium** [comment]
I already did that a week ago. We had the same crash.
https://github.com/MinetestForFun/server-minetestforfun/commit/2aab854a4f23b8a9ec511a3029c76505eb7b6044

**Comment by LeMagnesium** [comment]
(As I said, already fixed locally)
