### ISSUE TITLE
Update mobs redo

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#261]
Don't touch anything other than the 4 lastest commits !
(Since Commits on Aug 19, 2015 included)

(PS : je me poserais normalement samedi après midi pour l'ajout des boss/requins/etc)

**Comment by crabman77** [comment]
already updated https://github.com/MinetestForFun/server-minetestforfun/commit/167a0fe2e324119ae328e6886c72b3576938f60f
