### ISSUE TITLE
Add the 32px textures for remaining armors

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#262]
Add the 32px textures for remaining armors from summerfields modpack, don't forget do resized it properly !

Also for the HG server

**Comment by fabienwang** [comment]
Pushed in f4194f14baeeb25c656b3e674f18134639a6500c
If it's okay for you, i'll push it to HG server too.

**Comment by Ombridride** [comment]
See my comment on your PR => https://github.com/MinetestForFun/server-minetestforfun/commit/f4194f14baeeb25c656b3e674f18134639a6500c

**Comment by Ombridride** [comment]
I will merge this night, can you over this issue before please ?
