### ISSUE TITLE
Completely remove the [jumping] mod and create aliases

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#263]
Completely remove the [jumping] mod and create aliases

**Comment by gravgun** [comment]
Sad to see it go :(
afa234e229d1a652505ba71b4d45fc294e387edb

**Comment by Ombridride** [comment]
Maybe we will reintroduce it someday... BUT, this mod needs to be debugged first.

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/server-minetestforfun/issues/401
