### ISSUE TITLE
Translate death message in english

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#265]
Because of the recent english new players, we need to traduct our death messages in english.

Death message example :
*player is dead. / player est mort.*
*At first, english sentence. / deuxièmement, phrase française.*

**Comment by LeMagnesium** [comment]
Would it not be easier to just go full english and forget about the french part?

**Comment by ObaniGemini** [comment]
NO, the main part of our players is still french and some of them do not understand english.

**Comment by LeMagnesium** [comment]
Do you realize how much of a waste it is to have to concatenate/format those strings in both french and english? Anyway... I'm going to do that while I improve the way the mod sends messages.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/4e99399cdbef2e187d991c25c1c4d38d2d4b325d

**Comment by Ombridride** [comment]
Perfect, we will from now adopt a "EN translation / FR translation" format, that's better for international understanding. ;)

**Comment by ObaniGemini** [comment]
Just a little question : how do we choose language ? With the quizz ?

**Comment by Ombridride** [comment]
You don't choose language.

**Comment by Ombridride** [comment]
Small comment :
I think the sentence is too long and complicated, whacked/c'est prit une raclée isn't as easy as killed/tué

**Comment by LeMagnesium** [comment]
Well, the sentences wouldn't that long if they were only translated in one language. (there, I said it...)
If you find it too long feel free to modify it, it was the only sentence I could think of and we need more of them.

**Comment by ObaniGemini** [comment]
Will improve messages for monsters (if I can)

**Comment by Ombridride** [comment]
Of course you can @ObaniGemini ;)
