### ISSUE TITLE
Visual issue with the position of armor items

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#266]
as you can see, if i set my armor shield on bottom, it's go visualy in front of the player
![002](https://cloud.githubusercontent.com/assets/11613522/9699948/ac2ef2e0-53f3-11e5-96b0-8c9bb5b51a29.PNG)

and now if i place it on top the shied goes behind the player... 
![001](https://cloud.githubusercontent.com/assets/11613522/9699949/b538cf0a-53f3-11e5-806e-ccd649fa5ea2.PNG)

Need more investigations, or not :)

**Comment by Ombridride** [comment]
That's strange, need to investigate

**Comment by LeMagnesium** [comment]
This is not strange, but this is quite bad. Armor constructs the preview image by superimposing every piece's preview picture on the other ones. We just need to tell it to put the shield last.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/ea7c8f20dcaf1fafd0e024cfb14ad0ea5611acad

If @stujones11 is interested by this fix, he should feel free to apply it on his repository.
