### ISSUE TITLE
new idea about column blueprint

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#267]
i think we need add this column 
we can made it by wood planks
![004](https://cloud.githubusercontent.com/assets/11613522/9699978/4fc21f36-53f4-11e5-8844-5b0ad64d4408.PNG)

but not by trunk
![003](https://cloud.githubusercontent.com/assets/11613522/9699965/04f84304-53f4-11e5-89b5-025d4c8370dc.PNG)

i think it's just a missing craft recipe no ?

**Comment by LeMagnesium** [comment]
Why would you do that with trunks, or trunks AND wood?

**Comment by farfadet46** [comment]
only because :p
no in fact i think it's more realistik in trunk.

when i see all the wood planks color (never used) i think we can get more and more derivation of cool nodes.

**Comment by Ombridride** [comment]
we can add the column textures and crafter with default tree trunk (or group trunk) if you want, but we will not tweak an already good craft recipe ;)

**Comment by ObaniGemini** [comment]
I think the idea is just to add a column blueprint kind that is missing, not to modify the craft recipe (but to add it)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/5aaa915196ec97773f3a39b721ba45d7ec2857fd

There, you have it.
![Tree Column](https://lut.im/QvB3LVGX/lV72nVIk)
