### ISSUE TITLE
the sponge can replace somes nodes

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#268]
if i make a mistake and clic on the node behind the pipe, the sponge replace the pipe

![1](https://cloud.githubusercontent.com/assets/11613522/9700049/7cb41524-53f6-11e5-867a-602ee7ff4852.png)
![2](https://cloud.githubusercontent.com/assets/11613522/9700050/7cb80db4-53f6-11e5-83fa-e984244957a0.png)
![3](https://cloud.githubusercontent.com/assets/11613522/9700051/7cbc75c0-53f6-11e5-8b99-6490b6c9f990.png)

i havent try other node ( hihi i dont want to lose other stuff :p )

**Comment by Ombridride** [comment]
Ok, that's indeed a bug !

Need to try wiht other nodes to confirm it and understand it better ;)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/bd72179e0e66ed421e31dbd66072b1d0f39d8bb8

Sponge is coded to handle by itself its nodes' placement. I moved the `on_place` callback to an `after_place_node` callback and cleaned the code.

**Comment by ObaniGemini** [comment]
I've another bug like this. With glass doors : we can place a node on the up of a glass door but when we close the door it disappears. Try by yourself :)

**Comment by LeMagnesium** [comment]
What node did you achieve to put on the top part exactly? It's no surprise that it will be removed when moving the door, but I bet you guessed it's not supposed to be there in the first place, didn't you?
