### ISSUE TITLE
player's inventory grid broken in the  single locked chest

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#269]
I've tried many times, and palige told me the same.
It only happens with small locked chests, should be easy to fix. an example will be MUCH better than any description

![capture du 2015-09-07 22 37 35](https://cloud.githubusercontent.com/assets/12512762/9722663/6d030fe2-55b1-11e5-877c-0ebe5f40f08f.png)

as you see, the player's inventory is drawn twice.

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/9091d61132020782d1a3d8eafc6118bd763a982c
