### ISSUE TITLE
Update [throwing] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#273]
https://forum.minetest.net/viewtopic.php?f=11&t=11437&view=unread#p190803

Be carful, keep our settings !

Add spears only for hunters (special tool for hunter melee weapon and can we throwed ! :))

After th update of the mod, I will need maybe to re-unified the damage values

**Comment by ObaniGemini** [comment]
Maybe should we remove "Harmful arrows" ?

**Comment by crabman77** [comment]
trowing updated https://github.com/MinetestForFun/server-minetestforfun/commit/303a724cda93e880388df8458c6eed1b3fb77f2f

now, must be add spears only  for hunter

**Comment by Ombridride** [comment]
Great, I need to test it in a local server and look if the damages/range is overpowered or not

**Comment by Ombridride** [comment]
Need some tweaks because many bugs wit hthe spears for the moment, and the throwing spear animation isn't very good :/
@crabman77 i think i had read you work on it ?

**Comment by Ombridride** [comment]
@crabman77 
Can you speak us about this update, is it done ?
