### ISSUE TITLE
Pour le parcours de b91b

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#275]
Voici les coordonnées de la zone contournant le parcours de b91b : (983, 13.5, -971) à (1, 13.5, -955)
Le spawn pour cette zone désiré : (992, 15, -965)

Il faut donc créer un mod qui va faire deux chose :
- [x] Enregistrer la zone de contour du parcours de b91b et la définir comme spécial
- [x] si un joueur meurt dans cette zone spécial, il est téléporté à un seul endroit, le spawn de la zone

(Définition de la zone, récupération de la position du joueur une fois meurt, si celui ci meurt dans la zone, le téléporter au spawn de la zone)

**Comment by crabman77** [comment]
en modifiant le mod area  c'est ok? https://github.com/crabman77/minetest-minetestforfun-server/commit/879b04a7bc880db7f94956c946e4128ddfa75dc9

**Comment by ObaniGemini** [comment]
Pratique pour un éventuel MT-Arena, n'est-il pas ? :p

**Comment by Ombridride** [comment]
Wow, superbe idée crabman, si c'est fonctionnel t'es le roi du pétrole ! :)

**Comment by crabman77** [comment]
voila c'est envoyé  https://github.com/MinetestForFun/server-minetestforfun/commit/8b2a291531247f34cd85463f617f63843cd37202
Les messages sont surement incorrect niveau anglais, à vérifier.

**Comment by ObaniGemini** [comment]
Peut-on fermer le ticket ?

**Comment by Ombridride** [comment]
Non, l'area special n'est pas en place, il faut que je la fasse

**Comment by Ombridride** [comment]
The spawn for the area is set, thank you for your work @crabman77
