### ISSUE TITLE
Unknown node: "snow:shrub_covered"

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#277]
Found at (3981, 29, 3421)

**Comment by LeMagnesium** [comment]
Related to #277

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/aa9647ff4ede1239f82b4f87e2a64d903d5549bd

**Comment by Ombridride** [comment]
lol, that was just this =)...

**Comment by Ombridride** [comment]
Done, it works.
