### ISSUE TITLE
New mob cochonou

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#279]
![cochonou](https://cloud.githubusercontent.com/assets/11613522/9991953/dcf45640-606e-11e5-88f8-5dbbff3d384f.PNG)

are you ok for this shape ?

**Comment by fabienwang** [comment]
it looks like the cow :laughing:

**Comment by Ombridride** [comment]
I think it needs smaller leggs, and more bigger chest

**Comment by farfadet46** [comment]
ok for the legs.
@fabienwang normal, it's the same base :)

**Comment by Ombridride** [comment]
mh... j'ai quelques idées :
1) Coller le rectangle des oreilles à la tête quand le cochon bouge pas, tu pourra les faire ce "balancer" comme sur ton modèle actuel quand le cochon bougera
2) la queue ne va pas, autant mettre un petit carré/rectangle, actuellement c'est trop "rond"
3) rendre des pattes un peu plus large
4) peut etre enfoncer la tete un peu dans le corps, le cochon pour moi c'est un animal avec la face pas écrasé mais faisant partie intégrante de son corps, il a pas a proprement parlé de cou, si tu vois ce que je veux dire... :)

**Comment by farfadet46** [comment]
ok merci pour ces détails, je tenterais de revoir tout ça demain soir
j'ai aussi pensé le faire + maigre qu'en pense tu ?

**Comment by farfadet46** [comment]
Vous en pensez quoi du coup ?
il me faut un max de retours svp.

![cochon5](https://cloud.githubusercontent.com/assets/11613522/10026493/627d5034-6162-11e5-88ec-ab42472c2636.PNG)

**Comment by Ataron** [comment]
Je prefere la tete plus enfoncée comme ca :p.

**Comment by farfadet46** [comment]
j'ai en effet descendu la tête et grossi les pieds pour les rendre tous les 4 identiques.
la queue en biseau ne choque personne ?
normalement un cochon c'est assez fin vue de dessus je dois le faire "maigrir" ou pas ?

**Comment by crabman77** [comment]
La queue en biseau ne choque pas, c'est plutôt ou elle est placée qui choque :)
Pour le reste ça me va.

**Comment by Ataron** [comment]
C'est vrai que je trouve qu'elle est un peu haute :p

**Comment by Ombridride** [comment]
Je préfère personnellement rester dans le cubique et une queue en "rectangle" aulieu de biseau.

Pour la carrure et la tête enfoncée, je trouve que c'est bien mieux !

Je ne pense pas qu'il faille le faire "maigrir"

Peux tu faire un essai avec des oreilles rectangulaire qui "pendent" aulieu du trapèze qui "vole" actuel s'il te plait ?

Quoiqu'il en soit, c'est déjà du superbe travail !

**Comment by ObaniGemini** [comment]
J'apprécie beaucoup :)

**Comment by farfadet46** [comment]
Comme ceci ?
![cochon6](https://cloud.githubusercontent.com/assets/11613522/10052285/679bcf4a-6226-11e5-8b97-b6fd995b2532.PNG)
après n'oubliez pas que niveau texture de machin vivant je suis vraiment une bille :/

**Comment by Ombridride** [comment]
ça me semble parfait comme ça, bravo :)

Si d'autres ont des suggestions c'est maintenant ou qu'ils ce taisent a jamais :p

Si personne d'autre ne voit de point d'amélioration, tu vas pouvoir faire l'animation

**Comment by farfadet46** [comment]
ok je reste ouvert pour les améliorations jusqu’à demain, l'animation est quasi prête.
une idée d'attaque d'ailleurs ?

**Comment by Ombridride** [comment]
un coup de "tête" peut être, le cochon ça mord, à part ca aucune idée ^^

**Comment by ObaniGemini** [comment]
Peut-être changer la texture? (pour le regard, ou la tête rouge par exemple)

**Comment by farfadet46** [comment]
c'est possible de modifier la texture lors d'une animation ? aucune idée mais du coup pourquoi pas, si ça peut m’éviter de faire des textures bidons c'est mieux pour tout le monde :)

**Comment by Ombridride** [comment]
Oui on peut le faire, si tu trouve cela nécessaire, via du code :)

**Comment by farfadet46** [comment]
j'ai refait l'assignation des faces pour faciliter l'UV mapping (plusieurs coloris)
![cochonv2](https://cloud.githubusercontent.com/assets/11613522/10280538/26fd71b8-6b6e-11e5-9d6d-9274adaf3763.PNG)
![cochon4_uv_ok](https://cloud.githubusercontent.com/assets/11613522/10280550/3105bf3a-6b6e-11e5-913d-406e867cc0eb.jpg)
![cochon4_uv](https://cloud.githubusercontent.com/assets/11613522/10280537/26fbe9d8-6b6e-11e5-8f3c-1f400960ac34.png)

je réfléchis toujours sur les animations... :(

**Comment by Ombridride** [comment]
Great work on the texturization but, they aren't enought cubic.

The general view is great. (maybe need a noise for the brown weird bottom of the pig)

**Comment by farfadet46** [comment]
bon j'ai repris mon boulot :factory: 
j'ai essayé de le refaire du mieux que je puisse :)
![cochon1](https://cloud.githubusercontent.com/assets/11613522/12007359/067cd5cc-ac01-11e5-9284-5d93e82c5049.PNG)

**Comment by Ombridride** [comment]
je viens de découvrir ça et je me dis que c'est une super idée : 
!(queue)[http://shoopsoldierstuff.blogspot.fr/2012/01/minecraft-papercraft-pig.html]

La queue du cochon est faite en texture 2D sur son corp (cul), en gros ça simplifie le modèle et la queue en tire bouchon ce jou à la texture 2D appliqué, je trouve le principe bon, et en plus ça simplifiera l'animation et la texturisation

**Comment by farfadet46** [comment]
Carrément, j'y avais pas pensé !
on oublis donc l’idée de queue.
par contre des idée du coté de l'animation serais la bienvenue.

**Comment by gravgun** [comment]
> on oublis donc l’idée de queue.

Faut que je garde cette citation pour la sortir hors contexte :wink:

**Comment by Ombridride** [comment]
Ahah @gravgun, oui ça peut être ambigüe sortie hors contexte :p

Pour l'animation, je n'ai pas bien d'idée, je pense que ça ressemblera beaucoup à l'animation de la vache. 
Le cochon étant plus petit, à une vitesse égal à celle de la vache j'en déduis que ses jambes devront donc bouger plus vite, à part ça, aucune idée...

**Comment by farfadet46** [comment]
Bon je vous donne libre pour les textures car je suis vraiment une bille XD
![screenshot_20151228_173351](https://cloud.githubusercontent.com/assets/11613522/12021727/62562450-ad89-11e5-94fc-ff3a31d2dcc4.png)
![screenshot_20151228_173403](https://cloud.githubusercontent.com/assets/11613522/12021728/625c6c2a-ad89-11e5-8325-ade82eeebe59.png)
il ne me reste plus qu'a l'animer ;)

**Comment by farfadet46** [comment]
![cochonou_texture](https://cloud.githubusercontent.com/assets/11613522/12042039/5010254a-ae77-11e5-80dd-d980b9afc541.png)

voici la texture si quelqu'un veut bien me la faire :/

**Comment by farfadet46** [comment]
![cochonou](https://cloud.githubusercontent.com/assets/11613522/12052978/c9a086fa-af14-11e5-8c5d-2f0d7be6dd2b.gif)

**Comment by farfadet46** [comment]
Bon normalement ce fichier est correct,
https://up1.ca/#V-Ow5NSsLJqJXKupDKrCTA
avec la texture suivante (surement a refaire)
![mobs_pumba](https://cloud.githubusercontent.com/assets/11613522/12054428/de6c7616-af23-11e5-8e2a-5934bf86c0fc.png)

il faudra aussi modifier le .ini avec ces valeurs (animation un peut plus longue):

>	animation = {
		speed_normal = 15,
		stand_start = 25,
		stand_end = 55,
		walk_start = 60,
		walk_end = 100,
		punch_start = 60,
		punch_end = 100,
	},

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/f9413db441481a750b3e182a88e4990b6aa4e289
J'ai utilisé la chèvre comme modèle. Je copierai tout ça sur Creative quand on aura le son.

**Comment by Ombridride** [comment]
L'idée n'était pas d'ajouter encore un mob supplémentaire mais de remplacer le pumba actuel qui a un modèle moche et déjà les attribues du pig en ce qui concernes ses stats/sons/drops

**Comment by LeMagnesium** [comment]
> (Bon, ducoup là tu dois aussi revert ton commit sur l'ajout pig qui n'a pas lieu d'être :/)

Ou alors j'enlève le pumba et je copie ses propriétés dans pig.lua dans un nouveau commit.

**Comment by Ombridride** [comment]
Ce qui te fait bien plus de travail que de juste renommer 3 mots et d'écraser un modèle (+1 texture), et qui potentiellement vont te faire faire des erreurs...
Fais comme tu le sens, c'est toi qui choisis la méthode si tu souhaites utiliser, contrôle simplement que tout sois bon en local s'il te plait

**Comment by Ombridride** [comment]
Everything is OK, merged to the Classic server. Great work everybody !
