### ISSUE TITLE
Double chests improvements

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#282]
2 tiny bugs about the double chests:

1) a locked double chest shows to anyone its content - the single locked chest doesn't. This should be unified in a way or the other.

2) if you watch carefully the corner, you will see the chest's lock. in the corner; an example is much better than words: 
![capture du 2015-09-22 22 52 30](https://cloud.githubusercontent.com/assets/12512762/10031378/2d4d00f6-617d-11e5-98c4-0e19167b0e07.png)

Probably the whole light brown should not be in the corner.

**Comment by LeMagnesium** [comment]
1) is fixable. 2) Is probably not, it's caused by bumpmapping.

**Comment by Ombridride** [comment]
The second point you tell us isn't fixable without the model of the chest :/

But, we can fix the first point.

**Comment by LeMagnesium** [comment]
Well, @Ombridride, as far as I know, the second point cannot be fixed even if we have the model. The bumpmapping feature adds bumps to the textures (by an optical illusion). This particular glitch comes from bumpmapping. To fix that we would have to fix the way the bumpmapping shader works (and that's also present with any other block).
I will fix the first problem though.

**Comment by fabienwang** [comment]
@LeMagnesium Maybe if you just increase the brown border on all corners of the texture it would be okay?

**Comment by LeMagnesium** [comment]
@fabienwang No it won't, it will still use parts of side textures to fill the gaps created by the bump effect.

**Comment by Ombridride** [comment]
@LeMagnesium, @farfadet46 has fixed this problem in our older Cow model/texture...

**Comment by LeMagnesium** [comment]
Yes but this is not a model, this is a node. It's different, and relies on different mechanisms.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/14d12abd37fe45c95d150b77ddd6e9bfc3c7a738 https://github.com/MinetestForFun/server-minetestforfun-creative/commit/b5624a17dc79ae8569cefeca372155c6c091d6c0
