### ISSUE TITLE
Traduction d'un article forum

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#283]
Il faut traduire cet article en anglais, vous n'êtes pas obligé de le faire en entier seul, mais poster des petit bout traduit pourrait m'aider infiniement, merci par avance :)

https://forum.minetest.net/viewtopic.php?f=20&t=13244

**Comment by ObaniGemini** [comment]
Hello,
 
This text is here to make understandable to everyone why did the collaboration between MinetestForFun team and 4aiman stopped, and why it is impossible to work with 4aiman in general.

Let's begin...
For you can understand this message and continue to read it : 4aiman is self-centered, stubborn and immature. Let's add that he has no respect on others work, and that he took the developers team (more than 10 people and myself) for slaves/dumb people.

So here is the complete and detailed story that 4aiman would have loved to keep secret forever.

[u]AUTHORIZATION TO USE THE SUBGAME[/u]

On the 21 August 2015, The team of MinetestForFun developers agreed on the fact that we had unused resources on our dedicated server, and that it would be good to help a developer working alone to help him at the enhancement/bugfix/finalization of his subgame.
I (MinetestForFun / Darcidride) decided to propose our help to 4aiman (main modder of Magichet), by opening a public server to help him finalize his subgame. That began from a good intention and was proposed freely, without any compensation ( his server was never launched publicly on any other server, and 4aiman also confessed us that he never tried his code on a public server and that he would like to).

After some discussions from the 21 to the 22, 4aiman accepts to give us the right to use his subgame (under restrictives licenses), and we reach an agreement, everything is right for now.

The server opens a week after (the time to make the administration of the server ressources and to prepare the Github repository.


P.S : je ferais peut-être la suite plus tard, voici la première partie. Correction s'il vous plait :)

**Comment by LeMagnesium** [comment]
Je suis aussi sur la traduction, j'essaye de faire quelque chose de complet. J'éditerai ce message une fois fini. On pourra comparer avec ta version @ObaniGemini .

**Comment by Ombridride** [comment]
Je suppose que le mieux et le plus pratique serait d'éditer la version d'obani pour l'améliorer/corriger et continuer la traduction sur son post ;)

**Comment by LeMagnesium** [comment]
Je ferai un merge, on verra bien. (on peut aussi se trouver un pad interactif)

**Comment by Ombridride** [comment]
Allé c'est partie pour un pad : https://semestriel.framapad.org/p/traduction_article_forum

**Comment by Ombridride** [comment]
Translation over.
