### ISSUE TITLE
Warp Crystal (South East)

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#284]
Originaly posted by farfadet

"the warp Crystal protect all the area and we can't expand our area :(
like at the cyberpangolin's factory"

**Comment by younishd** [comment]
Yes pls.

**Comment by Ombridride** [comment]
Owww !!

Im sorry, indeed it's my fault ! 

Yesterday, after seeing some usebug with the Warp crystals end teleport point.
I decide to protect the 4 Warps crystal "teleport areas" and i had apparently forget a "marker" at the North West of the map. So, when i put my markers at the South East of the map and owned the area i don't owned only the South East area BUT the entire area between the South East and the North West warp crystal (at least 90% of the map)

It's fixed.
