### ISSUE TITLE
Area of areas

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#285]
A nooby player (or not ;) ) with the name of "Darcidride" now owns around 80% of the whole MFF map, while he wanted to protect a tp_area.

-> please remove it
-> it could be good to add a question like "do you REALLY want to own 20x20 km?" for huge areas.

**Comment by fabienwang** [comment]
Duplicate of #284 
Which should be solved?!

**Comment by Ombridride** [comment]
Yes it's a duplicated issue, i will re-check the area, just to be sure it's fixed...

**Comment by Cyberpangolin** [comment]
A player was complaining one hour ago. #284 is supposed to be solved for 17 hours. 
Please close this if irrelevant.

**Comment by Cyberpangolin** [comment]
irrelevant. The player was near a warp zone
--closed.

Sorry.
