### ISSUE TITLE
Formspec of the locked big chest doesn't exist

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#286]
Create a new **locked** big chest and try to acces its content: error. The formspec is unavailable.

Repeated error message:
2015-09-27 09:49:06: ERROR[Main]: InventoryMenu: The selected inventory location "nodemeta:3826,3,3507" doesn't exist

Existing locked big chest work of course.

**Comment by LeMagnesium** [comment]
I observed that but the inventory is always created after a few seconds. It comes from the fact that the inventory is created on-rightclick to prevent the access for users who are not owners. I may have an idea about how to fix that, but I'm not 100% sure it will work.

**Comment by LeMagnesium** [comment]
From what we saw, this is a client problem, caused by lag or bad response from the client. It cannot be fixed, and it won't probably happen to anybody else.
