### ISSUE TITLE
the hitbox for the fence gate is wrong

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#288]
The left side is ok but the right side has a width = 0 ?

![screenshot_20150928_173619](https://cloud.githubusercontent.com/assets/11613522/10140448/d017c814-6607-11e5-8e05-d5267bda20a0.jpg)

**Comment by LeMagnesium** [comment]
You can't have two hitboxes, so it's either one part only, or the whole area.
I will put the whole area, fences will be easier to close then.

**Comment by LeMagnesium** [comment]
![screenshot_20150928_184450](https://cloud.githubusercontent.com/assets/6785985/10142158/3c828ee0-6611-11e5-9f60-89cc22172b9a.png)
