### ISSUE TITLE
Female PNJ sounds

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#289]
Les sons des PNJ femelles sont bien trop fort, Il faut les baisser en décibel avec le sons de base !

A appliquer aussi sur le serveur creative !

**Comment by crabman77** [comment]
reduit sur MFF https://github.com/MinetestForFun/server-minetestforfun/commit/2c47322feb0e007876dc481bdfb1a0cb112c814e

**Comment by Ombridride** [comment]
Thank you for this commit, the reduced sounds of the female NPC seems to be right.

For the attack --> shoot_attack, this tweak needs to be apply to all of our mobs.

We also need to merges these updates to the mff-creative repository

**Comment by crabman77** [comment]
sound shoot_attack is for mobs with arrows (mese and dungeonmaster) 
attack -> https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L947
shoot_attack -> https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L984

**Comment by Ombridride** [comment]
Ok, thank you for the accuracy and informations :)

**Comment by crabman77** [comment]
reduit sur creative https://github.com/MinetestForFun/server-minetestforfun-creative/commit/fa3c2512d96f30ed420858136760604f18e74adc
