### ISSUE TITLE
Jukebox sounds don't loop

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#292]
This is a problem that always existed, but there was not any issue talking about it.

Well, it's very easy to understand it. When you play a song, it stops at its end. As all songs are loops, it only play one time the loop.

Two solutions :
- Drop the CD and stop jukebox notes at the end of the song

OR

- Make it loop as it should

**Comment by gravgun** [comment]
Dropping the CD could mean loosing it since dropped items despawn. Make it loop as intended.

**Comment by LeMagnesium** [comment]
It was intented to loop though, but I can make it.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/39110eaa979e8a3059d00780734f32be2b4b6800
