### ISSUE TITLE
Need to check/investigate it

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#293]
#### Need to check/investigate it

- reworked builtin_item
https://forum.minetest.net/viewtopic.php?f=9&t=10271

- reworked drop_item
https://forum.minetest.net/viewtopic.php?f=9&t=10319&view=unread#p157430

This reworked mods will give us maybe possible ideas/fixs/improves, so... Need to check/investigate them :)

**Comment by LeMagnesium** [comment]
I don't think it's a good idea to modify our mods to fix a glitch we already fixed... Besides, our code is at the moment very different from the reworks..

**Comment by gravgun** [comment]
My `item_drop` version is a widely reworked one, supporting non-radius pickups range (capsule shape around the player), pickup animation as well as pickup/drop callbacks, which are required for `mff_quests`. Changing it would bring back a simpler yet unfit version.

**Comment by Ombridride** [comment]
Ok, we don't touch the actual *item_drop* mod.

it was just here for information and eventually investigate the good things bring with this reworked code.
