### ISSUE TITLE
Unified inventory update

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#294]
#### Unified inventory update and adapt our tweaks

https://forum.minetest.net/viewtopic.php?f=13&t=3933&p=193699#p193699

**Comment by crabman77** [comment]
updated https://github.com/MinetestForFun/server-minetestforfun/commit/13974157c26dede96cde6101f7e95ee2a367dbb1

**Comment by Ombridride** [comment]
Awesome, this merge was very difficult, happy to see you done it as fast as your shadow :)
