### ISSUE TITLE
[mesecon] Make water_turbine detect fluid group and not only water node

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#295]
Everything is in the title. If possible :
- [x] Apply it to server-minetestforfun => https://github.com/MinetestForFun/server-minetestforfun/commit/f34d5a6d2cf454e42080af04cb82df2b33fbea32
- [x] Apply it to server-minetestforfun-creative => https://github.com/MinetestForFun/server-minetestforfun-creative/commit/74e5e7a585eccf5de1cfe10add8ac85287cca6c0

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/f34d5a6d2cf454e42080af04cb82df2b33fbea32 https://github.com/MinetestForFun/server-minetestforfun-creative/commit/74e5e7a585eccf5de1cfe10add8ac85287cca6c0
