### ISSUE TITLE
[mobs] Add parameters for shark spawn

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#296]
- [ ] Spawn only over y = -50 (actually they can spawn in caves)
- [ ] Disable spawn in water_flowing [from crabman]

**Comment by Ombridride** [comment]
Good idea,  we  will do it as soon as possible

**Comment by Ombridride** [comment]
Done. 
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/shark.lua

Spawn under -25 because -50 is too deep.

**Comment by ObaniGemini** [comment]
You inverted wto values. Also I think min_height should be more -30 or -40 and max_height should be -3 or -5

**Comment by Ombridride** [comment]
oh, ok.

Fixed : https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/shark.lua
https://github.com/MinetestForFun/server-minetestforfun/commit/1e9595771b6e4b8ccce622b616ae8e966a5b283e
