### ISSUE TITLE
Shields wieldview problem

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#297]
#### Shields wieldview problem

The wieldview of all Shields is incorrect, it's 4x too big, and the 3d_armor model can't displayed it all.

Old bug(not fixed anymore ?), need to fix it ASAP...

APPLIED it to All servers which use 3d_armor ! (classic & HG)

**Comment by LeMagnesium** [comment]
We need a screenshot please to determine the precise origin of the problem, and resizing those textures proved to be a mess after a while.

**Comment by Ombridride** [comment]
![](http://i.imgur.com/2ql79vF.png)
![](http://i.imgur.com/Xzlo7SZ.png)
![](http://i.imgur.com/Xzlo7SZ.png)

**Comment by LeMagnesium** [comment]
Oh, then it's not preview, it's wield. And that was probably caused by the fact that we resired the shields. I will investigate on that.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/1c13721b34ee9218995dbdb0b6b2e6310cfe537b
Fixed the wield, now it's the preview wich is bugging. I think it's my fix about the textures piling that is messed up.
