### ISSUE TITLE
Spears

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#298]
Echoes91 apparently wants to divided the spears from his Throwing mod, this splited mod seems more interresting with the key controls, we need to check/investigate it...

https://forum.minetest.net/viewtopic.php?f=9&t=13367&view=unread#p194034

**Comment by LeMagnesium** [comment]
I don't know how much we modified the spears, but if we split the mod into two, that may be very difficult to update from Echoes91's version. @crabman77 is the person to ask for that. If he's okay with splitting then we only need to update throwing and install spears, and I will agree with his opinion.

**Comment by crabman77** [comment]
removed of throwing https://github.com/MinetestForFun/server-minetestforfun/commit/f198c25db235f3b9385d498e847d87300a1a3e1a
added spears mod https://github.com/MinetestForFun/server-minetestforfun/commit/8ce79c3dfcd1224d64332d71d521805f7119da8a and https://github.com/MinetestForFun/server-minetestforfun/commit/78c5f0cc09702a599fecf81b6b3da0d5881b7a9b
