### ISSUE TITLE
Maybe add this mod ?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#299]
https://forum.minetest.net/viewtopic.php?f=9&t=13366

A server that provides a server guide.
Maybe add it to the server (and maybe to the creative) ?

**Comment by Ombridride** [comment]
I see it, it's a huge work for fill it if we added it.. But why not :)

**Comment by ObaniGemini** [comment]
I can write into it :)

**Comment by LeMagnesium** [comment]
This would probably help many players getting the basics of areas, classes, and others.

**Comment by LeMagnesium** [comment]
Do we still want that mod?

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/9c29b0452e1e50eed2db4d9b5d2e0111579e526d
