### ISSUE TITLE
Why not add this mod ? 

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#300]
https://forum.minetest.net/viewtopic.php?f=9&t=12845
it's an hardcore server right ? :)

**Comment by ObaniGemini** [comment]
-.- No and I hope this is a joke. If you want to use Ben's mod, use them on a server that is only PvP, or to play in local.

**Comment by farfadet46** [comment]
yep it's a joke. i say that because you add more and more sytem to kill me on the server. more mobs, more mobs and more mobs :p

i think you want to add, if you don't move you lose your life too :)

**Comment by ObaniGemini** [comment]
I agree with what you told, but please do not create useless issues, talk about it on the IRC, we already talked about that to @Ombridride , tell him if it really annoy you.

**Comment by Ombridride** [comment]
Good joke :)

But recently we make easier the server ! ^^
