### ISSUE TITLE
Palm tree leaves don't fall

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#301]
If you cut down a palm tree from moretrees, its leaves don't fall. The area where I tried this was tree-less except for this palm tree. Another palm tree was insanely far away (~30 blocks) on the beach.

I tried several other trees and they all dropped their leaves quickly, including moretree's oak and sequoia. It seems the problem is only on the palm tree.

**Comment by Ataron** [comment]
I cut down some palm trees a while ago and their leaves felt but after a LONG time.

**Comment by ObaniGemini** [comment]
It's still a problem if we have to wait to much for leaves to fall, as it's nearly instant on most part of other trees.

**Comment by LeMagnesium** [comment]
Palm leaves fall from decay as all leaves, if it doesn't work then it's because another tree is too close. On local it works but I will test on creative and classic.

**Comment by mgl512** [comment]
I think it's a problem of design of the palm tree: its leaves need a very big leafdecay radius not to fall. Now that moretrees uses the default leaf decay ABM, a leaf doesn't specifically look around for a palm tree trunk anymore but for any node of the "tree" group in a radius of 10 blocks. With such a radius, a palm tree leaf far away from its palm tree trunk has many chances to catch another random tree node (including the underground ones that moretrees grows) to keep it alive. 

That means something like when you plant a palm tree sapling, you should not have another node of the tree group in a radius of nearly 20 blocks or its leaves (at least on the edge) won't fall when you cut it down. That makes the palm tree the most annoying tree. 

Commit 6de5e69 does'nt fix that. It only may make the palm tree sapling more rare

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/6de5e6991a556c59f1e1d7eb90dc82f8a4c9aa62

No it was just an exception.
