### ISSUE TITLE
Spears update

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#304]
#### New update

alpha1 -> alpha2 :
https://forum.minetest.net/viewtopic.php?f=11&t=13367&view=unread#p194034

alpha 2 -> alpha 3 : 
https://forum.minetest.net/viewtopic.php?f=11&t=13367&view=unread#p195044

**Comment by Ombridride** [comment]
@crabman77 can you do this update please ? 
https://gitlab.com/echoes91/spears/commits/master

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/332fe79f890fe00c714e5f026dac501ee4027305
