### ISSUE TITLE
Post the fishing mod of crabman on the forum

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#306]
#### Post the fishing mod of crabman on the forum

We need to work together to write the forum post of the fishing mod of crabman on the forum, it's clearly the best and stable with more features Minetest has never had.

**Comment by ObaniGemini** [comment]
https://semestriel.framapad.org/p/fishing-mod

- [ ] Text with explanations
- [ ] Screenshots
- [ ] download links
- [ ] Display code

**Comment by crabman77** [comment]
pad édité avec le descriptif et liens des screnshoot, il faut vérifier les fautes de traductions.

**Comment by Ombridride** [comment]
Great news, so we just need to check the translation and maybe display a small piece of the code and it's over :)

**Comment by Ombridride** [comment]
Posted in the forum, WIP mod : https://forum.minetest.net/viewtopic.php?f=9&t=13659

Request to be in released mod : https://forum.minetest.net/viewtopic.php?f=11&t=10418#p199912

I closed this issue, it's done :)
