### ISSUE TITLE
Looking for a volunteer

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#308]
#### Official Facebook Page

https://forum.minetest.net/viewtopic.php?f=3&t=13356&view=unread#p195349
We're looking for an Admin with time to keep up to date and clear the official facebook page :)

Just posted it here for peoples which didn't follow the forum.
If nobody want it, we will close the issue BUT, just ask a little comment here, even if it's No :)

For my point of view, it's maybe, but i haven't the time to manage this page...

**Comment by LeMagnesium** [comment]
I go with a "no" on this one.
(though it's astonishing that you ask for someone to be an admin for a facebook page and at the same time assume that nobody wants to be a moderator on servers that may need it, but that's offtopic)

**Comment by ObaniGemini** [comment]
For me, it's a NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO and 
###NO

In my point of vue, Facebook MUST disappear and we need to do that first. I can administrate a Diaspora account but Facebook will be a NO.
> That's my point of vue <

**Comment by Ombridride** [comment]
@LeMagnesium 
I agreed. in the other hand i think administrate a Facebook page required less time than moderate a server...

@ObaniGemini 
I strongly advice you to read the entire forum thread ;)

**Comment by ObaniGemini** [comment]
@Ombridride : No facebook at home

**Comment by Ombridride** [comment]
No volunteers here, closed the issue.

THank you anyway for the answers ! :)
