### ISSUE TITLE
Spears can't be put on pedestal

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#309]
Spears can't be put on pedestal

**Comment by LeMagnesium** [comment]
It's because [this](https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/spears/tools.lua#L15) is triggered with rightclick.

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/36e3c44430bd64ed5215da965b59e77e44e8ca32
