### ISSUE TITLE
admin "class" from pclasses bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#310]
La classe "admin" ne peut pas utiliser les armes elles partent directe en graveyard inventaire !

Pour les armures tout est bon on peut porter des armures warrior/hunter sans probleme et elles ne finissent pas dans le graveyard dès qu'aparaissent dans l'inventaire

**Comment by LeMagnesium** [comment]
Mais c'est normal, elle n'a jamais été implémentée pour être supérieure. Jusqu'à maintenant.
