### ISSUE TITLE
Update [farming] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#312]
https://forum.minetest.net/viewtopic.php?f=11&t=9019&start=100#p196320

Need to update it also on Creative server https://github.com/MinetestForFun/server-minetestforfun-creative/issues/46

**Comment by crabman77** [comment]
done https://github.com/MinetestForFun/server-minetestforfun/commit/2fb116685cef18d7d36c6617fb2c4691a16d4737 and https://github.com/MinetestForFun/server-minetestforfun/commit/1e49bd6d20578208ff9bf9365c486b9fd39df539 and https://github.com/MinetestForFun/server-minetestforfun/commit/80059b2477a84b56e8678ec305c806e89270d8d4

**Comment by Ombridride** [comment]
Perfect, thank you @crabman77 

You can close by yourself the issue ;)
