### ISSUE TITLE
New server-side default textures pack ?

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#316]
I'm thinking about a new server-side default textures for players ONLY FOR NOT ALREADY MODIFIED TEXTURES

The PIXELBOX textures pack was updated yesterday, and this texture pack is really beautiful for a 16px texture pack, what's your opinion ? 

If everybody agreed, we can push the selected textures to all of our servers.

~~https://forum.minetest.net/viewtopic.php?f=4&t=4990~~
EDIT 2016.02.29 : Use this version https://forum.minetest.net/viewtopic.php?f=4&t=14132 because it's a renewed version made by @kilbith and adapted to the latest Minetest version 

![pixelbox](http://i.imgur.com/dTP97yA.jpg)

**Comment by ObaniGemini** [comment]
Mods are designed to fit with default texture pack. Also, wouldn't it increase charging time at the launching of the server to chose another pack ?

But I agree it seems to be a sweet texture pack :)

**Comment by Ombridride** [comment]
@ObaniGemini 
You answer is again **off topic**, im not here to moderate the Github...
Mods are designed to fit with default texture pack => Just wrong and we tweaks many mods textures to improve the consistence of the textures.
will increase charging time => NO, we don't change 16px with a 128px texture, we changed a 16px with an another 16px texture.

Give your opinion is a great thing but **PLEASE**, do not post questions like this in the repository, PREFER the IRC to understand better the issue before you post an answer.

Thank you in advance.

**Comment by LeMagnesium** [comment]
@Ombridride even though I hate what you did and I would never delete a comment from an issue unless it's hypothetically harmfull for others, you get the point that he was **slightly** offtopic. But he agreed, and expressed that in his way.
I don't dislike that texture pack, even though it will break some nodes like those from pipeworks, morechests, connected_chests and mesecons for example, which uses copies of the default pack to adapt their systems to those default nodes. We have already modified textures in the past, as long as we see what is broken and need to be adapted/repaired, it will be fine. It's okay for me then.

**Comment by Cyberpangolin** [comment]
I'm afraid with such a texture pack: it may change the color balance, and good-looking buildings may look better or worse. So I prefer to keep the default texture pack on the server-side and let people install their own texture pack if they want.

**Comment by Ombridride** [comment]
We will only took some textures of this texturepack because they are really well done compared to the default 16px texturepack, im working on the list of texture i thing it will be great to add

**Comment by Ombridride** [comment]
After some thoughts, I closed this issue but it's a not very interesting.
