### ISSUE TITLE
Conflicting crafts: 9 sticks

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#317]
farming redo: 9 sticks ---> farming:treillis
custom moreblocks (I think) 9 sticks ---> default:wood

Maybe use a farming:bean_pole at the center bottom line for the craft of the treillis so that it uses its own items to craft more of its things without conflicting with other mods. It would be annoying to change the recipe of such a popular mod though.

**Comment by LeMagnesium** [comment]
I change a bit the recipe. We don't have many combinations left with sticks. I didn't use any item from farming though.

**Comment by LeMagnesium** [comment]
Are we okay with this? Can I close it?

**Comment by Ombridride** [comment]
Ok for me
