### ISSUE TITLE
More death_messages

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#319]
from here https://gitlab.com/00C/ayntest_game/blob/master/mods/chat_next/init.lua

**Comment by Ombridride** [comment]
Assigned to @LeMagnesium because he done earlier all work about the death_messages

**Comment by LeMagnesium** [comment]
I didn't do everything.
Anyways it's done.

**Comment by Ombridride** [comment]
Thank you :)
