### ISSUE TITLE
trunks:treeroot member of the "tree" group

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#320]
It's the annoying, hard to see 2D triangles that you sometimes find at a tree foot. They mimic roots. I think they are members of the generic "tree" group because they prevent leaves from falling when you cut down a tree. On a flat ground, they're too far away from the leaves to do that but, on the slopes of a tree-covered hill, they do. 

So if there is no purpose for them to be a member of the "group:tree", it should be removed I think.

**Comment by LeMagnesium** [comment]
I moved them to a `tree_root` group.
