### ISSUE TITLE
Tamed mobs problems

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#321]
suite aux dernières MAJ de mobs :

le npc prennent les diamants mais ne sont jamais tamed avec
les npc suivent pas dutout les objets qu'ils devraient suivrent, ils suivent le wheat uniquement alors que ça fait pas partir de npc(_female).lua

**Comment by crabman77** [comment]
Testé en local et sur le serveur, les NPC se tame et suivent le diam's.

**Comment by Ombridride** [comment]
Fixé depuis le dernier merge.
