### ISSUE TITLE
Armors out of [3d_armor] mod problem

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#323]
Armors out of [3d_armor] mob still have the preview problem :
![black_mithril](http://i.imgur.com/9uI9Fpp.png)

Need to fix it ! :)

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/0e2df1e5d5c05d6fb4e9f071a6f64a49c311eead
