### ISSUE TITLE
Spears problem

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#324]
The spears can be used/throw by warrior and adventurer, the spears can normally be used only by Hunters !

**Comment by LeMagnesium** [comment]
I can have none of the available spears as a warrior and an adventurer.
I can't reproduce this on my local server.

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/576d732088733da1e6fd8ed496e9c76e8c5cc7c0
