### ISSUE TITLE
Spear instantly taken when dropped

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#326]
Les spears ce ramassent instantannément après les avoir jeté, il faudrait ne pas pouvoir les ramsser avant 5 secondes par exemple

Actuellement : Lancé spear ---> touche adversaire = adversaire ramasse immédiatement
Voulu : Lancé spear ---> touche adversaire --- 5sec ---> adversaire ramasse la spear

PS : que ce soit adversaire ou sois meme c'est pareil, il faut que ce soit 5sec

**Comment by ObaniGemini** [comment]
5 seconds seems a bit too long to me, because the players who would launch the projectile would have to wait to retrieve it. What about 2/3 seconds ?

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/332fe79f890fe00c714e5f026dac501ee4027305

**Comment by Ombridride** [comment]
3sec was chosen finally.
