### ISSUE TITLE
A new mod for server rules

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#328]
Maybe shall we add this mod, it seems easier to understand.
https://forum.minetest.net/viewtopic.php?f=9&t=12441

![Newserverrules](https://forum.minetest.net/download/file.php?mode=view&id=3444&sid=63bf794d3a4206761b73e05ed062a8ad)

Also, if we add it here, we should add it to creative.

EDIT : Just saw that MinetestForFun commented on it. But I think it's still better than the actual one :)

**Comment by Ombridride** [comment]
We already used a better version of this mod, it's a really useless mod for us.
