### ISSUE TITLE
moreblocks glasses losts their "connected" property

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#330]
Default glass still has it on the server but the moreblocks glasses I tried don't (clean and super_glow).

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/ea4fc7f70c0b523faaa9f2dec7d6b79ed2aa4270

**Comment by Ombridride** [comment]
Need to comment our changes before the next update of this mod.

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/50170dcaff2c4da904719a53e990f3b0c16b2599
