### ISSUE TITLE
Update [no_sneak_glitch] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#331]
A mettre à jour sur MFF-Classic
https://forum.minetest.net/viewtopic.php?f=11&t=10424&view=unread#p200289

Je pense qu'ajouter ce mod anti "usebug" du sneak sur tous les serveurs serai une bonne chose

**Comment by LeMagnesium** [comment]
Je ne pense pas que ce mod soit utile, le système d'amortissement des dommages dus à la chute est très utile, tout comme le fait de grimper rapidement certaine structure. Certains mini-jeux ne peuvent même pas être complétés sans le sneak (exemple : le "Living on the Edge" de Hg, ainsi que d'autres de ces mini-jeux, comme "Waterfall"). Parfois, utiliser sneak est le seul moyen de grimper une montagne ou de survive à une chute. Sur le classic, Carbone nous empêche déjà d'utiliser une partie des fonctionnalité du sneak : la faculté à pouvoir sauter de deux nodes d'un coup avec sneak.
Ce mod ne fixe même pas le seul bug que je juge réel et important avec sneak : celui ajouté en 0.4.13 qui permet de passer à travers le plafond en sautant sur une certaine structure.
Donc, :-1:.

**Comment by Ombridride** [comment]
As we discuss, we need to check if we have the "double node jump" feature or not in the server

**Comment by LeMagnesium** [comment]
The double node jump feature works on the server.

**Comment by ObaniGemini** [comment]
I experienced this mod on another server. It's a REAAAAALLY bad feature. It totaly disables the sneak advantages, and only leaves the "slowing" function.

**Comment by Ombridride** [comment]
Not needed.
