### ISSUE TITLE
Jukebox tweaks

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#333]
The trololol music is too long, need to take just 30sec for example...

And it will take less space, that's an another good point

(applied it to all servers)

**Comment by LeMagnesium** [comment]
That song was just a test, we can even remove it, it's not a problem.

**Comment by Ombridride** [comment]
No need to removed it, It's funny :)

Just need to make it smaller, 30sec is enough

**Comment by ObaniGemini** [comment]
I'll do that

**Comment by Ombridride** [comment]
Perfect, thank you @ObaniGemini 
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/f29dd3be7d2f1576d928f1c63be5328258ff6625

**Comment by ObaniGemini** [comment]
Creative : https://github.com/MinetestForFun/server-minetestforfun-creative/commit/f29dd3be7d2f1576d928f1c63be5328258ff6625
Classic : https://github.com/MinetestForFun/server-minetestforfun/commit/51ab6f3eb3653d3998f8e2b6b8d9bde5e8f65bdd
