### ISSUE TITLE
Autohide hudbars

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#334]
I like the idea, maybe it will be interresting someday ? write here for "post-it"

https://forum.minetest.net/viewtopic.php?f=9&t=13707

**Comment by crabman77** [comment]
bof, ça cache la hotbar, ce qui veut dire que si tu veut sélectionner un truc rapidement tu va devoir faire une sélection au pif pour faire apparaître la hotbar puis sélectionner le bon item, sans compter le lag.
Imagine tu mine, tu te fait attaquer par un mod, oup's ou est l’épée? il va falloir chercher au pif le temps que la hotbar apparaisse.
Même pour la construction ça doit être pénible de ne pas avoir le visuel de ce que l'on peut selectionner.
Le but de la hotbar c'est d'avoir un visuel rapidement, avec ce mod elle perd tout son sens.

**Comment by Ombridride** [comment]
Je vois ou tu veux en venir, je le met là en post-it, ce sera peut etre jamais utilisé, mais ça a le mérite d'être possible, l'implémentation que je voyais le plus probable était pour le creative

**Comment by ObaniGemini** [comment]
Alors peut-être déplacer le ticket ?

**Comment by LeMagnesium** [comment]
Je suis d'accord avec @crabman77 , le but de la hotbar c'est de montrer un accès rapide aux huit (chez nous seize) cases d'items utilisables. Si elle est vraiment gênante, et elle ne l'est en général que pour les screenshots, on masque le HUD avec F1. (Si la barre gêne elle gênera autant que la minimap et les lignes d'infos debug je pense)

**Comment by Ombridride** [comment]
Je clos le ticket, si un jour ce mécanisme est utile on aura ce ticket dans un coin :)
