### ISSUE TITLE
Christmas gifts

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#335]
Most of the time, they yield nothing at all, which is revolting. **A Christmas gift should never be empty**. And Some of the existing gifts are weird like a brick block, a bookshelf, a furnace, a chest etc. We have a lot of decoration items which could be added to the gifts like potted flowers, books, chocolate... **Some gifts yield unknown nodes**, like "diamonds:{pick, shovel, block}".

The colored packages require so much dye (6 for the cardboard box) that players only crafted the colorless one last year, which was the less yielding but most rewarding one I think, according to the code at that time. All the colors should have the same chance to yield the same thing I think. And they shouldn't cost so much dye.

**Comment by Ombridride** [comment]
Thank you for your report @mgl512 
we will investigate/fix it as soon as possible (maybe tomorrow)

**Comment by LeMagnesium** [comment]
This is very peculiar, considering that the code itself [asks for at least one item to be dropped](https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/christmas_craft/init.lua#L319) :

    drop = {
        max_items = 1, min_items = 1, items = {
            {items = {'default:bookshelf'},	rarity = 90,},
            [etc...]

My theory is that the rarity factors should be complementary, otherwise the engine will have a chance of dropping nothing.

**Comment by mgl512** [comment]
It's the code for the white package. I tried 20 of them and only 3 yielded something : 2 signs and a steel shovel (a sign is a disgusting gift by the way). Maybe the last line of the drop list should have a rarity of 1 for the code to work as expected. The colored packages don't even have a minimum number of items to drop. Their code is different. You can see the unknown nodes there, the 'diamonds:*' items. I think it should be the same drop list whatever the color of the package.

**Comment by LeMagnesium** [comment]
Making the rarity factors all equal to 18 (the amount of different items that can be dropped) helps but doesn't solve the problem, 1/6 of the time it drops nothing.

**Comment by mgl512** [comment]
If i set the rarity of the last item to 1 (dirt_with_grass for the colorless package), I always have a gift: the dirt_with_grass if all the previous ones of the list fail. It's a default if all the other items failed their chance.

**Comment by LeMagnesium** [comment]
That could be our chance. But having a default gift is not good for me, gifts should still be randomized. What is we used the last item as default but to drop the present box so that players can place it again?

**Comment by mgl512** [comment]
This surprising idea is full of Christmas spirit !  :+1:

**Comment by ObaniGemini** [comment]
I think a christmas gifts event could be good. But I won't be there for that :> (more explanations on IRC if you want)

Example : a room full of christmas gifts and everyone has to take his part.

**Comment by LeMagnesium** [comment]
Then if we agree on this, I'm going to keep the current rarity values (because most of them are actually OK for us, the worse being those on the "Christmas Present"'s drop) and add a 'default case' that will drop the christmas present.
(I'm also going to change a thing regarding the sapling's drop, now that I understood how those drop fields work, I'm going to change a fix I did months ago.)

**Comment by mgl512** [comment]
For the recipes, I made 10 colored Christmas gifts on the server with the original recipes. It cost me 150 paper sheets and 60 colored + 20 red + 10 black dyes. You have to have stacks of papyrus and a lot of flowers.

**Comment by Ombridride** [comment]
Ok, the cost of the colored christmas gifts is too high...

We need to make this recipe easier.
Can someone list here the available gifts from the colored christmas gifts ?

**Comment by LeMagnesium** [comment]
The time has passed I think... Presents are not in use anymore... Can we close this?

**Comment by ObaniGemini** [comment]
Maybe should we fix it for next Christmas ? ^^

**Comment by mgl512** [comment]
Made a dozen or more but didn't give any of them to anyone. Didn't even log in 2016 yet I think. OK to close.
