### ISSUE TITLE
[hudbars] hide/unhide crashed a server

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#336]
Shiva report us a server crash about the new feature of the **hudbars** mod, here is it : 

```
18:12:24: ERROR[main]: ERROR: An unhandled exception occurred: .../mods/hudbars/init.lua:254: attempt to index field '?' (a nil value)
18:12:24: ERROR[main]: stack traceback:
18:12:24: ERROR[main]: .../mods/hudbars/init.lua:254: in function 'unhide_hudbar'
18:12:24: ERROR[main]: .../mods/hudbars/init.lua:324: in function 'update_hud'
18:12:24: ERROR[main]: .../mods/hudbars/init.lua:354: in function '?'
18:12:24: ERROR[main]: .../builtin/game/register.lua:341: in function <.../builtin/game/register.lua:329>

In thread 7fa9d0a60740:
/mnt/p3/minetest/minetest-minetest-cd4324e/src/main.cpp:312: int main(int, char**): Assertion '0' failed.
Debug stacks:
DEBUG STACK FOR THREAD 7fa9c9275700:
#0 virtual void* CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 7fa9d0a60740:
#0 int main(int, char**)
(Leftover data: #1 Dedicated server branch)
(Leftover data: #2 virtual void ServerMap::save(ModifiedState))
(Leftover data: #3 void ItemStack::serialize(std::ostream&) const)
```

Linked to the forum post : https://forum.minetest.net/viewtopic.php?f=20&t=13734&p=201557#p201466

**Comment by crabman77** [comment]
lol, c'est hudbars. c'est pas nous. 
En plus si la var n'existe pas il ne cache tout simplement pas le menu, donc il y a peu de chance d'avoir un crash avec hide/unhide de unified_inventory.

**Comment by Ombridride** [comment]
@crabman77 
Shiva utilise notre verison du repository (donc de hudbars), en d'autre terme son crash équivaut à un crash de notre serveur, d'où le post ici.

Désolé de ne pas l'avoir précisé, il était tard lors de la création de ce ticket, et je n'ai pas été présent sur l'IRC pour l'expliquer... :)

**Comment by crabman77** [comment]
Ok, bon déjà il est en 0.4.12 et il n'a peut être pas la dernière version de notre repo.
La ligne qui correspond au crash n'a pas l'air de correspondre, il faut qu'il update puis si ça continue on fixera si ce n'est pas déjà fait.

**Comment by d-stephane** [comment]
En effet, je n'ai pas la dernière version du dépôt, je vais donc faire une petite mise à jour histoire de voir ce que ça donne. Par contre je ne sais pas trop comment reproduire le bug...

**Comment by crabman77** [comment]
Cela dépend de combien de temps date ta version, on a ajouté mff_hud en dépendance, donc il va le falloir aussi si tu ne l'a pas.

Il me semble qu'on a ajouté des truc seulement géré par la 0.4.13.
Sinon si tu peut mettre le fichier hudbars/init.lua ici -> http://zerobin.qbuissondebon.info/
pour voir ce qui crash, je pense à un joueur qui se déco entre temps et donc la variable n'existerait plus.

**Comment by d-stephane** [comment]
Niveau version je compte recompiler la dernière version du jeu histoire d'être à jour.
Ce plantage arrive même si je suis seul sur le serveur donc je ne pense pas que ce soit un soucis de déconnexion. Sinon voici le fichier :
http://zerobin.qbuissondebon.info/?275fc8845060701a#hANPQc/rdpnK72oRV+Ij5AbwZ4jxZk2QlCMXULyZkwk=

**Comment by crabman77** [comment]
On avait bien un fix, voila la version patchée si tu ne veut pas update tout (j'ai fix que le bug, pas mis les dernier ajouts) http://zerobin.qbuissondebon.info/?4a6abaa6b569d05d#XoR5Uj6dWryA7ooroX3MB3EMiJWpTDgb6X6yF/pVs0U=

**Comment by d-stephane** [comment]
Ok, je test tout de suite. Merci à toi

**Comment by Ombridride** [comment]
Merci à crabman pour sa réaction rapide :)

Attendons une validation de @d-stephane puis fermons le ticket si tout est bon.

**Comment by d-stephane** [comment]
Pour le moment toujours pas de plantage, donc ça roule :-)

**Comment by Ombridride** [comment]
Ok, je clos donc l'incident.

Si tu rencontres de nouveaux une erreur, n'hésite pas à réouvrir le ticket !

**Comment by d-stephane** [comment]
De nouveau le même type de plantage qui survient lors de la connexion d'un joueur. En trois jours c'est arrivé trois fois :
```lua
12:40:35: ERROR[main]: ERROR: An unhandled exception occurred: .../mods/hudbars/init.lua:184: attempt to index field '?' (a nil value)
12:40:35: ERROR[main]: stack traceback:
12:40:35: ERROR[main]: 	.../mods/hudbars/init.lua:184: in function 'change_hudbar'
12:40:35: ERROR[main]: 	.../mods/hudbars/init.lua:329: in function 'update_hud'
12:40:35: ERROR[main]: 	.../mods/hudbars/init.lua:354: in function '?'
12:40:35: ERROR[main]: 	.../builtin/game/register.lua:341: in function <.../builtin/game/register.lua:329>

In thread 7f6d50c19740:
/mnt/p3/minetest/minetest-minetest-cd4324e/src/main.cpp:312: int main(int, char**): Assertion '0' failed.
Debug stacks:
DEBUG STACK FOR THREAD 7f6d49630700:
#0  virtual void* CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 7f6d50c19740:
#0  int main(int, char**)
(Leftover data: #1  Dedicated server branch)
(Leftover data: #2  virtual void ServerMap::save(ModifiedState))
(Leftover data: #3  void ItemStack::serialize(std::ostream&) const)
```

**Comment by crabman77** [comment]
Apparemment la hudbars pour le joueur n'a pas encore été crée, un callback appelé trop tôt peut être, j'ai mis un return si pas de nom pour le joueur ou pas de hudbars, ça ne devrait plus crash.
http://zerobin.qbuissondebon.info/?527ed019eed9e456#slb+H9tipulBfclPU5RRpyFSDfPRp4o56JT9YsCV9+0=

**Comment by d-stephane** [comment]
Ok merci à toi, je viens de mettre à jour chez moi. Je vais voir si ça replante...

**Comment by Ombridride** [comment]
(Laissons le ticket ouvert une semaine au cas ou... :))
