### ISSUE TITLE
Fishing: "Shark bait ball" doesn't work

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#337]
Rapporté par Ju. C'est l'appat fait en craftant deux poissons. La canne ne pose pas le bouchon avec cet appat.

**Comment by crabman77** [comment]
ce n'est pas un appât mais de l'amorce, tu doit la jeter sur le bouchon, ça augmente la chance de 20%.

**Comment by mgl512** [comment]
Houlà, va falloir mettre ça dans les messages aléatoires envoyés au joueur ou crafter un livre "Le guide du pêcheur". Avec quelques noeuds de pêche le guide :p

**Comment by ObaniGemini** [comment]
@mgl512 : si tu veux aider à faire le serverguide, personne ne s'est encore attelé à la tache (le mod est dans le dépot). Si tu veux le faire en français, on traduira, mais personne n'a encore écrit pour le remplir.

**Comment by Ombridride** [comment]
Please, closed this issue when a random message is added with this explaination

**MFF_Classic** and **MFF_Creative** need this message.

**Comment by crabman77** [comment]
Je suis entrain de faire un guide. Un livre à crafter ou bien un formspec dans le menu fishing, à voir.

**Comment by Ombridride** [comment]
Oui bonne idée, seulement on a déjà un mod "guide" avec un bouquin tout pret, il suffit de lui rajouter un onglet @crabman77 

Quoiqu'il en soit un random mesages ou deux pour expliquer les différentes (riches) fonctionnalités de ton mod fishing seraient un plus :)

**Comment by crabman77** [comment]
le guide sera dans fishing directement,  sur le forum ils en parlent qu'ils ne savent pas crafter les appâts.
mais rien n’empêche de faire dans le mod guide aussi.

je ne sais pas si je fais un type d'item par page avec explications en dessous, ou bien tout les items puis une explication dans une autre page.
![capture-1](https://cloud.githubusercontent.com/assets/7189389/11769247/b27b9c42-a1e2-11e5-9d37-6f0b1373562b.png)

**Comment by mgl512** [comment]
Tous les items dans une vue générale comme ça c'est bien. Quand on connait un tout petit peu le mod, on comprend, par exemple, que les petites boules jaunes ne sont pas non plus des appâts mais qu'elles se jettent sur le bouchon comme leur voisin le poisson cru déchiqueté. On n'a pas besoin d'aller regarder dans les autres pages pour avoir l'information.

**Comment by ObaniGemini** [comment]
Dans ce cas, ne pas faire page 1/2 mais faire une page "objets" et une page "informations"

**Comment by Ombridride** [comment]
Je pense que ce ticket peut être fermé ? le problème initial est résolu
@crabman77 je te laisse fermer ce ticket si tu juges qu'il peut l'être
