### ISSUE TITLE
we can place node on the top node of the door

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#339]
![screenshot_20151214_134228](https://cloud.githubusercontent.com/assets/11613522/11781269/ec16633e-a268-11e5-8a4f-0287235e7c69.png)

**Comment by LeMagnesium** [comment]
Sadly, that's normal. Homedecor's doors are a single node expanded onto two places. I don't have any way of preventing this.

**Comment by Ombridride** [comment]
Indeed, it's normal, the second node of the door isn't a "real node", it's an hack of the doors mod.

Closed the issue, thank you anyway for your report :)

**Comment by ObaniGemini** [comment]
It was fixed by @LeMagnesium some time ago with the glass_door, am I wrong ?

**Comment by LeMagnesium** [comment]
@ObaniGemini : You're right, but it was not me. @VanessaE applied a fix on the upstream repository that I merged. I will see if we can use the same principle for those doors then.
