### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#340]
https://forum.minetest.net/viewtopic.php?f=11&t=13752&hilit=report

- [X] Add this mod to all of our servers.
- [x] Maybe add a button to use it
- [x] Add a random message for explain this mod

Also add this mod with the report :
https://forum.minetest.net/viewtopic.php?f=11&t=13754

**Comment by LeMagnesium** [comment]
Should we add that on other servers?

**Comment by LeMagnesium** [comment]
I think we can add a button fairly easily on Creative and Classic, but not on Hungry Games nor Skyblock.

**Comment by Ombridride** [comment]
On Hungry games it can be a "tab" (Report), for the Skyblock, a button was added earlier this month, so it's possible (but boring :/)

We need an icon for the report button,  maybe a red /!\, i don't know

**Comment by LeMagnesium** [comment]
> We need an icon for the report button, maybe a red /!\, i don't know

A red danger sign would be good enough for the texture. Also, I don't think a feature like report deserves an entire tab in Hg's inventory..

**Comment by Ombridride** [comment]
I agree but i haven't any other idea, maybe @crabman77 will have more ideas ?

**Comment by crabman77** [comment]
add button in HG https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/2e8faf09e98df3f17751a57f8be90b1a3f57aa71
