### ISSUE TITLE
Admins can't see inside doublechests

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#341]
Admins can't see inside doublechests

is it possible to add this feature like for locked chest in default ?

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/0900a41e1161e754e7bdf26d59c945d9d0677a55

**Comment by Ombridride** [comment]
Thank you, 
Solved, I closed the issue
