### ISSUE TITLE
christmas_craft snowball

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#342]
From the IRC today :
<JAPP> la boule de neige christmas_craft:snowball ne se pose pas
<JAPP> mais default:snow ce pose

Need to fix it :)

Have only one type of snowball will be maybe better ?

**Comment by crabman77** [comment]
Quel est le mieux?
1) désactiver les snowball en commentant le code puis créer un alias vers default:snow pour les crafts et items sur la map.

2) la réponse 1) et changer les craft dans le code par default:snow en +.

**Comment by Ombridride** [comment]
je pencherai plus vers la 2

**Comment by crabman77** [comment]
fixed, oup's oublié de le mettre dans le message de commit https://github.com/MinetestForFun/server-minetestforfun/commit/faa6a045a4d78c17cc400a84bdb2361982281973
