### ISSUE TITLE
Chatplus problem /!\

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#343]
Des joueurs ne voient plus ce que les autres joueurs écrivent en jeu, par contre ils peuvent voir ce que les gens de l'irc leur dit

ça a commencé hier (suite au merge), je pense que ça vient de la dernière update de chatplus https://github.com/MinetestForFun/server-minetestforfun/commit/fe33132577f3954457bf3a0fe81491c124cd3ef1

Ce n'est pas dû a l'os, la version de minetest ou des privileges (privs pareil, os different et version de minetest differente pour tous)

@LeMagnesium @crabman77

**Comment by Ombridride** [comment]
After your fix, the problem is still here

The server was merged here : https://github.com/MinetestForFun/server-minetestforfun/commit/6d807e89562ebb9c28b652151c056a4de64a3441

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/f4ceb21bb03f56d9f3f8059b0d7e2c1463f21677
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/94265f586a68e3dcaa3ba77d9cb51045e6976a04
Should be enough.
