### ISSUE TITLE
Christmas trees don't grow

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#344]
The small pine "snow:pine_sapling"  and the Christmas tree sapling "snow:xmas_tree" won't grow on MFF because their ABMs are in the disabled file "snow/src/abms.lua". When you break the leaves a  small pine, you have a chance (1/120) to get a xmas sapling. I have both saplings since the beginning of the new map but they don't grow.

If you disabled the snow ABMs for another reason, it would be a good idea to move the sapling ABMs in another file and load it, or the best we will have is a Christmas bonsai.

**Comment by LeMagnesium** [comment]
We disabled snow's ABMs because they were constantly crashing the servers. Thus, I don't even know why we still have christmas saplings. We could try to debug it though.

**Comment by Ombridride** [comment]
I prefer desactivate it and remove the sapling ;)

**Comment by mgl512** [comment]
There is no Christmas sapling in "christmas_craft:". The only one was in "snow:"

**Comment by Ombridride** [comment]
That's what Mg does, he commented the snow sapling

**Comment by HybridDog** [comment]
Why did it crash?

**Comment by Ombridride** [comment]
Because we disabled snow's ABMs, we just forget to disable this sapling

**Comment by HybridDog** [comment]
>We disabled snow's ABMs because they were constantly crashing the servers.

>Why did it crash?

>Because we disabled snow's ABMs,

Why did the abms crash the server constantly?

**Comment by LeMagnesium** [comment]
> Why did the abms crash the server constantly?

It was using a method defined in a file that was no longer loaded (`src/mapgen.lua`) since we didn't need it anymore. At some point when I realized that I wanted to move the function in a loaded file and enable the christmas tree's ABM again but since we have `christmas_craft` I was asked to remove both pine and xmas tree saplings from snow.

**Comment by HybridDog** [comment]
thanks, l use snow's mapgen (v6) because l like it more than the default one e.g. because of the snowdrifts.
