### ISSUE TITLE
4 snow balls --crafting--> christmas_craft:snow_block

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#346]
MFF told they should make "default:snowblock" instead. And that "christmas_craft:snow_block" shouldn't exist.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/45d4f97dba3d7ffcce0121738a7c37a4f60a4752
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/e580f5f6ef4e9d71e1b5df89cac3f25639e4f83f
So far that's how we fixed it, but we should later remove and alias that node.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/6db59ee981d85a7520b937de0379b0f915d55c02
