### ISSUE TITLE
One more website banner

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#347]
Im thinking about a website banner for promote @Cyberpangolin youtube channel

So, @Cyberpangolin, do not hesitate to give us a banner if you agree with the idea ! :)

**Comment by Cyberpangolin** [comment]
Thanks @Ombridride !

Which size do you want?
I may make it today.

**Comment by Ombridride** [comment]
2min i edit this post to answer you

**Comment by Cyberpangolin** [comment]
[cyberbannière.zip](https://github.com/MinetestForFun/server-minetestforfun/files/76724/cyberbanniere.zip)

and here you are!

**Comment by Ombridride** [comment]
![slider_cyber](https://cloud.githubusercontent.com/assets/8619233/12145951/65fd5b8c-b491-11e5-859a-10741349ad36.png)

Slider added ! The slider is clickable and link to https://www.youtube.com/user/CyberPangolin

**Comment by Ombridride** [comment]
The font can be changed if you want it, I need an external API, i didn't find something more pixelised... Maybe @Obani have a better font.

For the moment i closed the issue, if you have improvments do not hesitate !

**Comment by Cyberpangolin** [comment]
Jeux libreS ;) il y en a plusieurs.
Jolie animation, merci beaucoup! ;)

**Comment by Ombridride** [comment]
Fixed.
