### ISSUE TITLE
Missing mobs admin inventory icons

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#348]
![Missing mobs admin inventory icons](http://i.imgur.com/kj1C5K2.png)

**Comment by crabman77** [comment]
oui je suis au courant, mais ce sont les œufs de mobs qui les créer. il n'y en a pas pour les boss pumking et ent.

**Comment by Ombridride** [comment]
Pas de soucis, il faut donc créer les oeufs de ces monstres, toute façon seulement l'admin peut les voir ou utiliser ce menu

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/306efd836c8b8cbcebdaa581d5d6376b14d73e4d

![conv-mob_inv](https://cloud.githubusercontent.com/assets/7189389/12007277/4b36421a-abfd-11e5-84a0-30ca2e5a1d89.jpg)
