### ISSUE TITLE
Unknown nodes in spawn tower

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#349]
I can't tell what they are. There are nodes from the christmas_craft mod around. I think it's not its former snow block because the ones I had were successfully converted to default snow blocks.

**Comment by LeMagnesium** [comment]
They are christmas tree saplings. @Ombridride can take care of them.

**Comment by Ombridride** [comment]
I removed them from the spawn, I also add an alias https://github.com/MinetestForFun/server-minetestforfun/commit/37edd5ee7ef62881452cdfd58614739fd89a406c

Closed the issue.
