### ISSUE TITLE
Update [nether] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#351]
https://github.com/HybridDog/nether-pack/commits/master

Need to apply it also on creative server

WARNING : do not erase our (sometimes uncommented) tweaks !

**Comment by HybridDog** [comment]
There's a well working way to update your version to the newest nether mod using a submodule:

1. fork https://github.com/HybridDog/nether-pack
2. make a new branch
3. delete everything except .git/ (don't (add and) commit this)
4. copy everything inside that folder (server-minetestforfun/mods/nether/) to where you deleted the files before
5. run $ git add -A && git commit -m "apply our differences"
6. remove server-minetestforfun/mods/nether/ and put your fork as submodule there

The only problem is that the history (who changed what and when) isn't kept, but the advantages are that you can run $ git pull --rebase https://github.com/HybridDog/nether-pack master for updating and sometimes fix conflicts (edit files and then run $ git add -A; git rebase --continue; git status)

**Comment by LeMagnesium** [comment]
Oh, thanks @HybridDog. But since we have differences between Classic's version and Creative's version I'm not sure it will be that handy.
(meanwhile : https://github.com/MinetestForFun/server-minetestforfun/commit/8eebd39db8b32f0df904d8de3c9e048bc2f379bd and https://github.com/MinetestForFun/server-minetestforfun-creative/commit/85d6b1479148778fe5e233c818b030e195d8ff5a)

**Comment by HybridDog** [comment]
>since we have differences between Classic's version and Creative's version I'm not sure it will be that handy.

You could make e.g. the creative's version base on the classic's one and rebase it to that and add commits which makes it different

**Comment by LeMagnesium** [comment]
> You could make e.g. the creative's version base on the classic's one and rebase it to that and add commits which makes it different

Do you mean using branches? I discovered how to force a submodule to use a specific branch from a remote repository, so creating a fork with two branches, one for each server, would work perfectly.

**Comment by HybridDog** [comment]
>Otherwise we could use two forks but that would probably waste disk storage space (although GitHub may have plenty of it).

l think using branches works better because e.g. to get both you need to clone only once.

**Comment by Ombridride** [comment]
Update was applied, I closed the issue.

Thank you @LeMagnesium and @HybridDog
