### ISSUE TITLE
Update [riesenpilz] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#352]
https://github.com/HybridDog/riesenpilz/commits/master

Need to apply it also on creative server

WARNING : do not erase our (sometimes uncommented) tweaks !

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/ee352dbc60794113e15174cd0b274ef54e1ffc24
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/78e95d58faebb2e529a3d3d583b1119c4efb165c
