### ISSUE TITLE
gource

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#353]
@Cyberpangolin 
Adapt this command line like you want for the video rendering :
```
gource --title "Two years of \"MinetestForFun Classic server\" development" -1280x720 --seconds-per-day 0.5 --hide dirnames,filenames --logo /home/quentinbd/Images/gource/logo_github_100.png --user-image-dir /home/quentinbd/Images/gource/ --user-scale 7x7 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 2years_mff_devs_team_gource.mp4
```

For the files you need : 
/home/quentinbd/Images/gource/ = http://jheberg.net/captcha/gsource/
/home/quentinbd/Images/gource/logo_github_100.png = ![logo_github_100](https://cloud.githubusercontent.com/assets/8619233/12039136/141b6248-ae5e-11e5-9474-2ab8ef695211.png)

**Comment by Cyberpangolin** [comment]
Here is what I have now, with my settings:

gource --title "More than two years of \"MinetestForFun Classic server\" development" -3840x2160 --seconds-per-day 0.5 --hide dirnames,filenames --logo /home/moi/Bureau/videogource/logomff.png --user-image-dir /home/moi/Bureau/videogource/gource/ --user-scale 7x7 -o - | avconv -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset fast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 /home/moi/Bureau/videogource/2years_mff_devs_team_gource.mp4

but It doesn't know where to  take the git repo...

**Comment by Ombridride** [comment]
I given you the answer in "later tell" Sambot feature, but i will repeat it here :

you need to launch gource in the project folder you want to visualize, so you need a local up-to-date mff_classic repository localy, just go into this folder with cd, and put your gource command here :)

**Comment by Cyberpangolin** [comment]
[image2pipe @ 0xfb1580] Could not find codec parameters (Video: ppm)
[image2pipe @ 0xfb1580] Estimating duration from bitrate, this may be inaccurate
pipe:: could not find codec parameters

I installed ~10 packages without finding the answer to that and ran after the forums. I also tried to replace ppm with mjpeg or png without any better result.

Any idea is welcome...

**Comment by Ombridride** [comment]
https://code.google.com/p/gource/issues/detail?id=115
https://code.google.com/p/gource/issues/detail?id=29#c11
https://askubuntu.com/questions/48053/gource-export-video-error-could-not-find-codec-parameters

**Comment by Cyberpangolin** [comment]
How stupid am I!
All I need was installed, but I forgot to change a directory place in my command.
-- > rendering now in 3840x2160 px, should be done and uploaded in some hours.

**Comment by Ombridride** [comment]
Ok, good news :)

Do you find a music ?

Can you create a screen before the gource  ? 
With :
- our new logo (Obani new logo)
- and a little title/explanation

Example of the screen i describe, this is the second screen after "runic" here : https://www.youtube.com/watch?feature=player_embedded&v=byNjZvZfvAM

**Comment by HybridDog** [comment]
There's also something called codeswarm
https://vimeo.com/1940073

**Comment by Cyberpangolin** [comment]
Here is the "intro" before the gource. please note:
it's 4k and 60 fps, so you might experiment problems with it.

[untitled.mp4.zip](https://github.com/MinetestForFun/server-minetestforfun/files/75234/untitled.mp4.zip)

I asked @ObaniGemini for some music, hoping he comes on IRC (or here) soon

**Comment by Cyberpangolin** [comment]
Ok, here is a preview without any sound.
https://youtu.be/Z5tqFMwI4qM
The video is quite light (57.4Mio), expect 60Mio with the sound.
-> @Ombridride  Do you want to keep it on our serv?

**Comment by Ombridride** [comment]
The preview is beautiful, good job ! :)

It's possible to reduce the "ambient light", it's the "bloom" parameter if I remember well, try/tweak :
```
--bloom-multiplier 1.0 --bloom-intensity 0.66
```

For the sound, no idea which one to add

Finally, what's the software do you use for the start screens ? (i need to do my hands with this kind of softwares) :)

**Comment by Cyberpangolin** [comment]
kdenlive -> use the transition "affine", applied on "black". size=60% at the start, 100% at 1s, 110% at 3 seconds (use key frames for that). Do not forget to center at each key frame.
to switch between the titles I added a fade to and from black, 0.5s each.
And... here we are.

v2: https://youtu.be/g_A0E_vxONA

gource --bloom-intensity 0.2 --bloom-multiplier 0.2 --title "More than two years of \"MinetestForFun Classic server\" development" -1920x1080 --seconds-per-day 0.5 --hide dirnames,filenames --logo /home/moi/videogource/logomff.png --user-image-dir /home/moi/videogource/gource/ --user-scale 7x7 -o - | avconv -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 3 -bf 0 /home/moi/backup/moi/2years_mff_devs_team_gource.mp4


(Yeps I have a backup drive mounted in ~/backup, and then what?)

kdenlive rendering settings: 
f=mp4 hq=1 acodec=aac vcodec=libx264 preset=faster threads=7

**Comment by Ombridride** [comment]
1) Xorhub - When Freedom meets fun
2) Proudly present
3) More than 2 years ok
4) "MinetestForFun Classic"
       server development
5) gource
Maybe it's bettter like this ?

For the music, i find this : http://opengameart.org/content/vivid-existence-glitch-hop

Before the level 1 sound of the music (0:01 to 0:53) => screens view, 0:00 to 0:09 of the video
After the level 1 sound of the music (0:54) => 0:10 of the video
after 4:25 the music will shut down slowly, maybe freeze the screen a few seconds in the video at 4:37 to 4:42(5sec freeze) to let the music shutting down completly for a better end effect

**Comment by Cyberpangolin** [comment]
Ok, I will make it tomorrow!

happy new year! :dancer:

**Comment by Cyberpangolin** [comment]
Bim!

video trough YT: ->  https://youtu.be/z2uFNbBOfOU
do you want the file? -> http://jheberg.net/captcha/xorhubv3/

**Comment by Cyberpangolin** [comment]
The video is on the website -> I close this ticket.
