### ISSUE TITLE
[Warp Stone] bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#354]
*Warp Stone* bug when teleporting with sneak

![warp stone bug](http://i.imgur.com/q3gi7vo.png)

**Comment by LeMagnesium** [comment]
I don't see any line of code in `warps` infering any random teleport mechanism. Seeing how it happens though I think it might be an engine bug.

**Comment by gravgun** [comment]
@LeMagnesium The universe is telling me an engine bug is more than likely :grin:

**Comment by LeMagnesium** [comment]
It seems like pressing sneak while being teleported makes the player stuck on the edges of the ground's nodes, and such movements make the engine think it's actually speed cheating. It ends up resetting the player's position.
There's litterally nothing we can do here.

**Comment by HybridDog** [comment]
l don't understand the problem.

**Comment by LeMagnesium** [comment]
@HybridDog is your console spammed with warning messages about resetting the player's position when you try teleporting whilst holding shift?

**Comment by HybridDog** [comment]
No, l think anticheat is disabled by default in singleplayer mode and there may be a bug at localplayer.cpp which causes that when a player holds shift, his position is set next to the node where he/she begun holding shift even if his new position is more than 100 m away, he/she gets put there.

**Comment by LeMagnesium** [comment]
So even though it might not be anticheat's fault, there's still a bug related to using sneak on nodes' edges.
I'm gonna report that if it has not already been done..

**Comment by HybridDog** [comment]
> […] if it has not already been done..

https://github.com/minetest/minetest/issues/2876

**Comment by Ombridride** [comment]
Need to know if it's fixed after the latest @HybridDog commit : https://github.com/minetest/minetest/issues/2876

**Comment by HybridDog** [comment]
>Need to know if it's fixed […]

The PR doesn't get merged:
https://github.com/minetest/minetest/pull/3535

**Comment by Ombridride** [comment]
As this fix will be merged on our servers only when the "0.4.14-stable minetest" version will come, i closed this issue.

In fact, we use only stable release for our Minetest server, so, we can't fix this for the moment, we will not use a -dev version, hope the 0.4.14-stable will come soon :)

**Comment by HybridDog** [comment]
Obviously some fix was added recently:
https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c

l'm wondering whether my PR gets closed…

**Comment by ObaniGemini** [comment]
https://github.com/minetest/minetest/commit/c0b6986e3875e6f42682c78fd5db0080a7bae651
