### ISSUE TITLE
Fences pointing to west connection

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#357]
I just noticed that putting a fence that should connect to its west side prefers to turn back to the east. 

After testing, it does NOT affect jungle fences.

a screenshot is better to explain:

![capture du 2016-01-04 06 54 48](https://cloud.githubusercontent.com/assets/12512762/12084230/df72485c-b2b0-11e5-9808-84c33646f684.png)

I put it under a medium priority because it's annoying/ugly/bad (choose what you prefer) to see but not critical for the gameplay.

EDIT: this doesn't affect fences that were placed some weeks ago.

**Comment by Ombridride** [comment]
If i understand well, this problem is just for the newer fences you put and not for the old fences you putted before ?

**Comment by farfadet46** [comment]
The colision is wrong too (we can pass up the fence we walk on the little piece of wood)

**Comment by Cyberpangolin** [comment]
@Ombridride exactly.

**Comment by Ombridride** [comment]
The fences code hasn't changed since a very long time ago... https://github.com/MinetestForFun/server-minetestforfun/commits/a2b30a2abaa9336f5d24e72ac44a2add0a008e86/mods/fences

Maybe something interfer/overwrite the fences "link" algorithm... We need to investigate

**Comment by LeMagnesium** [comment]
The fences' link algorithm has been broken ever since we had that mod. I still don't know why we still have it and why we didn't register more fences in MFF_Game with the fence drawtype instead.

**Comment by Ombridride** [comment]
Upstream Minetest_Game maybe ? @crabman77 @mgl512

**Comment by ObaniGemini** [comment]
Glad to see it was finally reported and fixed :D
