### ISSUE TITLE
The Tree Fern Crown (Dicksonia) model is too little near invisible

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#359]
![screenshot_20160104_111308](https://cloud.githubusercontent.com/assets/11613522/12087574/62a6c6ee-b2d4-11e5-8111-9dd683759eb0.png)

**Comment by Ombridride** [comment]
The dropped model after you cut it is too small, is it right ?

**Comment by farfadet46** [comment]
yep when we cut the tree, there is a foliage and one seed spawn. the foliagle model is ridiculously too small yeah (and when you put the foliage on the ground and cut it from the ground it's spawn one seed and on other foliage = free seed \o/ :)

**Comment by LeMagnesium** [comment]
We can't control the appearance of a dropped item, sorry.

**Comment by ObaniGemini** [comment]
But I think we can use another image instead of changing its size

**Comment by Ombridride** [comment]
If we use a picture it will be a node... So this issue can't be resolved...

**Comment by farfadet46** [comment]
the seed is big compared with the foliage. i don't understand why there is this difference :/

**Comment by LeMagnesium** [comment]
Indeed, I just tried locally with some examples. If we create an `inventory_image` for it then it will be used.

**Comment by Ombridride** [comment]
I think we need @VanessaE to understand better this problem... :/
If she can light us, it will be pretty kind from her.

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/1b80d027df937217b44877c895107987dc416df6

c'était dans builtin_item, de ce que j'en comprend, le visual était plus grand que la collision_box et comme le point de repère 0 est en haut, l'image était décentrée vers le bas.

**Comment by Ombridride** [comment]
Purée bien vu, comment tu fais =)

**Comment by ObaniGemini** [comment]
Maybe should we translate the issue for upstream ?
