### ISSUE TITLE
[question] Flower power

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#361]
If I understood well, flowers are supposed to spawn only if they are less than 4 in a 9x9x9 cube
@Gael-de-Sailly can probably confirm that.

But strangely, it seems that it is not always applied... I planted only 4 flowers, and here is the result:
![capture du 2016-01-04 16 06 41](https://cloud.githubusercontent.com/assets/12512762/12092515/c699ae0e-b2fd-11e5-9fb3-d364804d56cf.png)

On the surface you can see ~40 flowers for a 25x20 area. Is there anything wrong, or am I paranoid?
the goal is to know if I can enhance my flower factory with more than 3 ones. The best would be to be able to produce every sort of them.

**Comment by Ombridride** [comment]
I think it's like "démineur", a flower can have only 8 other flowers in a 9x9 field.
If it's calculated like this, the flowers you see are possible.

Need someone to confirm that :)

**Comment by Gael-de-Sailly** [comment]
Do not understand "9 blocks far", This 9x9x9 cube is from (x-4, y-4, z-4) to (x+4, y+4, z+4)

**Comment by Cyberpangolin** [comment]
ok, then I can make new plans for my factory. thanks :)

**Comment by Ombridride** [comment]
A good answer is given, i closed the issue.
