### ISSUE TITLE
Maybe add this mod (music_player) ?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#363]
https://forum.minetest.net/viewtopic.php?f=9&t=13841

This mod is like a jukebox, but without discs.
Should we replace jukebox with it ?

If yes, add this to creative too

**Comment by Ombridride** [comment]
-1
We have already the jukebox for this kind of things

**Comment by ObaniGemini** [comment]
"Should we replace jukebox with it ?"
"This mod is like a jukebox, but without discs."

**Comment by LeMagnesium** [comment]
> and the room they take in inventory

That shouldn't be a big issue anymore but yes, I see how discs can be annoying although they're the price to pay in order to listen to music.
I'll look at this mod later.

**Comment by Ombridride** [comment]
This feature is already implemented in-game, i closed the issue because it just makes it easier to use the jukebox, so, not very interesting...
