### ISSUE TITLE
flowing water

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#364]
sometimes flowing water doesn't disappear.
Example: I have put a water source 3 days ago, 50 blocs upper, and some flowing water went down. I came where I am now ~20 times, and I'm still in front of that. No way, it does't stop flowing until I put a block on the top of the flowing water you can see here. 
![capture du 2016-01-05 19 57 33](https://cloud.githubusercontent.com/assets/12512762/12124665/f7a53416-b3e6-11e5-8bcd-906e4b9bff23.png)
I repeat to be sure it's understandable: There is NO water source on the top of this mountain of water, so it should flow down. It might be core-related, I don't know at all. Please change the label if not.

**Comment by Ombridride** [comment]
type /mapfix

**Comment by ObaniGemini** [comment]
I think there's no "code" way to fix it as you would need to check if there is a source, and sometimes it can be located very far. So /mapfix or place node on them :)

**Comment by LeMagnesium** [comment]
This is simply the engine not updating liquids. `mapfix` was created for such cases, and sadly, there's only one way of fixing this : modifying the engine.

**Comment by Ombridride** [comment]
Answers given, use mapfix please, I closed this issue.
