### ISSUE TITLE
Sound when joining is horrible

### ISSUE THREAD

**Issue by fabienwang** [MinetestForFun/server-minetestforfun#365]
Hey, this sounds is soooo horrible.
It is almost like when a wolf attacks you, but hey no it's just a player connecting :laughing: 

Please put a cute little sound that won't scare us hehe.

**Comment by crabman77** [comment]
It's a bug/bad implementation in pclasses,  fixed but no merged https://github.com/MinetestForFun/server-minetestforfun/commit/e0ce022cacd3e533f525dc36669fadc784ccb623

**Comment by Ombridride** [comment]
The equipped class sound, shouldn't be played when you join the game, thank you for the fix @crabman77
