### ISSUE TITLE
Carts mod is messed up

### ISSUE THREAD

**Issue by younishd** [MinetestForFun/server-minetestforfun#366]
The carts mod (which is actually a very useful and nice idea as such) is horribly buggy and basically doesn't work at all as soon as the rails go up or down. There is a lot of stuff that doesn't seem right, but the most annoying bug (which I'm reporting here) is that your cart sometimes (like 90% of the time) just freezes at some point and then it's just sitting there 4 blocks above the ground (see screenshot below). :joy:

I will try to have a look at the source code, too. So, @fabienwang told me that you're not using the upstream version [PilzAdam/carts](https://github.com/PilzAdam/carts) anymore and instead merged a bunch of pull requests that add some features. Can you confirm that?

Finally, do you have some kind of testing/dev server where you can test your code or do you do that locally?

![image_2016-01-06_01-57-32](https://cloud.githubusercontent.com/assets/994290/12133276/0118ffc2-b424-11e5-9828-24a0422df509.png)
![image_2016-01-06_03-01-04](https://cloud.githubusercontent.com/assets/994290/12133278/06776b02-b424-11e5-8c8e-f1d8dac19b5a.png)

**Comment by fabienwang** [comment]
Plop,

Après des tests ensembles, il se trouve que les carts ne bloquent que dans les descentes, lorsque la vélocité atteinte fait que le cart est à 2/3 blocs au dessus des rails (à cause de la vitesse).

On a testé un hack qui fonctionne bien et fait que les carts ne bloquent plus. Pull request incoming ;)

**Comment by fabienwang** [comment]
Note supplémentaire: le reste des fonctionnalités fonctionne bien: jonctions, choix de la direction, powerline qui accélère (par contre elles n'ont pas besoin d'être alimentées par une source d'énergie) mais bon c'est pas grave :)

**Comment by fabienwang** [comment]
J'uploade une vidéo qui montre la correction et les fonctionnalités des carts.

https://youtu.be/Ojd9IbXfsN8

**Comment by Cyberpangolin** [comment]
If it works, it's.. awesome, crazy, fantastic! Keep up the good work! :)

**Comment by fabienwang** [comment]
Well, I should have taken a video record before the fix and after, because it's only after we fixed it I decided to take a video. But let's hope it will work well on your server too :)

**Comment by Ombridride** [comment]
Thank you very much, we will merge this PR ASAP, do you planned to do an UpStream of your code in the forum/repo ?

**Comment by fabienwang** [comment]
The cart freezed only 1 time at lunch while I travelled like 20 times on a 500 blocks track.

So it still happens on server lags, but less often.

1 thing we could do is add some extra checks for let's say 5 more blocks after,
it will just take a few milliseconds and will probably fix the problem forever.

**Comment by Ombridride** [comment]
Yes, lags have bad ipacts on carts, if you can fix it, do it :)
For the upstream, you didn't ask me, do i need to upstream your fix or o you prefer to do that yourself ?

**Comment by fabienwang** [comment]
@Ombridride I prefer to wait until we really fixed it.
Then I guess @younishd or me will try to push it all upstream (their repo has still not merged the controls of the cart (left, right) etc. it's still in a pull request there.)
But if we can show them we have a working version, I guess it will help.

**Comment by Ombridride** [comment]
Yes for the controls, I think the official cart repository is abandoned...
Maybe we should put our carts mod "debugged" and improved in a submodule then, create a forum post with our debugged/improved fork, what do you think about it ?

**Comment by Cyberpangolin** [comment]
I'm again sometimes sticking into the walls when I have a too big climbing slope. maybe something can be done?

**Comment by Darcidride** [comment]
Well, it's because now the carts are too fast, since the last updates...

**Comment by Cyberpangolin** [comment]
then we should maybe slow them a bit, but keep them faster than a running player.

**Comment by Coethium** [comment]
Waiting the discuss #492 , you can dig 1 or 2 blocks above climbing rails to lowering the probability of a collision.

**Comment by Cyberpangolin** [comment]
lowering doesn't mean disappearing, but it's a good start. thanks for the tip.

**Comment by younishd** [comment]
@Coethium If I remember the bug correctly, digging blocks above doesn't affect the cart behaviour at all and it would get stuck in mid-air all the same.

@Darcidride That's correct and the "bugfix" doesn't really fix anything. It was just a dumb hack that checked if the cart went off the rails by some blocks (due to server lag etc.) and then put it back on track.

The thing is: if the server conditions (speed, lag…) change, then the fix might not work anymore. I suppose that currently the cart just lags too much, goes off the rails by too many blocks, and then the hack just does nothing.

A quick and dirty fix would be to increase the hack's threshold and cross fingers. However, the real issue it the fucked-up-beyond-any-repair cart mod which is just poorly written to begin with.

I can suggest a patch with the said fix, if you want to give it a try.

**Comment by Darcidride** [comment]
Ok, we can close this issue, thanks again to @younishd and @Coethium for their work!
