### ISSUE TITLE
news.txt

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#370]
Need to write news.txt !

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/cdcca2632496e73560e6795f46dbf62b75c71bf5

**Comment by Ombridride** [comment]
My god, :kiss: :dancers: :dancer: :dancers: :kiss: => @LeMagnesium 

Thank you so much, it's a lot of work, i know it more than all !
