### ISSUE TITLE
Dungeon Master looting

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#371]
Today I killed 2 DM, without any reward. They did not loot anything.
I dont' think it's a "normal" feature. If I remember well they are supposed to give always something, and sometimes very rare items.

**Comment by Ombridride** [comment]
im looking at the drops, i will edit this answer

**Comment by Cyberpangolin** [comment]
I will cry all I can. It was the first time I won against 2 of them in one day... thanks for the answer.
