### ISSUE TITLE
b91b parkour auto tp doesn't work properly

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#374]
b91b parkour auto tp doesn't work properly

MinetestForFun : when you die in the b91b parkour, you're automatically teleported to the beginning of te parkour :)
Sky27 : no
Sky27 : I return to my home

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/40b3e178941b21b1508c78cca7c544bce31b06f8
