### ISSUE TITLE
Double locked chest bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#376]
Le contenu des Double locked chest est sensée être vu uniquement par le joueur qui le possède et l'admin

Actuellement tous les joueurs peuvent voir les contenus de tous les double locked chests

**Comment by LeMagnesium** [comment]
Je ne peux pas reproduire ça avec des Double Locked Chests, en tout cas pas des nouveaux. Il se peut qu'il faille remettre les chests pour créer les bonnées métadonnées.

**Comment by Ombridride** [comment]
Ok, il faut écrire les news.txt et le préciser dedans donc

**Comment by Ombridride** [comment]
C'est fait.
