### ISSUE TITLE
breaking mesecons wire

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#377]
Did you ever notice how easy it is to cut a mesecon wire?

If you break a stone block but you have a mesecons wire behind, it will instantly break and you won't notice anything until you try your machine and it doesn't work.

-> I suggest to take 0.5 to 0.75 second to break a wire.

**Comment by ObaniGemini** [comment]
:+1:

**Comment by LeMagnesium** [comment]
Ok. Why not. Anyone against it?

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/8d5bad4edf9da3327ad97a7fe1ac3549e675ab19
Could you try digging some wires with this commit @Cyberpangolin ?

**Comment by Ombridride** [comment]
Good idea :+1:

**Comment by Cyberpangolin** [comment]
much better, tested and approved! :+1:
