### ISSUE TITLE
i'm ready for a new mob :)

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#378]
![capture](https://cloud.githubusercontent.com/assets/11613522/12217069/16648f94-b6f5-11e5-8848-dd9c1acdc856.PNG)

maybe ask me for model ?

**Comment by Cyberpangolin** [comment]
let's ride horses! wheheee!

**Comment by farfadet46** [comment]
it's not an horse ... creepy man :p

**Comment by ObaniGemini** [comment]
I don't know if this mob would be accepted in MFF but the KPGmobs mod has horses and it maybe cool to enhance their model/textures

**Comment by Ombridride** [comment]
Add an horse is a good idea :)

But the main problem with them is the code, kpgmobs & mobs framework work with a bugged version of the mounted horses feature and there are terribly horrible/useless to use...

**Comment by Cyberpangolin** [comment]
maybe look in the carts mod? it should not be too difficult to adapt it, probably.
Once again, I'm no coder, I apologize.

**Comment by LeMagnesium** [comment]
Any news on this?

**Comment by farfadet46** [comment]
nope because the script for horses isn't very well :/

**Comment by Ombridride** [comment]
I think you can over your model and give it to the Minetest Community forum, but it will not interest us because of the actual bugged horses, we won't implement it...

Thank you anyway for your work ! :)
