### ISSUE TITLE
"Server shutting down". Or not.

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#379]
![capture du 2016-01-09 18 03 16](https://cloud.githubusercontent.com/assets/12512762/12217295/689387aa-b6fc-11e5-8b20-83a29a18ff17.png)

Look: it says: "Access denied. Reason: Server shutting down."

But... I was still in game in the next minutes, there was no crash... so why did I receive that alert?

**Comment by Ombridride** [comment]
Server Online http://i.imgur.com/p8I57Cs.png
