### ISSUE TITLE
Drastically improve mapgen's speed

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#380]
There is a way to -TOTALLY- kill the lag issue we actually have when someone generates land. The goal is to reduce the size of the chunk, to create only the land we need and not deep undergound or miles above you where you may never go.

the chunk size we actually have is 80x80x80 (size=5 (x 16) and should be decreased to 32x32x32 (size=2 (x 16) to have a really faster way of generating (15x better). Whith such a fast speed, you can be two players flying with the fast privilege, and causing ~1.3s of lag only, on a server based on a i5 laptop (i.e. strongly slower than our official MFF server), with - of course- all MFF-classic mods enabeld and the same generator (watershed).

It is a must have, BUT sadly some mods appear to be buggy, due to the way they are designed: in 80x80x80

This ticket is here to list all known bugs due to the 32x32x32, and then correct them.

Anyone is welcome to bust them on cyberpangolin.ch:30017
Please remember it is NOT a playing server, it might shut down without any warning, and of course any illegal use of my serv will be punished. Anyone can have the admin privs, but it is for DEBUGGING PURPOSE ONLY.

 -  [x]  A bug while generating was too fast already corrected by @Mg
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/snow/src/mapgen_v6.lua
 -  [x]  ~~Some Nether mushrooms lose a part of their heads~~ Nether mod fixed with modular chuncksize
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/nether/nether/pearl.lua
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/nether/nether/portal.lua
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/riesenpilz/mapgen.lua
 -  [x] ~~Nether buildings are replaced by big archs~~ Nether mod fixed with modular chuncksize
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/watershed/init.lua
 -  [x] Meru mountain bugged, need to tweak its code to a modular chuncksize code
 -  [x] https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/meru/init.lua

Feel free to edit this post to add more informations.

(EDITED by @Ombridride 2016-03-02 01:00 PM)

**Comment by Gael-de-Sailly** [comment]
Some mods are not adapted. Here are the mods that use a constant "80" instead of a variable:
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/nether/nether/portal.lua
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/riesenpilz/mapgen.lua
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/snow/src/mapgen_v6.lua
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/nether/nether/pearl.lua
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/watershed/init.lua
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/meru/init.lua

**Comment by ObaniGemini** [comment]
I don't think meru is important as we will probably copy some schematic.

**Comment by Cyberpangolin** [comment]
@Gael-de-Sailly  what if we replace 80 with 32? does it break something?

**Comment by Ombridride** [comment]
After some tests by @crabman77 it seems to be a really instable and hard work to use a lower value than 80...

**Comment by Gael-de-Sailly** [comment]
Do not simply replace 80 with 32. The chunksize can be detected, by `maxp.x - minp.x + 1`.

**Comment by Gael-de-Sailly** [comment]
Where is your code?

**Comment by Ombridride** [comment]
please, @crabman77 can you show @Gael-de-Sailly your tests and tell him your results ?

**Comment by crabman77** [comment]
Il n'y a pas de code modifié, c'est juste la taille du chunk dans la config,  "chunk_size=3", le mapgen fait le reste, mais le mapgen hardcodé avec du "80" n'apprécient pas.

**Comment by Ombridride** [comment]
Si on modifie tous les endroits hardcodés par du dynamique prennant en compte le paramétrage minetest.conf, est-il possible d'avoir un mapgen pas bug et plus rapide ? (a tester)

**Comment by Gael-de-Sailly** [comment]
normalement oui.
Je fais une nouvelle branche sur le repo.

**Comment by crabman77** [comment]
La commande "/regen" de watershed fait crash.
```
ERROR[Main]: Lua: Runtime error from mod 'watershed' in callback on_chat_message(): /var/opt/minetest_stable/bin/../mods/watershed/init.lua:347: bad argument #1 to 'abs' (number expected, got nil)
```

**Comment by Gael-de-Sailly** [comment]
Je n'ai rien changé qui pourrait faire crasher cette commande. Ça devait déjà être le cas avant, mais en tous cas il faut régler ça.

**Comment by Ombridride** [comment]
C'est une commande que je n'ai personnellement jamais utilisé, c'est fort probable qu'elle crashait déjà avant tes modifications

**Comment by Gael-de-Sailly** [comment]
C'est logique, elle utilise des variables qui sont définies au premier chunk généré. Je vois mal comment corriger ça.

**Comment by Ombridride** [comment]
Virer la commande ? on a /deleteblocks maintenant toute façon

**Comment by Gael-de-Sailly** [comment]
#392 
En principe on peut maintenant changer le `chunksize` sans encombre, mais rien n'impose de le faire tout de suite.

Il faut changer ça dans le fichier `map_meta.txt`, qui se trouve dans le dossier du monde. Le changer juste dans `minetest.conf` ne suffit pas (normalement ça n'est effectif que pour les nouveaux mondes).

Problème possible : les anciens chunks de 80x80 et les nouveaux de 32x32 ou 48x48 vont se recouper différamment. Certains nouveaux chunks vont être à cheval sur une zone générée et une zone non générée, et certaines parties vont donc être regénérées, tout ce qui s'y trouve sera perdu. Mais je ne pense pas qu'il puisse y avoir des constructions à moins de 32 blocs d'une zone non générée. Par contre il peut y avoir des bugs de chunks, pas trop méchants je pense (style des bouts d'arbre flottants).

**Comment by Ombridride** [comment]
C'est pour ça que j'aimerais des tests approfondit, il faut donc refaire des tests.

1) Générer des bouts de maps en chuncksize 4
2) Se reconnecter au même monde avec un chuncksize plus petit de 2
3) Analyser ce qu'il ce produit

Il faudrait poster des screenshots en cas de problème

**Comment by Cyberpangolin** [comment]
ok, je merge chlorine (au cas ou...) et je testerai en masse prochainement.

**Comment by Cyberpangolin** [comment]
Meru fait toujours des bizarreries...
en chuncksize de 3....
![capture du 2016-02-19 19 13 16](https://cloud.githubusercontent.com/assets/12512762/13184618/4413ab9c-d73d-11e5-9e4b-2a3039f3615e.png)

**Comment by Gael-de-Sailly** [comment]
Meru, je ne l'ai pas corrigé, puisqu'on l'utilisera sous forme de schematics. Mais c'est vrai qu'au niveau hardcodé, c'est le pire.

**Comment by Cyberpangolin** [comment]
okay ;). Je continuerai de prospecter la semaine prochaine, j ai japan impact ce week-end :P

**Comment by Ombridride** [comment]
Pourrais tu corriger meru mountains sur la meme ligné, il n'est pas exclu qu'un jour on l'ajoute sur l'un de nos serveurs de façon "normal", s'il te plait ?

**Comment by LeMagnesium** [comment]
@Cyberpangolin Il faut aussi blâmer la limitation que j'ai mise à meru sur chlorine.
Il semblerait que ce dernier augmente la taille du meru à cause du changement de taille de chunck. (J'avais déjà vu des coupures brutales du premier meru, sur des zones très éloignées du centre de la montagne, c'est normal du point de vue du code)

**Comment by Ombridride** [comment]
Up @Gael-de-Sailly, pourrais-tu fix meru mountain s'il te plait ? tu es le seul compétent en ce qui concerne les modifications lié au mapgen :)

**Comment by Gael-de-Sailly** [comment]
pas le temps cette semaine, à part peut-être demain aprem mais c'est peu probable.

**Comment by Cyberpangolin** [comment]
Après un grand moment de balade, je peux confirmer n'avoir repéré AUCUN bug susceptible d'altérer la map.

manque meru et à nous les générations sympa:)

**Comment by Gael-de-Sailly** [comment]
Vous pouvez vous occuper de meru, je ne serai à nouveau pas actif avant samedi.

**Comment by Cyberpangolin** [comment]
personellement ce serait volontiers mais je n'ai AUCUNE idée du correctif à apporter... qui peut prendre?

**Comment by LeMagnesium** [comment]
> personellement ce serait volontiers mais je n'ai AUCUNE idée du correctif à apporter... qui peut prendre?

La mapgen et moi ça fait 3. J'ai regardé le code, c'est du mandarin pour moi...

**Comment by Ombridride** [comment]
Il me semble que @Gael-de-Sailly avait aussi dit que le code le dépassait... je pense qu'il va falloir traduire le ticket et pinger paramat

**Comment by Cyberpangolin** [comment]
Du coup, on arriverait pas, en attendant, à activer déjà l'ensemble du nouveau code avec un chunksize de 3, quitte à renoncer provisoirement à meru?

**Comment by Gael-de-Sailly** [comment]
@Ombridride C'était vendredi soir, j'étais fatigué, j'avais dit que je verrais le lendemain, puis j'ai oublié, puis j'ai plus eu le temps.
Tu n'avais pas dit que meru ne serait pas activé directement ?

**Comment by Ombridride** [comment]
@Gael-de-Sailly No problem, you do it when you can

The answer of your question is here https://github.com/MinetestForFun/server-minetestforfun/issues/380#issuecomment-186397534 :)

**Comment by LeMagnesium** [comment]
> Tu n'avais pas dit que meru ne serait pas activé directement ?

C'est complètement valide. Jamais meru ne sera activé sur Classic (sauf nouvelle génération de map). La méthode envisagée pour le moment c'est l'importation du schematic du mont meru via python-minetest.

**Comment by Gael-de-Sailly** [comment]
b40a199

**Comment by Gael-de-Sailly** [comment]
and submitted pull request: paramat/meru#3

**Comment by Gael-de-Sailly** [comment]
Is the mod meru disabled in MFF classic?

**Comment by Ombridride** [comment]
Thank you @Gael-de-Sailly !

The goal of the meru mountain is to activate it and reduce the "spawn" rate, we only want ~10 meru mountain on the server

I will ad 1 or 2 in the already explored areas in this purpose

**Comment by LeMagnesium** [comment]
> ~10 meru mountain on the server.

Do you realize how much pain it is to simply import one?! o_o
Well, if the mod is enabled, they'll be generated anyway, but damn.
(by the way I'm going to update Meru's issue)

**Comment by Gael-de-Sailly** [comment]
x size: 2⁷
y size: 2¹¹
z size: 2⁷
Volume: 2²⁵, or 33 554 432 nodes.

And yes we can make thinner schematics for the top, but we won't be below 10 million nodes. Just remember the lag that happened when you moved the old admin castle (110 000 nodes), or Cyberpangolin's Tour Eiffel (around 1 million, mostly air).

`meru` do not have spawn rate: only one mountain is generated in the world.

**Comment by HybridDog** [comment]
You don't use the .we schematics, do you?

**Comment by ObaniGemini** [comment]
No, we use python-minetest by @LeMagnesium

**Comment by Ombridride** [comment]
@Gael-de-Sailly what ou said about the mru mountain is interresting, so if we moved the generated area to a unexplored area, then generate it, only one meru mountain will spanw in the server ? After all, I think it can be enough, can you confirm what you said ?

**Comment by Gael-de-Sailly** [comment]
It generates only one mountain in the world (the location is randomly chosen into the generated area), except if youchange the generating area once the mountain is fully generated, so a second one will appear. The relative location of both mountains in their generated areas would be the same: example if you've set the generated area from `-1000` to `1000` in both directions and the first mountain spawns on `464;235`, if you move the generated area +1000 nodes X and +1000 nodes Z, the second mountain will spawn on `1464;1235`.

**Comment by Ombridride** [comment]
Ok, if I understand well, we can tweak a little the mod to have only 1 Meru mountain on the server, in this position : "-170, y, -465"
This position is already generated, so if you activate the generation of the meru mountain in this area then i do a /deleteblock on this chunk, the meru will be generated ?

Im right ? If yes, can you tweak the meru mod and activate it with this position ?

**Comment by Gael-de-Sailly** [comment]
We're leaving the topic that was about mapgen speed. Discussion moved on #410.

**Comment by Ombridride** [comment]
Yes, thank you @Gael-de-Sailly.

For the modified chunksize on the mapgen : 
https://github.com/MinetestForFun/server-minetestforfun/commit/04708354bd5d4765848fb64e347e86fb9b6658db
And i also tweaked the mapmeta.txt file tu chunksize 3, we need to see the next reboot :)

**Comment by Ombridride** [comment]
For information, our new map_meta.txt file : 

```
chunksize = 3
mg_biome_np_heat = {
	flags = defaults
	lacunarity = 2
	octaves = 3
	offset = 50
	persistence = 0.5
	scale = 50
	seed = 5349
	spread = (500,500,500)
}
mg_biome_np_heat_blend = {
	flags = defaults
	lacunarity = 2
	octaves = 2
	offset = 0
	persistence = 1
	scale = 1.5
	seed = 13
	spread = (8,8,8)
}
mg_biome_np_humidity = {
	flags = defaults
	lacunarity = 2
	octaves = 3
	offset = 50
	persistence = 0.5
	scale = 50
	seed = 842
	spread = (500,500,500)
}
mg_biome_np_humidity_blend = {
	flags = defaults
	lacunarity = 2
	octaves = 2
	offset = 0
	persistence = 1
	scale = 1.5
	seed = 90003
	spread = (8,8,8)
}
mg_flags = trees, caves, dungeons, noflat, nolight
mg_name = singlenode
seed = 13107546752813893513
water_level = 1
[end_of_params]
```
