### ISSUE TITLE
Bug with class orbs

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#381]
Tested on the `crash server` :

When class orbs are aligned side by side, only one works (only one shows the class item that permits to change class).
So this forces the user to put them with some distance between them.

This works for horizontal and vertical lining up, but not diagonal

**Comment by Ombridride** [comment]
What ? i don't undertand, players can't put class orbs. Only the admin can.

And the orbs are all in an special building, so not near each orther...

**Comment by Cyberpangolin** [comment]
It happened on the Chlorine server -- should probably be fixed one day if someone makes a MFF-based server with a choice of class in a small building, but it's a very low priority issue.

**Comment by LeMagnesium** [comment]
It's nothing big, just check radii overlapping each other.
