### ISSUE TITLE
Player Detector tweak [mesecons]

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#382]
The player detector enables a player to take possession of it, for it only opens when he arrives.
I think it should work for many players : we should be abled to add *several* other players to the list.
Maybe can we use the code from `protector_redo` ?

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/9bcbb1c4e5b5bb7ccfee254d2563ebf317fdad57
Should be good enough. Efficient without much damage to the original code.

**Comment by ObaniGemini** [comment]
Thank you @LeMagnesium :)
@fabienwang, I think this should interest you ;)

**Comment by fabienwang** [comment]
Oh nice one @LeMagnesium thanks @ObaniGemini
