### ISSUE TITLE
Idea of use for this mod ?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#383]
Hey, I'm dropping this mod here https://forum.minetest.net/viewtopic.php?f=9&t=13897
I think it can be very useful, but I don't have any precise idea of for what it would be.

Let's drop possible uses !

**Comment by Ombridride** [comment]
Maybe we can use it, before we need to try it and check if :
- [ ] we can display only player to player / player to monster / monster to player damages
- [ ] how is calculated the armor reduction ? before or after the displayed number ?
- [ ] well codd or not / need to partially re-code it / totally re-code it

**Comment by LeMagnesium** [comment]
So far, my discoveries :
 - This mod is only programmed to display damages on players
 - It doesn't calculate the damages by itself, but uses the values given to all `on_hpchange` callbacks
 - We could try to code it so that mobs are also supported

**Comment by LeMagnesium** [comment]
If you ever want that mod, there it is : https://github.com/LeMagnesium/minetest-minetestforfun-server/commit/07af9dab90d520a1c0636d38d222ebca0c202e0e

**Comment by Ombridride** [comment]
This mod won't be added for some reasons(particles, only player to monsters damages displayed, etc...), I closed the issues.
