### ISSUE TITLE
falling sand on fences

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#386]
here is the setup:
|sand|
|anyblock|
|fence|

Break the "anyblock"
Surprise -> The sand starts falling but stays on the "falling" way

[bug.mp4.zip](https://github.com/MinetestForFun/server-minetestforfun/files/104824/bug.mp4.zip)

Attached: a short video for demonstration purpose

low priority, because nobody puts sand above fences and then let it fall (except me :P)

EDIT: maybe there already is a ticket, the gravel is affected too: https://www.youtube.com/watch?v=Rfqybs0O664

**Comment by LeMagnesium** [comment]
If it is a problem with fallling nodes, then no wonder that gravel is affected as well.

**Comment by Ombridride** [comment]
all falling nodes are affected, i already see this bug with gravel

**Comment by LeMagnesium** [comment]
Just so you know, it doesn't happen to me with 0.4.13-dev, so it is most likely fixed in Dev.

**Comment by LeMagnesium** [comment]
Alright, should fix it : https://github.com/MinetestForFun/server-minetestforfun/commit/cbff471338ac19deff896942459bfbcd2e8f5415

**Comment by ObaniGemini** [comment]
This happends also on markers.

**Comment by Ombridride** [comment]
@ObaniGemini create a new issue with a link to this issue, not an issue after a issue solved an reopened it........................................

**Comment by ObaniGemini** [comment]
Why that ? it's the same issue with another block, it's easier to understand where do the problem comes from imo, without flooding of issues.

**Comment by Ombridride** [comment]
https://en.wikipedia.org/wiki/ISO_9000
http://www.iso.org/iso/catalogue_detail.htm?csnumber=16537

Reopen an issue please ;)
