### ISSUE TITLE
something eats tons of ressources in the serv

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#387]
Look at these grafana screens: we have a full reboot at 4:32

As you can see, the server seems to be at the limit of overload until 5:10, so during 40 minuts, and then sticks at 30-40% every time WITHOUT ANY PLAYER.

![capture du 2016-01-28 06 54 31](https://cloud.githubusercontent.com/assets/12512762/12636345/574233d6-c58c-11e5-9ae1-f34140ab0031.png)

For comparison purpose, to make sure all servers start one after the other, I need less than 10 seconds to start one on my dev server. Then, idle, all of my servers need 1.3 to 2% of the cpu time, and it's supposed to be much slower than our main server (laptop with a core i5 vs server with Xeon(?)), so all servers running should probably take less than 5% permanently.

My conclusion is that: OR all our programs are totally optimized and the server is really slower than what is paid for, OR something (the mapper?) is eating tons and tons of resources and should be really improved. I would prefer to see more available resources for map generation, by example :P

@Ombridride I take the freedom to assign it to you, as it's your server and you are probably the only one who can launch top to see what happens ;)

**Comment by Ombridride** [comment]
C'est normal, les mtwebmapper ont été arrêté en attendant le fix du REDIS, le gros bond de CPU que tu vois c'est le mtseeder tous les jousr a 4h30, rien n'est anormal :)
