### ISSUE TITLE
Respawn of tree

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#389]
voir derrière l'usine de @Cyberpangolin (152,9,-283).

J'ai planté des sapling de pommiers un peut trop proche de la route mais maintenant il m'est impossible de les tailler, ils respawnent entièrement au bout de 5 minutes environs (j'ai pas calculé)

![screenshot_20160128_232935](https://cloud.githubusercontent.com/assets/11613522/12660989/58962ee6-c617-11e5-83cc-d779c9c223e0.png)
![screenshot_20160128_232937](https://cloud.githubusercontent.com/assets/11613522/12660990/589ad2b6-c617-11e5-81c1-a15bb2714c62.png)

**Comment by Ombridride** [comment]
Pourrais tu détailler davantage ton problème, pourquoi "respawn" t ils ? tu dig les feuilles et elles ne disparaissent pas ?

**Comment by crabman77** [comment]
c'est le mapper, le serveur décharge le chunk puis quand on reviens il le recharge mais la map n'a pas été update par le mapper.

**Comment by Ombridride** [comment]
je ne comprend pas, tu parles du bug REDIS ou d'autre chose ?

**Comment by crabman77** [comment]
la map était encore down, mais les logs n'indiquaient rien cette fois, @gravgun viens de le reboot.

**Comment by farfadet46** [comment]
ça m'a fait la même chose sur la glace, j'ai dig un bon millier de nodes et lorsque je reviens, les nodes sont toujours là = 1000 blocs de glaces dans mon inventaire et 1000 bloc de glace sur l'eau :/
= Blocs illimité :/

**Comment by LeMagnesium** [comment]
Il semble que quelque chose, probablement le mapper, soit en train de manipuler la map, et empêche les chuncks d'êtres actualisées. Il faudra essayer de nouveau avec les mapper down.

**Comment by Ombridride** [comment]
@farfadet46 Nous avons besoin de savoir la date à laquelle tu as fait ça et la date à laquelle tu as remarqué le rollback, les informations que tu nous donnes ne nous aide pas jusque là ...

**Comment by Cyberpangolin** [comment]
Je note pour ma part qu'une grande partie de mon aménagement au niveau du petit pont a été rollbackée également. J'ai bossé dessus jeudi soir, nous sommes samedi et je viens de voir les dégâts. les pertes: quelques juncus, 60 à 70 super glow glass, et 3 heures de jeu :/. Bizarrement une partie des modifications est préservée, mais de loin pas tout...
J'ai refait quelques modifs simples pour voir si elles restent ou disparaissent.

**Comment by Ombridride** [comment]
Normalement elles ne disparaitront plus, je vais checker les logs voir si nous avons encore des bugs REDIS

**Comment by Ombridride** [comment]
So, I checked the logs for REDIS errors and i don't see errors anymore since the last tweak OS side i applied
![monitoring](http://i.imgur.com/Y2m7CFb.png)

I closed this issue, it's done :)
