### ISSUE TITLE
Pathfinding here ! Update mobs redo

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#393]
https://forum.minetest.net/viewtopic.php?f=11&t=9917&start=575#p206802

**Comment by Ombridride** [comment]
Thank you @crabman77 

Closed the issue

**Comment by ObaniGemini** [comment]
Pathfinding works a strange way but can work.
It works nicely to climb structures but not really to dodge a simple thing blocking the way.
