### ISSUE TITLE
last merge create high memory usage and swap usage

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#394]
![screenshot at 2016-02-12 06 27 52](https://cloud.githubusercontent.com/assets/7189389/12999657/d0377410-d151-11e5-8991-36dc38d683d4.png)
![screenshot at 2016-02-12 06 18 24](https://cloud.githubusercontent.com/assets/7189389/12999557/f3ea09aa-d150-11e5-81a1-d6f975319a94.png)

**Comment by ObaniGemini** [comment]
It might come from the skyblock, the bugfix of the furnaces not cooking while chunk unloaded seems to create huge lags (tested with @cessna151 )

**Comment by Ombridride** [comment]
18h --> daily reboot :
![graph](https://cloud.githubusercontent.com/assets/8619233/13003851/180a6934-d178-11e5-92c6-7ea8744822c2.png)

After the daily reboot the RAM usage is good.

Need to wait an another night to see what is happening, for me, the merged as surely encounter a problem, but after the daily reboot, the server and the Minetest servers has booted correctly.

I will wait this night, and see the logs

**Comment by cessna151** [comment]
Is swap memory the same as page file memory in Windows?

**Comment by Ombridride** [comment]
Yes, swap = pagefile

But the pagefile speed/features/performance are far from the swap speed/features/performance, because Microsoft use a "FAT" filesystem type and they don't use a special filesystem type made for this kind of thing like GNU/Linux & other Unix/BSD based Operating system use.
For a little reference, ~ the best performance Microsoft pagefile can do is ~ the worse the swap can do.

**Comment by LeMagnesium** [comment]
It is still unknown what caused this, although it seems to be fixed. Should we close then?

**Comment by Ombridride** [comment]
La cause est simple, lors du reboot du serveur, tous les objets dans les furnace étaient déjà dans les furnaces depuis longtemps, résultat, au reboot tous les furnaces du skyblock (3000+) ce sont activés en meme temps pour cuir leur contenu, il en a résulté l'utilisation de la RAM que tu peux voir.
Bref, le contenu de tous les furnaces étant maintenant vide, le problème est résolu.
