### ISSUE TITLE
aspen saplings are unbreakable

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#396]
tested on the chlorine server:
If I place an aspen sapling, I am totally unable to remove it.

**Comment by Gael-de-Sailly** [comment]
that's true. Some informations are missing for the aspen sapling.

[Normal sapling definition](https://github.com/MinetestForFun/server-minetestforfun/blob/22b863cf41bdb5a98906c07a4a1f9265a9fc1b14/minetestforfun_game/mods/default/nodes.lua#L556-L574)
[Aspen sapling definition](https://github.com/MinetestForFun/server-minetestforfun/blob/22b863cf41bdb5a98906c07a4a1f9265a9fc1b14/minetestforfun_game/mods/default/nodes.lua#L871-L880)

Fixing now.

**Comment by Gael-de-Sailly** [comment]
66c5524

**Comment by Ombridride** [comment]
Thank you @Gael-de-Sailly
