### ISSUE TITLE
areas in areas.

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#398]
If 2 people (or more) own a same area, sometimes one of them wants to protect a specific thing into the area, but he cannot.
Typically, I think about the spawn island, where a lot of people are allowed to build, but none can protect his building by himself (maybe except Calinou, because he is the first on the list).

I conclude that the area mod should be improved by checking all lines if the player's name exist, instead only checking the first line and say "nope, you can't protect that area, it's owned by (insert_a_name_here)". 

@Ombridride now you are back to 14 issues, don't cry :)

**Comment by Ombridride** [comment]
@crabman77 

> pour area ont va pas pouvoir faire grand chose, car si quelqu'un a fait une area collée au spawn, si cyber veut faire une area qui chevauche les 2, il aura le droit car il est dans celle du spawn et empietera dans celle de l'autre

**Comment by crabman77** [comment]
solution à tester https://github.com/MinetestForFun/server-minetestforfun/commit/9b75c37a8f0944b2b7a6644da11866cef5309a79

**Comment by Ombridride** [comment]
Quelqu'un peut tester ? En serveurs dev peut etre ?

**Comment by LeMagnesium** [comment]
Je peux confirmer que cela fonctionne (serveur Chlorine de @Cyberpangolin)

**Comment by Ombridride** [comment]
Parfait, le commit peut-il être ajouté au serveur creative ? ensuite on pourra clôturer l'issue

**Comment by crabman77** [comment]
mergé sur classic https://github.com/MinetestForFun/server-minetestforfun/commit/abb1e093e0ca83c415626679c74b47adec257148

creative https://github.com/MinetestForFun/server-minetestforfun-creative/commit/892ee150dca7398445041feee9faba6c342060b0
