### ISSUE TITLE
Add jumping mod back

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#401]
*Jumping* mod was removed because not working on 0.4.13 stable.
The fact is it was working, we just needed to put higher values (for example, 10 intead of 0.10). I could experience it on VanessaE's Dreambuilder server and @crabman77 confirmed me that it was working.
Could we add it back and find good values to it ?

Also, could we add it to the **Creative** server ?
(nice for races and traps)

**Comment by Ombridride** [comment]
It won't be added on the HG server

But yes, it's a good thing to re-add it to the Classic and Creative server :)

**Comment by ObaniGemini** [comment]
Edited the post

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/497fdfef65c025c163505c411da8e52e32d9c433
And https://github.com/MinetestForFun/server-minetestforfun-creative/commit/6af5afe81dab9967c631a7acb2d58dc865e6cfe3
