### ISSUE TITLE
replacment for moretrees bushes

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#402]
Let's discuss about this ? 
https://forum.minetest.net/viewtopic.php?f=9&t=14068&view=unread#unread

**Comment by Cyberpangolin** [comment]
:-1: 
I REALLY prefer the ones we have actually

**Comment by ObaniGemini** [comment]
I say no, it just looks like leaves with colored pixels. I would say yes if it was generated with trees.
If the code is better, then just use this code but don't change the looking of actual berry bush. I think they could look better but this mod is not IMO a good alternative
:-1:

**Comment by LeMagnesium** [comment]
I'm not really in favour of this. We already have perfectly operational bushes, which have been there for as long as MFF has existed, and they have a nicer look than those (although I like the pixel-art style of those bushes).
I think we should stick with what we have...

**Comment by Ombridride** [comment]
Ok, i closed the issue, it was only opened for proposal try :)

The actual moretrees bushes are very circular, so it's not very beautiful is my point of view, but it's just my point of view, if everyone agreed in the fact that the actual bushes are good, it's good for me :)
