### ISSUE TITLE
nouvelle api pour les  doors/doors3 , besoin de refaire les textures

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#404]
voila le tar.gz du mod avec la nouvelle api de doors avec nos portes en 2/3 nodes intégrées et le système de double porte. [new_doors.tar.gz](https://github.com/MinetestForFun/server-minetestforfun/files/155248/new_doors.tar.gz)

il faut refaire 9 textures adaptées au mesh.
l'archive contient les anciennes textures pour le modèle.

- [x] faire les textures
- [x] debug le sand qui peut tomber dans la porte 3 nodes

**Comment by farfadet46** [comment]
il y a un petit bug on peut faire tomber du sable dans la porte :)
(j'ai parcouru le code ils fabrique un node spécial invisible au sol du mesh ?
j'ai rien compris :)
![screenshot_20160302_183400](https://cloud.githubusercontent.com/assets/11613522/13468950/81bc5fea-e0a5-11e5-9ff4-634ce897b2d6.png)

**Comment by LeMagnesium** [comment]
> j'ai parcouru le code ils fabrique un node spécial invisible au sol du mesh ?

Le code place un node sur la moitié supérieure de la porte (le node étant la moitié inférieure) pour empêcher le placement d'autre nodes. Il faudrait si on utilise leur technique en placer deux.

**Comment by crabman77** [comment]
@LeMagnesium c'est fait mais ça ne fonctionne pas.

texture de la porte steel finie.
![door3_steel](https://cloud.githubusercontent.com/assets/7189389/13475712/b52d3948-e0c4-11e5-9348-4f6883e63db2.png)

**Comment by Ombridride** [comment]
Wow bravo, ça avance vite ! :)

**Comment by crabman77** [comment]
bon le seul hack dégueulasse pour corriger le bug du sand c'est de rajouter une exception pour le node "doors:hidden" dans falling coté serveur, ou peut être redéfinir "__builtin:falling_node".
ou les laisser trouver un fix :).

```
if bcn.name == "doors:hidden" then
	-- Create node and remove entity
	local np = {x=bcp.x, y=bcp.y+1, z=bcp.z}
	core.add_node(np, self.node)
	self.object:remove()
	return
end```

**Comment by Ombridride** [comment]
Je pense que le mieux c'est de traduire le ticket et de l'envoyer de leur côté, ils trouveront ou implémentaront une nouvelle solution plus propre

**Comment by LeMagnesium** [comment]
Si j'ai bien compris ce que tu dis crabman les falling tombent à travers le doors:hidden?
Mais alors le bug peut être reproduit avec MT Vanilla?

**Comment by crabman77** [comment]
oui, surement, le node n'est pas walkable alors ça passe dedans. Avec les portes 2 nodes le sand reste coincé dessus, on ne peut pas l'enlever car c'est une entité non pointable tant qu'il tombe, mais bisarement il ne descend pas sur le node.
ça doit être le même bug que Cyber à trouvé avec les fences.

le code de falling est vraiment bizarre, j'ai mis une exception pour le hidden pour qu'il entre dans la 1ère condition comme si c'était un walkable et le serveur à freeze/le disc grattait, le updatenode() qui n'allait pas, pourtant c'est le seul endroit ou le node est stoppé.

**Comment by farfadet46** [comment]
juste petite info, la cherry door ; la poigné est du mauvais coté non ? sur la capture de @crabman77 on la vois a droite alors que toutes les autres portes l'ont à gauche :/

**Comment by LeMagnesium** [comment]
@crabman77 As-tu commit tes modifications? Je voudrais pouvoir déboguer ces portes. Les portes de vanilla ne sont pas traversée par le sand, donc il y a dû y avoir une boulette quelque part.

**Comment by crabman77** [comment]
@farfadet46 non, la 1ère est à droite mais les autres sont à gauche car il y a une porte à gauche quand ont la place.
@LeMagnesium dans quel dépot? avec les PR en cours ça risque de faire des conflits.
Skyblock dans une branche alors?

**Comment by LeMagnesium** [comment]
Une branche, je ne t'ai pas répondu avant que tu ne le fasses mais c'était la bonne idée.

**Comment by crabman77** [comment]
Fixé https://github.com/MinetestForFun/server-minetestforfun/commit/67673f7fdc9c512306285379dc2cefd6a279d7b0
