### ISSUE TITLE
[roleplay] this mod interesting ?

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#405]
Is this mod interesting in your point of view ?
https://forum.minetest.net/viewtopic.php?f=11&t=14143&p=209314#p209108

**Comment by ObaniGemini** [comment]
:+1: 
a bit useless but :+1: 
(maybe a unified_inventory icon ?)

**Comment by LeMagnesium** [comment]
This was useless to put into a mod but... why not.

**Comment by Ombridride** [comment]
The idea is to add this mod on all of our servers with a generic command to sit/sleep, it's just for a roleplay purpose, the roleplay features are always "useless" if you thing about a gameplay way :)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/5b926f753c36e9a21aebac1d8641357af0ac463e
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/19ead1cb686513f7145147e4b761f14942737ad6
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/8f38855ac90a4eb5f625190c941d63152cee8ebe
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/970e020e3941e0403dd226de6a6c0068e0dfb04d
