### ISSUE TITLE
Doors + seed = ?

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#406]
![inbox message](http://i.imgur.com/dshnx1E.png)

Ce n'est peut etre pas fixable, le clique droit est peut etre utilisé pour une fonctionnalité exprès, après une exception est peut etre faisable pour permettre l'ouverture des portes avec en main les seeds ?

**Comment by farfadet46** [comment]
je pensais pas qu'il s'agissait d'un bug en fait :) pareil avec les coffres ;)

**Comment by crabman77** [comment]
il faut faire comme dans les doors justement, quand on place, si le node a un callback "on_rightclick" alors on l'utilise.
https://github.com/MinetestForFun/server-minetestforfun/blob/master/minetestforfun_game/mods/doors/init.lua#L42

à mettre dans la fonction "place_seed" de farming, ça évite de faire tout les items https://github.com/MinetestForFun/server-minetestforfun/blob/master/minetestforfun_game/mods/farming/init.lua#L430

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/f9c045edad296b2d41832f1952a810477642f530
It sould be enough.

**Comment by Ombridride** [comment]
#### More informations
Classic : https://github.com/MinetestForFun/server-minetestforfun/commit/bf269a6574f2bfcfbbffec06b7fd2ef4d04053fa
skyblock : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/e708f8d2667e83cf947d916737e3c3a83573e85d
Creative : https://github.com/MinetestForFun/server-minetestforfun-creative/commit/5fd60fea7f8341fdea3ae3e20201b41047cd2296
