### ISSUE TITLE
some dirt nodes are illuminating in caves ?

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#407]

**Comment by Ombridride** [comment]
I didn't understand, please provide description or at least a screenshot :)

**Comment by LeMagnesium** [comment]
I think this is an error of lua generation, one of the mods places dirt but doesn't update light, or does so and it bugs lighting. I'm not sure there will be a way to solve this in every case possible, Minetest's handling of lighting is widely known as buggy..

**Comment by ElementW** [comment]
@LeMagnesium You are wrong.

No, those light-emitting dirt and sand nodes are generated by `sea`'s `seaplants` and `seacoral` plants. Try it yourself: put water sources over the nodes and wait for sea plants to pop. There is however no way of harvesting them without them turning back to normal dirt or sand.

**Comment by Cyberpangolin** [comment]
I see two answers:
- Or the illuminated sand stops to bright if it doesn't detect any sea plant on it, like the leaves decay, but probably much slower.

- Or we give us a way to collect it. The effect could be nice.

**Comment by LeMagnesium** [comment]
> No, those light-emitting dirt and sand nodes are generated by sea's seaplants and seacoral plants

Oh. Then we're not talking about dirt. @farfadet46 please be precise.

> the illuminated sand stops to bright if it doesn't detect any sea plant on it

You can't modify a node's light_source value whilst in the game, not without using a VoxelManipulator, and it will only work on specific nodes.

I have a question though. What's the problem? We can't fix anything if we don't know what is requested to be fixed.

**Comment by Ombridride** [comment]
> I have a question though. What's the problem? We can't fix anything if we don't know what is requested to be fixed.

+1, not a problem is this point for me
