### ISSUE TITLE
Meru mountains

### ISSUE THREAD

**Issue by Gael-de-Sailly** [MinetestForFun/server-minetestforfun#410]
The `meru` mod places only one mountain in the world. It could be possible to tweak it to place several mountains, at custom positions. The question is: how many mountains? and where to place these mountains?

*@Ombridride wrote:*
>Ok, if I understand well, we can tweak a little the mod to have only 1 Meru mountain on the server, in this position : "-170, y, -465"
>This position is already generated, so if you activate the generation of the meru mountain in this area then i do a /deleteblock on this chunk, the meru will be generated ?

>Im right ? If yes, can you tweak the meru mod and activate it with this position ?

simply:
```
XMIN = -170
XMAX = -170
ZMIN = -465
ZMAX = -465
```
It should work with `/deleteblock` but you need to `/deleteblock` all air chunks above it too.

I would have preferred to set the mountain farther on an area on which we're sure that there isn't anyone that has built something. -170 ; 465 is not very far from jabali's house. I propose -640 ; -450. On the worldmap, the dry grass is not displayed correctly, that means that this area has not been explored since we added an alias for dry grass in August.

What do you think about it?

**Comment by Ombridride** [comment]
Ok for -640 ; -450, seesm good to me ! :)

I think you can do the tweaks and activate the Meru mountain, just before, we need to do a test in the dev server, to confirm it works, even if theorically it works :)

**Comment by Gael-de-Sailly** [comment]
but the mod is activated, isn't?
[world.mt](https://github.com/MinetestForFun/server-minetestforfun/blob/5b926f7/worlds/minetestforfun/world.mt#L31)
To generate just one mountain, juste change the 4 values [here](https://github.com/MinetestForFun/server-minetestforfun/blob/b40a199/mods/meru/init.lua#L5-L8). We can tweak it after to generate more mountains.

**Comment by Cyberpangolin** [comment]
It could be good to add a parameter to choose how much are generated.
By the way, good job @Gael-de-Sailly  :+1:

**Comment by Ombridride** [comment]
Apparently the mod is already activated, yes :S

Well, i committed the modifications : https://github.com/MinetestForFun/server-minetestforfun/commit/8f74c9f069507d9981a743d677d9051efd7ffe23

Can your confirm everything is good @Gael-de-Sailly ?
Well, just need to wait a in-dev test now.

**Comment by Cyberpangolin** [comment]
Will be tested on chlorine asap

**Comment by Gael-de-Sailly** [comment]
i'm very busy on weekdays, this time. I may reply quickly on the issue but I can't code.

**Comment by Cyberpangolin** [comment]
Tested, and approved, the generation in itself looks better.

PLEASE NOTE BEFORE APPLY:
**- it won't generate anything on already generated land.**
- the meru base is at 0 of height, so when it pops on an ocean, the whole mountain is on the water. A "simple workaround": get  the whole meru generation down of "insert max ocean depth here" blocks, so it looks anchored into the surrounding stone. 
- probably the easiest way to put some meru mountains on the server is to copy the mod 10 times, and set 10 coordinates of ungenerated land. of course those coordinates must stay secret :)

**Comment by Ombridride** [comment]
1) Yes, it's normal, we know it
2) Yes, it's normal, we know it
3) No, i don't think so. :) Anyway, we will only introduce 1 Meru mountain (for the moment), i will create an event about it and do a /deleteblock when the event begin, i think

**Comment by farfadet46** [comment]
event of lag ? XD

**Comment by Ombridride** [comment]
Just some seconds of lags before the event start ;)

**Comment by Ombridride** [comment]
#### MinetestForFun Classic
Le voici : http://xorhub.com/fr/evenement-montagne-meru/
Here is it : http://xorhub.com/en/meru-mountain-event/

**Comment by Cyberpangolin** [comment]
\o/

**Comment by farfadet46** [comment]
After event ; anybody can buil on it ?

**Comment by Ombridride** [comment]
Yes, if you want after or during the event you can build on/inside it, try to do something beautiful :)

**Comment by Gael-de-Sailly** [comment]
The meru base should be at y=-32, not at y=0. I think the mountain is generated below 0 but it's overriden by watershed. This could be solved by adding the `watershed` depend to meru but I don't think that's needed since we know that the mountain will not spawn on an ocean.

**Comment by Ombridride** [comment]
yes, im also thinking it's no needed

**Comment by ObaniGemini** [comment]
What about that ? https://forum.minetest.net/viewtopic.php?f=9&t=13389
(just dropping it here)

**Comment by Ombridride** [comment]
Oh yeah i see it, forget it :D

**Comment by Gael-de-Sailly** [comment]
Just finished to climb the mountain, that is exactly 2016 blocks height. In fact I won the event… because I was alone xD
![Screenshot](https://cloud.githubusercontent.com/assets/6905002/13717432/c4361b98-e7e1-11e5-998d-cabf493f3419.png)

**Comment by Ombridride** [comment]
Congratulation ! :)

**Comment by Cyberpangolin** [comment]
Oh me, I totally forgot it was already yesterday. Sorry then :(

**Comment by Ombridride** [comment]
@Cyberpangolin i just need a proof you reach the top of the Meru mountain and you will win 3 ultimate class items of your choice (proof = screenshot or video)

**Comment by farfadet46** [comment]
okay it's too easy now ;)
![screenshot_20160315_131730](https://cloud.githubusercontent.com/assets/11613522/13777559/2be66cf8-eab1-11e5-8944-aa8bc4d8121d.png)

**Comment by Ombridride** [comment]
#### Vainqueurs
- @Gael-de-Sailly 
- Uraza
- eZam
- @farfadet46 

#### Récompenses
- [ ] @Gael-de-Sailly 
- [x] Uraza (Torse et Bouclier en Black Mithril + Epée en sang de DM)
- [x] eZam (Torse et Jambières en Hardened Leather + Minotaur Horn improved Bow)
- [ ] @farfadet46

**Comment by Ombridride** [comment]
Finished : http://xorhub.com/fr/termine-evenement-montagne-meru/
