### ISSUE TITLE
need more color for large bag ;)

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#411]
large bag is only red can we add a craft to make new colors ?

**Comment by Cyberpangolin** [comment]
good idea for a better organization :+1:

**Comment by Ombridride** [comment]
Good idea ! 3 more colors should be enough

**Comment by LeMagnesium** [comment]
> Good idea ! 3 more colors should be enough

This is how you end up with thousands of stick of the same color. Just saying.
Easily doable, it's entirely useless in my opinion.

**Comment by Ombridride** [comment]
Not useless, try to understand a little the players needs. They want to arrange they items with different bag colors, it's smart ;)

**Comment by Ombridride** [comment]
Done https://github.com/MinetestForFun/server-minetestforfun/commit/88d71e9510077e2c0fc0d25f4fca9cffeed5327d

**Comment by farfadet46** [comment]
we can't make colored bag :/ the craft is missing ?

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/c63b13ba85114cb265cbb63586d1a6abcb031d14
