### ISSUE TITLE
[Boss] Mese Dragon and its Room/Arena

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#414]
This post is about implementing the mese boss from not so simple mobs in MinetestForFun Classic server.
I made with the help of discodlm57 an arena in the MinetestForFun Creative server

![arena_room_top](https://lut.im/DNAlVkWT7m/hROcZeQT7ujWAe7i.png)
![arena_room_inside](https://lut.im/iFqIH7wDFZ/UJTMjRifQ4xHj9cB.png)
![arena_room_inside02](https://lut.im/YD6fvpBbZ4/bjDptUXUqJO6MLLh.png)
![arena_room_outside](https://lut.im/r6BPk8sBuj/7LSHbAoSJlo264S5.png)

There would be probably mese monster spawners on the high areas and lava slimes spawners on the lava area.
Location on creative : (540, 120, 100)

**Comment by Ombridride** [comment]
Thanks very much to you two ! :)
I'm working on the Mese Dragon Boss, and i will post soon my code, unfortunately I need a good internet connection to commit it and it's really not the case currently... (not in my home this week)

**Comment by farfadet46** [comment]
I'm workin on a new "Mese Dragon boss"
![capture](https://cloud.githubusercontent.com/assets/11613522/13614864/cd810814-e572-11e5-9f67-108197fb489d.PNG)

**Comment by Ombridride** [comment]
Good beginning !

**Comment by farfadet46** [comment]
et bien ça y est le rigging est fini pour ce monstre 
#YEAH-MEC !
![mese monster](https://cloud.githubusercontent.com/assets/11613522/13617032/ef021708-e57c-11e5-9de1-9d71e62b1355.PNG)

**Comment by Ombridride** [comment]
Ahah, il est achevé ducoup ou tu comptes rajouter des éléments genre pattes/ailes ?

**Comment by farfadet46** [comment]
le modèle est achevé après a toi de me dire si tu veut des pattes / ailes.
il faut me donner aussi les animation a lui faire...
 -ouvrir la gueule pour lancer des boules de feu ?

**Comment by ObaniGemini** [comment]
Il faut une animation de morsure en se baissant et une animation de marche/rampements au moins
Après je vais faire un son pour la mort du boss ou son apparition en fonction du possible.

**Comment by farfadet46** [comment]
quelle est sa taille par rapport au joueur ?

**Comment by ObaniGemini** [comment]
3/4 fois la taille du joueur.

**Comment by farfadet46** [comment]
ok le perso fait a peut près la taille de la tête du coup.
Avant de m'attaquer a l'animation ; dois-je lui ajouter des ailes / pieds ?

**Comment by ObaniGemini** [comment]
Je ne pense pas je le trouve très beau comme il est actuellement.
Au niveau des textures, j'aime beaucoup la façon dont elles sont agencées, mais serait-il possible de les rendre un peu plus sombres et de rendre la teinte plus orangée ? Sinon donnes les textures que tu utilises pour qu'on puisse modifier un peu :)

**Comment by farfadet46** [comment]
Pour la texture c'est forcement a retravailler.
je m'attaque a l'animation ce soir.

**Comment by ObaniGemini** [comment]
L'absence d'yeux donne un vrai côté totem et angoissant. Je vais essayer de retravailler cette partie des autres textures de mobs :)

**Comment by farfadet46** [comment]
pour la texture hesite pas ;) par contre il existe déjà un monstre de mese du coup celui si pourrai être le "MEZE" non ?

**Comment by ObaniGemini** [comment]
@farfadet46 : non car ce monstre est le boss, qui plus est le boss final pour l'instant :)
Il y aura bien des mese monsters dans la pièce mais ils feront office de "minions"

**Comment by Ombridride** [comment]
@ObaniGemini a des bonnes idées mais n'est pas notre directeur artistique, tout le monde peut donner son avis, par conséquent ne part pas tête baissé sur des idées @farfadet46 :)

Pour la taille je dirais plutot 2 à 3 fois maximum par rapport à la taille du joueur, @ObaniGemini ne réalise pas à quel point avoir une hitbox compatible avec le modèle est difficile, et plus le modèle est grand, plus la hitbox devient n'importe quoi...

Pour les animations, il faut une animation d'attaque de corps à corps, et une d'attaque à distance, en effet le boss attaquera à distance si le joueur est à distance, et au corps à corps si le joueur est à portée de griffe/morsure. Après à toi de voir ce que tu souhaites lui faire faire, personnellement je pense que séparé les deux animations différente serait une bonne chose, comme un coup de griffe au corps à corps et la gueule ouverte en avant pour les attaques à distance (il crachera du mese : boule de mese "enflammé", ou gros pic de mese "enflammé")

La taille de la tete me parait bonne, pour les pieds, ça ne me semble pas une obligation absolu, parcontre les ailes me semble obligatoire, c'est le cliché même du dragon :)

je suis contre l'orangé proposé, c'est un dragon en mese, sa couleur doit être mese/jaune pour moi.

Les yeux ne font pas partie du modèle mais font partie de la texture, ils seront donc à faire lors de la texturisation

Ne l'appel surtout pas "meze", ce boss s'appellera "Mese Dragon" ;)

Les "Mese Monsters" seront une sorte de "bébé dragon" tandis que celui-ci sera la mère, dans l'idée scénaristique de la salle du boss, donc il y aura aussi des Mese Monsters pour l'accompagner

J'espère qu'il y aura d'autres avis écris ici sur ce que les joueurs attendent de voir / veulent ajouter à Minetest, tout avis est intéressant à avoir ! ;)

@Cyberpangolin @paly2 @Gael-de-Sailly @Ataron @crabman77 @LeMagnesium @ElementW

**Comment by ObaniGemini** [comment]
@Ombridride : pour la taille je me réfère juste au modèle de base, qui avait une hitbox de 2 mais une taille de 4/5, pareil pour les mouvements.
Pour l'orangé, je ne parlais pas d'orange, c'est juste que la texture actuelle est beaucoup trop saturée, le jaune est fade.

Les ailes ne me semblent pas être une bonne idée car le dragon a déjà des bras.
Aussi, les plus gros dragons ne volent pas tout le temps, je le verrais ici plutôt comme un grand "golem", et il serait beaucoup plus imposant et impressionant en rampant comme sur le modèle actuel de @farfadet46 qu'avec un fatras d'ailes inutile.

**Comment by Ombridride** [comment]
@ObaniGemini la hitbox de base est à chié, je l'ai testé, c'est n'importe quoi =)

Les ailes peuvent etre une extensions des bras, c'est d'ailleurs souvent le cas chez le dragon lambda

Les ailes des dragons ne sont jamais utilisé dans les jeux vidéos, c'est pas pour autant que ça ne donne ce côté fantaisie agréable :p

**Comment by farfadet46** [comment]
les ailes peuvent ne pas être sur les bras/jambes exemple de dessin d'un amis https://twitter.com/ThomasFrick/status/707988838367547392 il a placé des ailes au dessus des bras.

en effet plus j'aurais de retour, commentaires plus facile la création sera ;)

**Comment by farfadet46** [comment]
le B3D fait 644Ko (je suis dans les clous)

voici le 7zip du vilain pas beau
https://up1.ca/#o-hQOzcpSIhF_GooesIU8g
contenu:
-fichier source .blend
-fichier texture .png
-fichier .B3D

**Comment by farfadet46** [comment]
petit test avec des ailes a vos commentaires ;)
![capture](https://cloud.githubusercontent.com/assets/11613522/13703364/d1640d8a-e795-11e5-83b8-a0b31b1a134b.PNG)

**Comment by Ombridride** [comment]
Je trouve ça très bien fait, la forme de l'aile ce prendra avec la texture (transparence) dans l'idée je suppose ?

**Comment by farfadet46** [comment]
#Toutafé ;)

**Comment by Ombridride** [comment]
Parfait, peux-tu nous transmettre une texture "exemple" pour que nous puissions la retoucher et comprendre ou sont tel ou tel partie du corps ?

**Comment by farfadet46** [comment]
je bosse sur un meilleur dépliage UV (actuellement beaucoup de faces se superposent) sinon dans le 7zip tu peut trouver la texture (si l'import ce fait urgent)

**Comment by Cyberpangolin** [comment]
Très joli monstre, il danse bien :dancer: 

du moment qu'il a des ailes, c'est imaginable qu'il puisse s'envoler (style comme le saut des autres mobs mais en tweakant la physique pour qu'il redescende lentement)?
Et du coup, il pourrait faire du corps à corps tout le temps mais cracher son feu uniquement en vol? Comme ça ça donnerait une occasion au joueur de se mettre à l'abri si bébé prend son envol

**Comment by farfadet46** [comment]
vouala le 7zip complet (avec la texture): 
https://up1.ca/#SSEria3ZOXGR-r49sas_mA
![dragonaile](https://cloud.githubusercontent.com/assets/11613522/13966359/4e689d16-f072-11e5-860a-0dde4a5034c2.png)
il est bien bien moche maintenant XD
![capture](https://cloud.githubusercontent.com/assets/11613522/13966398/87f87312-f072-11e5-8c84-f71c360f37b4.PNG)

**Comment by ObaniGemini** [comment]
Parfait je pense qu'on va pas trop le modifier de l'original :)

**Comment by farfadet46** [comment]
ok on me presse pour sortir le bébé et vl'a un mois qu'il traine sur l'internet :/

des nouveauté ?

**Comment by Ombridride** [comment]
Je me suis donné cette mission, mais je manque de temps et d'énergie en ce moment, je vais tenter de finir mes fichiers a moitié terminé du boss

**Comment by Vault-Boy-111** [comment]
Looks amazing so far good job... should be more yellow though

**Comment by Ombridride** [comment]
My work is pushed, @farfadet46 i need you in this commit : https://github.com/MinetestForFun/server-minetestforfun/commit/0f40f11030c4d4fcf18ccb1f7e2d961586d1d240 (answer my comments about animation & textures)

**Comment by farfadet46** [comment]
new mese_dragon.b3d (in zip with my texture)

We need a new animation for attack ?

[mese_dragon.zip](https://github.com/MinetestForFun/server-minetestforfun/files/251815/mese_dragon.zip)

**Comment by Ombridride** [comment]
New commit about the **Mese Dragon** https://github.com/MinetestForFun/server-minetestforfun/commit/d6102fdbb9ef29240bdd855cc936994699d1a697

**Comment by Vault-Boy-111** [comment]
blender correct?

**Comment by Ombridride** [comment]
Up, I will try to add the **Boss room** this week-end (before the HG arenas)

**Comment by Ombridride** [comment]
Room on the classic map :

Shortcut available at spawn :
![](http://i.imgur.com/bYN6jrQ.png)

The room is empty currently, I will fill it later !

**Comment by farfadet46** [comment]
there is no "return back to the spawn" crystal ?

**Comment by Ombridride** [comment]
No return crystal, like for the PumpKing, you need to use /spawn or /home

This spawn crystals wasn't made to be there definitely, but now it's the case... (for simplicity purpose)

**Comment by ObaniGemini** [comment]
I suggest I and @Ombridride (and whoever wants to join us) do the implementation in the week, to have this task finished. I don't think it's really hard but it's time to spend. If we don't do it quickly, we'll forget it.

**Comment by Ombridride** [comment]
I agree, the last thing we need to do :
- [ ] Mese Monster spawning node (need to create it)
- [ ] Mese Dragon spawning node (need to create it)
- [ ] Mese Dragon stats (need balance and some tests)
- [ ] The Mese Dragon size need to fit the hitbox, also the size need to be set (tall, but not too tall)

**Comment by ObaniGemini** [comment]
I think mese monster spawning node is provided by mobs redo actually.

For the Mese Dragon fireball texture, can you describe the mese dragon action for we see how it should look ?

**Comment by Ombridride** [comment]
Mese dragon attacks :
if the player is near "claw hit"
else (if player not near) "spits fireball"

The Mese Dragon Fireball should be just the DM Fireball but with mese colors, or you can totally redo it, it's your choice

**Comment by Ombridride** [comment]
La plateforme est trop basse et devrait etre réhaussé d'un carré :
![](http://i.imgur.com/Lz5qU4V.png)

**Comment by Ombridride** [comment]
Ok, fixed

**Comment by HybridDog** [comment]
>The Mese Dragon Fireball should be just the DM Fireball but with mese [colours], or you can totally redo it, it's your choice

l did sound for generating the fireball.
https://github.com/HybridDog/mobs/commit/2fdcd61b95059ae885914909e097bda73cb83c9c?w=1
