### ISSUE TITLE
Remove some skins from u_skins

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#415]
Actually our u_skins database contains 16*32+9 skins which means... **WOW**

#### 521 skins + their previews

I think it's a bit too much for a server like ours. Also, we have the full u_skins database, which is something launched on 2013/2012, and mostly filled with community members unskilled playing with gimp (including me at the time). So I think there is much garbage we could remove for now.

- [x] Reach a value of 50 skins https://github.com/MinetestForFun/server-minetestforfun/commit/5079f3c35d2387a6f33d129a6e91f8877ff2dcf1

**Comment by Ombridride** [comment]
+1 good idea
But it's a big task, hope someone will take it :)

**Comment by ObaniGemini** [comment]
No need to do all of it at once :)

**Comment by ezamlinux** [comment]
Currently 399 Skins (removing ugly (in my opinion), Minecraft reference, duplicate ...) For the rest, I proposed deleting the references to other games / anime (FNAF, Pokemon Adventure Time ...)

I also replace the default by Sam II (character_3) 
and corrected the name of some skins (eg. Red Yoshi, who displayed an error message)

**Comment by ElementW** [comment]
Just measured `u_skins`' RAM usage... (see [Making-the-subgame-more-lightweight](https://github.com/MinetestForFun/server-minetestforfun/wiki/Making-the-subgame-more-lightweight))

73 MB. Too big for skins.

**Comment by Ombridride** [comment]
Well, i was wondering.... And if we just merged the "MFF_skyblock"  u_skins on the MFF_Classic ? it's a 10 skins pack, it's propably enough ?

**Comment by Cyberpangolin** [comment]
I would be happy to keep more diversity on the serv. And my own skin, too (it's under WTFPL, maybe I never told anyone.)

**Comment by ObaniGemini** [comment]
30/40 skins is a good number, but 30 is too light for a diversified server imo

**Comment by Ombridride** [comment]
well, someone can create a zip of 50 skins, we will implement them, no more than 50 skins please ;)

**Comment by Ombridride** [comment]
UP, someone on this ? You're free to do a proposal with 50 of your favorite skins :)

**Comment by ezamlinux** [comment]
hi, if you want i can make selection ! I only keep the skins "medieval fantasy"? or it also keeps skins "modern / futuristic?". obviously I do not touch the "mff_character" ....

sorry for the translation, I'm tired and I use google trad x)

**Comment by Ombridride** [comment]
No problem at all, you can keep the skins you prefer, don't worry about medieval/SF/RP/etc... Jus the skins you prefer :)

Keep in mind we want less than 50 skins

**Comment by ObaniGemini** [comment]
@ezamlinux : make a Pull Request and then we'll see what we approve and what we don't :)

**Comment by ezamlinux** [comment]
@Ombridride 

J'ai fait une PR, j'ai surtout choisi des skins plutot simple ( dans le sens polyvalent ) car je me suis dit que le coté "BADASS" d'un personnage doit ce faire ressentir par son armure / arme et donc sa classe ( si un joueur joue mage mais qu'il a le skin d'un chevalier en armure de plate, couronne d'or ... je ne trouve pas ça très RP ) Après, cela reste mon avis bien entendu et je n'ai fait que proposé un lot de skin.

( désolé pour la non - traduction )

**Comment by Cyberpangolin** [comment]
I wanted to make sure of something: what happens to a player whose skin disappeared? only a dummy texture?

**Comment by ezamlinux** [comment]
@Cyberpangolin It switches to the skin by default

**Comment by ObaniGemini** [comment]
@Cyberpangolin : see the comments on https://github.com/MinetestForFun/server-minetestforfun/pull/477#issuecomment-227132800

**Comment by Cyberpangolin** [comment]
Ok thanks :)
Then --> :+1

**Comment by LeMagnesium** [comment]
The patch was merged : https://github.com/MinetestForFun/server-minetestforfun/commit/5079f3c35d2387a6f33d129a6e91f8877ff2dcf1

**Comment by Ombridride** [comment]
Done, thanks to @ezamlinux !
