### ISSUE TITLE
What about new doors ?

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#422]
50 doors in one mod :)
https://forum.minetest.net/viewtopic.php?f=11&t=10626
https://github.com/minetest-mods/mydoors

**Comment by Ombridride** [comment]
I think we have enough doors, and we will have more with xdecor

**Comment by ObaniGemini** [comment]
These doors are unuseful.
This mod was just made by someone saying "hey what If I used all default textures to make doors !". Seriously no we don't need it.

**Comment by LeMagnesium** [comment]
The server is heavy enough. We could use this for Creative but not Classic..

**Comment by Ombridride** [comment]
We won't add this, sorry

Anyway, thank you for the proposal
