### ISSUE TITLE
Missing dep to "areas" in beds/depends.txt

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#424]
"beds/functions.lua" uses the variable "areas" but beds/depends.txt has no dependancy to the mod "areas" => possibly unknown variable "areas" if the mod "beds" is loaded before the mod "areas".  
It happens on the recently merged commit 93a4774 : "fix unknow item default:coal"

**Comment by mgl512** [comment]
Forgot to tell that beds/functions.lua uses a variable from the "areas" mod at line 187, after a GetModPath("areas"). It's pretty clear when the load order is wrong because you get a server error.

**Comment by LeMagnesium** [comment]
Here, no more error.
