### ISSUE TITLE
Unknown node, maybe "snow:sapling_pine"

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#425]
There are two of them near my house at (3861, 19, 3413) and (3867, 20, 3414). The HUD doesn't want to tell me their name in debug mode. And **I can't destroy them**. They may be "snow:sapling_pine" because I have another one in a chest and the HUD tells me that name when I try to place it. And because there is a suspicious node of dirt between them which must have been a Christmas sapling. 

Why can't I destroy unknown nodes in my area ??

**Comment by LeMagnesium** [comment]
The troubling question for me would rather be "why are there still pine saplings on the map?".
Minetest behaves in strange ways when it comes to unknown nodes. It's possible that it required specific dig groups which are not set now since the node doesn't exist. Can you even punch that node?

**Comment by mgl512** [comment]
I can see the node digging animation when I punch them but nothing happens, the animation ends and the node stays in place or is put back by the server, I don't know. Even the admin pickaxe can't break them on my local copy of the world. I guess it's "snow:sapling_pine" but I can't see the node name in debug mode. I've always been able to see the names of unknown nodes before. 

When the snow ABMs were disabled (months ago), the saplings couldn't grow. I planted several of them in my travels and they must still be there as unknown nodes now... Maybe we could create an alias to one of the flowers or to a sapling of a small tree.

**Comment by mgl512** [comment]
**I could destroy the unknown blocks today** ?!?. But couldn't see their names. But they stacked with the "snow:sapling_pine" I had in a chest. 

The server had a max lag of 58s and 17s when I tried before. With 2 players and much less disturbance than such a lag suggests.

**Comment by LeMagnesium** [comment]
> Maybe we could create an alias to one of the flowers or to a sapling of a small tree. 

There should already by aliases, that's why I'm surprised by all of this; but apparently it is not implemented. Or at least it was not.

**Comment by mgl512** [comment]
Still there. There is an alias from "snow:xmas_tree" (the Christmas sapling) to a block of dirt in 'mods/_misc/aliases.lua'. Maybe add one from "snow:sapling_pine" to something there.

**Comment by Ombridride** [comment]
Is this fixed ?

**Comment by mgl512** [comment]
> Is this fixed ?

No, snow:sapling_pine is still an unknown item. 
The aliases in the fix are wrong anyway, they convert default nodes to snow ones. The file 'mods/snow/aliases.lua ' is probably not loaded or the default pine wouldn't work.

**Comment by LeMagnesium** [comment]
> The aliases in the fix are wrong anyway, they convert default nodes to snow ones. The file 'mods/snow/aliases.lua ' is probably not loaded or the default pine wouldn't work.

Alias is loaded, but I think I messed up the aliases, they're old and I didn't really know at the time how they worked.

**Comment by mgl512** [comment]
Marche. Merci Mg. Je ferme.

**Comment by Ombridride** [comment]
Bien vu @LeMagnesium
