### ISSUE TITLE
prepare mod to update server in version 0.4.14, many mod crash

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#427]
**bobblocks**
``` 
WARNING[Main]: The core.digprop_* functions are obsolete and need to be replaced by item groups.
ERROR[Main]: ModError: Failed to load and run script from /var/opt/minetest/bin/../mods/bobblocks/init.lua:
ERROR[Main]: Runtime error from mod '??' in callback ??(): The core.digprop_* functions are obsolete and need to be replaced by item groups.
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'log'
 ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/deprecated.lua:7: in function 'digprop_dirtlike'
ERROR[Main]: 	/var/opt/minetest/bin/../mods/bobblocks/blocks.lua:26: in main chunk
 ERROR[Main]: 	[C]: in function 'dofile'
ERROR[Main]: 	/var/opt/minetest/bin/../mods/bobblocks/init.lua:2: in main chunk
```

**hudbars**
```
WARNING[Server]: Deprecated usage of statbar without size!
ERROR[Main]: ServerError: Lua: Runtime error from mod '*builtin*' in callback on_joinplayer(): Runtime error from mod '??' in callback ??(): <no description>
 ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'hud_add'
ERROR[Main]: 	/var/opt/minetest/bin/../mods/hudbars/init.lua:114: in function 'add_all'
 ERROR[Main]: 	/var/opt/minetest/bin/../mods/hudbars/init.lua:171: in function 'init_hudbar'
ERROR[Main]: 	/var/opt/minetest/bin/../mods/hudbars/init.lua:310: in function 'custom_hud'
 ERROR[Main]: 	/var/opt/minetest/bin/../mods/hudbars/init.lua:341: in function </var/opt/minetest/bin/../mods/hudbars/init.lua:337>
 ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/register.lua:369: in function </var/opt/minetest/bin/../builtin/game/register.lua:349>
```

**solarmana**
```
WARNING[Server]: Deprecated usage of get_node_group, use get_item_group instead
 ERROR[Main]: ServerError: Runtime error from mod 'solarmana' in callback environment_Step(): Runtime error from mod '??' in callback ??(): Deprecated usage of get_node_group, use get_item_group instead
ERROR[Main]: stack traceback:
 ERROR[Main]: 	[C]: in function 'log'
ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/misc.lua:147: in function 'get_node_group'
ERROR[Main]: 	/var/opt/minetest/bin/../mods/solarmana/init.lua:89: in function 'func'
 ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/misc.lua:34: in function </var/opt/minetest/bin/../builtin/game/misc.lua:11>
 ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/register.lua:369: in function </var/opt/minetest/bin/../builtin/game/register.lua:349>
WARNING[Server]: Deprecated usage of get_node_group, use get_item_group instead
 WARNING[Server]: Deprecated usage of get_node_group, use get_item_group instead
```

**sprint**
```
WARNING[Server]: The use of vel is deprecated. Use velocity instead
ERROR[Main]: ServerError: Runtime error from mod 'sprint' in callback environment_Step(): Runtime error from mod '??' in callback ??(): <no description>
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'add_particle'
 ERROR[Main]: 	/var/opt/minetest/bin/../mods/sprint/esprint.lua:120: in function </var/opt/minetest/bin/../mods/sprint/esprint.lua:84>
 ERROR[Main]: 	/var/opt/minetest/bin/../builtin/game/register.lua:369: in function </var/opt/minetest/bin/../builtin/game/register.lua:349>
```

**Comment by Ombridride** [comment]
Good job, this crash needs to be fixed before the 0.4.14-stable upgrade, it's unfortunately an obligation

**Comment by LeMagnesium** [comment]
Holy Molly, how is it possible that those errors happen and I've never been aware of it? I compiled Minetest not even a day ago!
Alright, gotta fix all of that..

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/bb8f9c71ea808aed722ba6b62c6ab6fe6cf0a971
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/caba7dcf244736d68964a5afb0f937a2b24b816e
https://github.com/MinetestForFun/server-minetestforfun/commit/bd120ad4814176da65caeffc24a06a1f4dc5aef6
There, fixed.

**Comment by Ombridride** [comment]
Thank you @LeMagnesium, happy to see you're still working with us :p 
( you NEVER answer me when I ping you on IRC :( )

**Comment by ObaniGemini** [comment]
Should it be closed ?

**Comment by Ombridride** [comment]
Yes, we forgot this issue :)

**Comment by crabman77** [comment]
En fait depuis ce fix les hudbars on un souci, https://github.com/MinetestForFun/server-minetestforfun/commit/bd120ad4814176da65caeffc24a06a1f4dc5aef6#diff-6273f279638243c7a02b19b7bbba25d3R121

http://dev.minetest.net/HUD
> - statbar 

>size: If used will force full-image size to this value (override texture pack image size)

if on met size="" , les hudbars sont corrects, ou alors il faut trouver les bons parametres, à voir.

**Comment by LeMagnesium** [comment]
> if on met size="" , les hudbars sont corrects, ou alors il faut trouver les bons parametres, à voir.

Mais si on l'enlève l'engine nous crie dessus, correct?

**Comment by crabman77** [comment]
oui c'est pour ça qu'on en est là.

**Comment by LeMagnesium** [comment]
Je vais tenter de remettre tout avec size = ""; y a-t-il encore des choses à fixer?

**Comment by crabman77** [comment]
Encore quelques warnings à corriger.
**classic**
WARNING[Main]: Field "metadata_name": Deprecated; use on_add and metadata callbacks


**creative**
WARNING[Main]: Field "metadata_name": Deprecated; use on_add and metadata callbacks

**Hungry game** 
WARNING[Main]: Field "noise_threshhold": Deprecated: new name is "noise_threshold".

**Comment by Ombridride** [comment]
Tous les serveurs sont maintenant en 0.4.14-stable, je vous invite à aller voir les logs (1000 denrières lignes) pour chopper les dernier WARNING :)

**Comment by Ombridride** [comment]
Je n'ai constaté aucun crash depuis Dimanche, je clos donc cette issue.
