### ISSUE TITLE
some textures missing

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#429]
After visiting MFF Classic, I noticed in my debug file.

> 2016-04-27 09:45:59: ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building texture
> 2016-04-27 09:46:02: WARNING[Main]: Irrlicht: Could not open file of texture: vachette2.png
> 2016-04-27 09:51:32: WARNING[Main]: Irrlicht: Could not open file of texture: Goat.png
> 

Something seems wrong there.

**Comment by Ombridride** [comment]
Just ignore them, there are olds invisible entities which aren't yet depop/be cleared by a clearobject, it's the minetest engine :) ...

**Comment by crabman77** [comment]
Non les mobs se sont les noms des textures qui sont mises dans les b3d, il faut les éditer pour enlever la référence, il faut voir avec @farfadet46.

Pour moretrees_acacia_wood.png c'est simplement que c'est passé dans default mais moretrees n'a pas été update depuis et il y a toujours la référence vers l'acacia dans une table, le mod columnia créer donc un node en se basant dessus mais il n'y a pas de texture.

**Comment by LeMagnesium** [comment]
C'est pas fixé.

**Comment by farfadet46** [comment]
Ce n'est pas possible de créer une autre texture nommée "vachette2.png" au lieu de refaire le modèle ?

**Comment by Ombridride** [comment]
Si c'est possible, mais c'est pas la meilleure solution, ça signifie une texture en plus uniquement pour cacher un message d'erreur...

**Comment by farfadet46** [comment]
ok car j'ai plus la vache en fichier (le serveur d'upload www.Up1.ca a du la supprimer) et je suis passé sur un SSD donc viré pas mal de truc notamment les vieux modèles :'(

**Comment by crabman77** [comment]
@farfadet46 de la chance que je garde 
[mob_cow.zip](https://github.com/MinetestForFun/server-minetestforfun/files/250342/mob_cow.zip)

up1.ca a crash

> WARNING: Due to disk replacement of unknown cause, all images uploaded before 4/29/2016 EST are missing in action. 
> We're working with the provider to resolve this if possible. 
> Please keep in mind that Up1.ca is a demo server only.

**Comment by Ombridride** [comment]
Merci de mettre le modèle de la vache en format blender dans le dossier other-thing du repository, il sert à ça ! :)

**Comment by farfadet46** [comment]
yep grand merci @crabman77 ;)

**Comment by Ombridride** [comment]
Crabman à pusher du code dans mobs pour virer les unknow, tout devrait être bon maintenant
(Il faut attendre le prochain merge)

**Comment by crabman77** [comment]
Non, la vache j'ai enlevé mais la chèvre non, il faut éditer le b3d mais on ne peut pas.
Sinon vous pouvez mettre la texture dans votre textures pack pour ne plus avoir l'erreur.

**Comment by Ombridride** [comment]
The goat blender file is available here : https://forum.minetest.net/viewtopic.php?f=11&t=9917&hilit=goat&start=200#p173535

**Comment by crabman77** [comment]
le .blend est ajouté au dépot, si @farfadet46 peut regarder pour la texture et l'animation qui est mal faite. https://github.com/MinetestForFun/server-minetestforfun/commit/e42117aaf08d3eb1af6d2ef69c7cb4a9eb4462d7

**Comment by farfadet46** [comment]
j'ai ouvert le .blend, je vois beaucoup d'animations non utilisée in-game :/ c'est bizarre il faut faire quoi sur la chèvre concrètement ? j'espère pas refaire toute l'animation XD

**Comment by crabman77** [comment]
Elle marche mal, l'animation est au ralenti quand elle marche, on dirait un truc sur roulette.

**Comment by farfadet46** [comment]
si ce n'est qu'un problème de vitesse autant l’accélérer dans le script non ?

**Comment by crabman77** [comment]
C'est toi l'expert en animation :)

**Comment by Ombridride** [comment]
Je réouvre le temps que l'animation soit fixé :)

**Comment by farfadet46** [comment]
Du coup c'est quoi la commande cette fois ? refaire l'animation du bestio ?
si oui, il faut 
 - marche
 - galop
 - coup de tête
 - IDLE
 - ... autre ?

**Comment by Ombridride** [comment]
c'est tout :)

**Comment by farfadet46** [comment]
voici le B3D de la nouvelle chèvre :
https://up1.ca/#O2NBdBHx2LzwtEpHSqN-6Q

avec les animations suivantes :
IDLE de 0 à 60
walk de 80 à 110
run de 160 à 198
punch de 120 à 150

**Comment by crabman77** [comment]
animation refaite et accélérée un peu ça fait vraiment mieux  https://github.com/MinetestForFun/server-minetestforfun/commit/23c47970afa7c66c9577568534208b5cde7bf630
