### ISSUE TITLE
Needed textures for many mods

### ISSUE THREAD

**Issue by LeMagnesium** [MinetestForFun/server-minetestforfun#43]
## RUNES mod :
(All spell textures must be books open, with a distinct glyph/symbol on one or more page)
- [x] runes_earthquake_major.png https://github.com/MinetestForFun/server-minetestforfun/commit/ef6f0d31278acaa4fe522a7f2cf8f9b655fcdf52
- [x] runes_earthquake_medium.png https://github.com/MinetestForFun/server-minetestforfun/commit/ef6f0d31278acaa4fe522a7f2cf8f9b655fcdf52
- [x] runes_earthquake_minor.png https://github.com/MinetestForFun/server-minetestforfun/commit/ef6f0d31278acaa4fe522a7f2cf8f9b655fcdf52
- [x] runes_silver_cross_amulet.png (cotton + silver cross) https://github.com/Ombridride/minetest-minetestforfun-server/commit/63b9abe34dbee4332c77ce2f6125459e1696ca8a
- [x] runes_minotaur_eye_amulet.png (leather + minotaur eye) https://github.com/Ombridride/minetest-minetestforfun-server/commit/63b9abe34dbee4332c77ce2f6125459e1696ca8a
- [x] runes_grim_reaper_amulet.png (chain + skull) https://github.com/Ombridride/minetest-minetestforfun-server/commit/63b9abe34dbee4332c77ce2f6125459e1696ca8a
- [x] runes_black_magic_block.png (skull/death/black block) https://github.com/MinetestForFun/server-minetestforfun/commit/a651f88919bafaa6abe746c077ed9b06c49c2d47

## MOBS mod :
- [x] Dungeon Master Diamond (light red colored diamond https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/dungeonmaster.lua#L112)
- [x] Zombie Tibia (just a big bone https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/zombie.lua#L42)
- [x] Minotaur Fur (https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/minotaur.lua#L79)
- [x] Lot of Minotaur Fur (https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/minotaur.lua#L85)

Last update : 03/09/2015 at 12:23PM UTC+2 by LeMagnesium

**Comment by ObaniGemini** [comment]
What is that mod ?

**Comment by Ombridride** [comment]
The "runes" mod is our selfmade spells implementation for minetest. At the moment, the spells names aren't very great choose. We keep the effect of each spell mysterious (for the moment) :)

**Comment by ObaniGemini** [comment]
How can we make textures if we don't know what are their use ? :)

**Comment by Ombridride** [comment]
(If you want participate, join us in our dev irc)

**Comment by LeMagnesium** [comment]
> We keep the effect of each spell mysterious (for the moment) :)

The names are pretty abvious though..

**Comment by ObaniGemini** [comment]
Can you leave a link for actual textures? For we can have a look at them :)

**Comment by LeMagnesium** [comment]
I will edit the first post to put the links to the pushed textures.

**Comment by Ombridride** [comment]
JukeBox : 5 new textures, 1 redo (the first)
https://github.com/Ombridride/minetest-minetestforfun-server/commit/e4bbe52feb8391f00053bbdcb5b1ab8a9473d6e1

**Comment by Ataron** [comment]
Runes: 1 new texture : 703518

**Comment by Ombridride** [comment]
@Ataron, can you created and commited this textures soon ? (The Warrior and Hunter integration aren't very far ;))

**Comment by Ataron** [comment]
Add a few of them : https://github.com/Ombridride/minetest-minetestforfun-server/commit/25a5d20501897e799a0b83c4240b31e6f7fd9957 (with the help of paly2)

**Comment by LeMagnesium** [comment]
Should we close this now?

**Comment by Ombridride** [comment]
Closed this issue, we will create another issues when we will need more textures
