### ISSUE TITLE
Mobs list

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#434]
##### And what of those we could remove :

- ~~bee : is this useful ? => yes for farm, beehive/honny~~
- ~~bunny : needed for cuteness~~
- ~~chicken : probably needed for farm~~
- ~~cow : needed for farm~~
- ~~creeper : needed for diversity and epic (+ using an other model, so lightweight)~~
- ~~dirt_monster : possibly removable due to sand monster and stone monster => we will not remove this monster~~
- ~~dungeon_master : needed for epic and history~~
- goat : possibly removable due to cow and chicken
- ~~kitten : needed for cuteness, but maybe only keep bunnies => we will keep cats, can be tamed and parts of your house, you can also give them a name~~
- ~~minotaur : needed for epic~~
- ~~oerkki : needed for fear and history~~
- ~~pig : possibly removable due to cow => we will not remove it, pig gives very interesting food when die~~
- ~~sand_monster : needed for epic and fear (maybe replace the model with stone monster's one ?) => the model is great~~
- ~~shark : needed ? => water diversity and thread~~
- ~~sheep : needed for farm~~
- ~~spider : needed for epic, fear and farm~~
- ~~stone_monster : possibly needed for fear, but maybe it can be replaced by oerkki => we will not replace them by oerkki, it's really a different monster and way to kill him~~
- ~~tree_monster : possibly needed => history, fear of trees~~
- ~~wolf : needed for fear on overworld => can be tamed for dogs~~
- ~~mese_monster : needed for epic, farm, fear, and diversity (most original monster, and not so hard to kill)~~

**Comment by Cyberpangolin** [comment]
IMO sand, stone and dirt monster could be merged in 1 mob with 3 skins, 1 chosen randomly.
you forgot the creeper (?)

**Comment by ObaniGemini** [comment]
@Cyberpangolin : I proposed that : actually there is a model for sand monster and a model for both stone and dirt monsters.
Adding creeper.

**Comment by Ombridride** [comment]
Chacun de ces trois monstres à ont leurs spécificités, sans compter le spawn et les résistance à la lumière qui diffre, les merger en un n'est pas possible.

chaque monstres à son utilité, ou est sur MFF car unique et non visible sur les autres serveurs...

Pour info :
- le lava_flan est déja désactivé car remplacé par le lava_slime
- wolf car peut etre tamed en dog et utiliser comme compagnon
- shark permet la remise en question d'un trajet uniquement par l'eau quand on veut éviter une jungle
- pumba n'est pas dans notre mob
- pig est dans notre mod et remplace le pumba, ils sont similaires, permette le drop de steaks qui nourrissent extremement bien cru ou cuit
- le rat permet d'avoir del a nourriture dans les caves pas trop profonde (ça ce cuit, la viande de rat)
- et j'ai plsu deb atterie, mais aucun mob n'est enlevable sans perdre quelque chose...

**Comment by ObaniGemini** [comment]
- lava_flan : donc on peux supprimer ?
- wolf : ok
- shark : ok
- pumba : alors on peux le supprimer ?
- pig : ok
- rat : je n'en ai jamais croisé et pour ce que ça rapporte... En général les mineurs s'arrangent pour avoir masse de nourriture

P.S : je me suis référé au dossier models, ce qui veux dire que tout ce que j'ai cité compte comme un modèle, sauf précision (creeper, dirt_monster)

**Comment by crabman77** [comment]
le rat ne drop rien.

**Comment by ObaniGemini** [comment]
C'est bien ce que je me disais

**Comment by Ombridride** [comment]
le rat ce clique droit... il ne drop rien oui :)

**Comment by Ombridride** [comment]
pumba est DEJA supprimé, lava_flan est juste commenté, on peut le virer oui

**Comment by crabman77** [comment]
le rat sert au chat.
je suis entrain d'enlever des fichiers /sons/textures/mesh et fix quelques truc
j'ai rajouter des poissons au chat, si on vire le rat je le rajoute, je vais push là.

**Comment by Ombridride** [comment]
Le chat peut etre déjà tamed avec rat ou poisson (normalement), donc enlever le rat pour le chat ne pose "normalement" pas de soucis

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/models/mobs_pumba.x

**Comment by crabman77** [comment]
@Obani je suis entrain de les enlever , ne touche/push pas surtout

**Comment by ObaniGemini** [comment]
zombie is quite similar in its behaviour to sand/stone/dirt monsters. One model for four ? (three/two if we delete stone monster and/or dirt monster)

**Comment by Ombridride** [comment]
Les zombies sont uniquement dans la nether forest et drop des items pour arc ultime hunter, on n'enlève pas

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/117d89197826c3ce8bac594e4f4271818a640797

**Comment by ObaniGemini** [comment]
You didn't understand. I was talking about unifying the model.

**Comment by Ombridride** [comment]
@ObaniGemini 
I edited the first post, you don't know as much as us the mobs mod and it's normal.

For me the only other monster we can remove is the ghoat, but we loose diversity, and this monster is really rare in our biome...

**Comment by ObaniGemini** [comment]
Maybe I don't know the mobs mod but I know that we can create with one model and several textures several monsters.
And that dirt monster is quite unuseful and boring due to sand monster and stone monster that greatly reminds him, and the many other overworld monsters (tree, spider, yeti, minotaur, sand, mummy,...)

As it's a second or third plan monster I thought it could be removed, participating to the nerf plan.
