### ISSUE TITLE
More lags with factories

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#435]
Today, the average lag was around **4.5s**, with a top at **7s** when I dared to use my factories.

It seems that plumbum's factory (and maybe other ones) is working for nothing, **when nobody is near it.**
We must kill that **f+*"*ç lag!**

Proposals:
- make sure pipeworks and mesecons are **totally inactive** when there is no player near them (say 50-100 blocks). Ideally, only tweak the items that may add thing into the pipes, ie: blinky plants, vaccuming pipes, injectors... so the units already into the factory can finish to be processed.

- add a "pipepolice" (I can do the job) who has rights to outerpass the areas to kill or fix a bad factory.

- eventually restrict pipeworks and mesecons to selected people who know what can or cannot be done.

- take a previous version of pipeworks /mesecons that was inactive at a certain distance (MFF1 did not have this problem, if I remember well. Typically, I had to be near the public factory to have the stone I needed, but there was NO player detector))

- slow down pipeworks and mesecons's thick depending on the max_lag value. a bigger lag means slower factories, so less lag.

- slow down the vacuuming speed.

- If really we cannot make better, remove pipeworks **and buy me tissues**. I may cry a lot.
The objective is of course to kill any zombie factory that makes the game unplayable. It seems that any factory stays on until all pipes are empty...

Please note: my 2 factories have protections against lag: the public one is automatically stopped when an item (cobblestone or stone brick) cannot find a way to a chest, and the wood one is stopped as soon as nobody is inside it (player detector). So, it _IS_ possible to do it.

**Comment by paly2** [comment]
Le problème des usines Pipeworks, c'est qu'il droppe les items quand les coffres sont pleins (ou qu'il n'y a pas de tube suivant), en créant un surnombre d'entités. Pour empêcher ça, commenter une ligne suffit (voir [ici](https://github.com/paly2/Mynetest-server/blob/5e59c90f94628e84a752b7f4a6b2b458be33acd3/mods/pipeworks/item_transport.lua#L252)). Ça corrige aussi le problème de "l'aspiration infinie" des items.

**Comment by ObaniGemini** [comment]
C'est un fix stupide je trouve. Au lieu de stopper la production ça ne fait que supprimer les trucs en trop, et on perds un grand nombre de ressources...

**Comment by paly2** [comment]
> Au lieu de stopper la production ça ne fait que supprimer les trucs en trop, et on perds un grand nombre de ressources...

On ne perd aucune ressource, on en gagne (depuis quand enlever des lignes bouffe-t-il des ressources ?). C'est vrai, on ne stoppe pas la production, mais il vaut mieux supprimer les trucs en trop que de les accumuler sur le sol.

**Comment by Ombridride** [comment]
C'est déjà un bon début de fix @paly2, merci pour la proposition.

@ObaniGemini 
Même si ce n'est pas une solution définitive, ça reste des items au sol qui bouffe des ressources inutilement, le joueur n'étant pas à côté ou n'ayant pas prit la peine de mettre en place un système de "poubelle", s'il perd des ressources c'est de sa faute.

**Comment by LeMagnesium** [comment]
> on perds un grand nombre de ressources...

> On ne perd aucune ressource, on en gagne (depuis quand enlever des lignes bouffe-t-il des ressources ?).

Je suis le seul ici qui a compris qu'il parlait de ressources in game?

Bon, analyse point par point.
> make sure pipeworks and mesecons are totally inactive when there is no player near them (say 50-100 blocks). Ideally, only tweak the items that may add thing into the pipes, ie: blinky plants, vaccuming pipes, injectors... so the units already into the factory can finish to be processed.

Ça devrait déjà être le cas; de ce que je sais, ces mods là n'utilisent pas d'ABM avec 'catch up'; et même si elles le faisaient, sans chargement forcé d'une chunck il n'y a pas d'action de pipeworks et mesecons si la chunck est déchargées. Après, votre client charge bien plus de chunck que vous ne pouvez l'imaginer... Et tant qu'on y est, c'est pas si simple de dire "okay, il n'y a plus personne, on coupe l'entrée et on laisse le mécanisme se vider" au niveau du code; on a pas inventé les player detectors pour rien...

> add a "pipepolice" (I can do the job) who has rights to outerpass the areas to kill or fix a bad factory.

Très drôle comme concept. Encore plus de code ch*ant à gérer pour les areas. Par contre j'aime bien le nom, "Pipe Police".

> eventually restrict pipeworks and mesecons to selected people who know what can or cannot be done.

Ceux qui construisent les usines qui produisent du lag sont très rarement les petits noobs qui ignorent les risques de mesecons. Il y en a, mais ils voient bien vite le problème; la majorité des lags d'usine sont dus à des gens qui savent construire des mécanismes complexes.

> take a previous version of pipeworks /mesecons that was inactive at a certain distance (MFF1 did not have this problem, if I remember well. Typically, I had to be near the public factory to have the stone I needed, but there was NO player detector))

Oh que si on avait du lag; du beau lag même, quand on approchait les usines. Pipeworks et mesecons dans des versions antérieures sont moins optimisés et ont moins de fonctionnalités que nos versions actuelles.

> slow down pipeworks and mesecons's thick depending on the max_lag value. a bigger lag means slower factories, so less lag.

Enfin une proposition qui a du sens!

> slow down the vacuuming speed.

Facilement faisable j'imagine; très peu problématique. Ça bouffera toujours autant de ressource, mais plus longtemps et lentement.

Rapellez-vous que c'est MineTest auquel on a à faire; autant mesecons est plutôt bien optimisé, mais dès qu'il s'agit de charger les entités dans pipeworks le jeu va avoir du lag. Si vous voulez le réduire, utilisez des injecteurs au mese et une fréquence de tick plus faible pour envoyer stack par stack au lieu d'item par item (ce que je viens d'écrire est un peu faux mais vous voyez l'idée).

**Comment by Ombridride** [comment]
Je suis pour la mise en palce de ces 2 points :

> slow down pipeworks and mesecons's thick depending on the max_lag value. a bigger lag means slower factories, so less lag.

> slow down the vacuuming speed.

**Comment by paly2** [comment]
> Je suis le seul ici qui a compris qu'il parlait de ressources in game?

Euh, non, en fait c'est plutôt moi qui suis le seul à ne pas l'avoir compris (MFF l'avait compris).

> slow down pipeworks and mesecons's thick depending on the max_lag value. a bigger lag means slower factories, so less lag.
slow down the vacuuming speed.

Comme l'a dit @LeMagnesium, diminuer la vitesse des items dans les tubes ne réduit pas forcément la consommation de ressources. Et le faire en surveillant la valeur de max_lag entraîne des instructions en plus à éxécuter pour chaque action, donc une perte de performances.

Du coup, une fois implémentées, il serait bien de vérifier que ces modifications soient réellement "rentables" niveau performances...

**Comment by Cyberpangolin** [comment]
> Ça devrait déjà être le cas; de ce que je sais, ces mods là n'utilisent pas d'ABM avec 'catch up'; et même si elles le faisaient, sans chargement forcé d'une chunck il n'y a pas d'action de pipeworks et mesecons si la chunck est déchargées. Après, votre client charge bien plus de chunck que vous ne pouvez l'imaginer... Et tant qu'on y est, c'est pas si simple de dire "okay, il n'y a plus personne, on coupe l'entrée et on laisse le mécanisme se vider" au niveau du code; on a pas inventé les player detectors pour rien...


@LeMagnesium justement, pourquoi ne pas implémenter le code du player detector mais à 100 blocs pour tous les items actifs?

**Comment by crabman77** [comment]
proposition:
1) Obliger le node breaker à chercher un coffre à coté de lui et y mettre directement les items, ou le changer en coffre, il est plein il s’arrête.

2) Mettre un taux d'usure/une limite sur le nodebreaker, quand il est à 0 il faut le ré-enclencher, ça oblige à rester à proximité, celui qui ne se connecte pas pendant x temps ne produit pas de lag.

et enlever le vaccum tubes.

**Comment by farfadet46** [comment]
sinon ajouter un filtre sur les "vaccum tubes" genre aspirer uniquement les pommes ... 
sinon très bonne idée de placer une minuterie sur les "node breaker"

**Comment by Ombridride** [comment]
## Roadmap
### No more lags from factories !

> 1) slow down pipeworks and mesecons's thick depending on the max_lag value. a bigger lag means slower factories, so less lag

=> Diviser les ticks par 2 quand le max_lag dépasse 2, et le réduire de 4 quand il dépasse 3 et plus me semble pas mal.
OU
=> Juste diviser par 4 les ticks si flemmardise de coder un truc en fonction du maxlag :)

> 2) slow down the vacuuming speed

=> Diviser la vitesse par 4 tout le temps. (n'engendre rien de problématique, l'objet finira forcément son chemin)

> 3) Supprimer les items qui sortent d'un pipe

=> Commenté la ligne comme montré par Palige : https://github.com/paly2/Mynetest-server/blob/5e59c90f94628e84a752b7f4a6b2b458be33acd3/mods/pipeworks/item_transport.lua#L252

> 4) Ajout de condition(s) aux node breakers

=> Obliger le node breaker à chercher un coffre à coté de lui et y mettre directement les items
OU
=> Le changer en coffre qui "dig", il est plein il s’arrête

> 5) Ajout d'un système de pause après x occurences au "node breaker"

=> Mettre une limite sur le nodebreaker, quand il est à 0 il faut le ré-enclencher, ça oblige à rester à proximité. De ce fait, celui qui ne se connecte pas pendant x temps ne produit pas de lag. 
/!\ Attention à ne pas permettre un système automatiser pour le ré-enclencher (via mesecons) ! /!\

**Comment by crabman77** [comment]
ligne commentées https://github.com/MinetestForFun/server-minetestforfun/commit/29da4843da3cc7267a5fea2d494f09f848dca4c6

**Comment by Cyberpangolin** [comment]
> Diviser les ticks par 2 quand le max_lag dépasse 2, et le réduire de 4 quand il dépasse 3 et plus
    OU, Juste diviser par 4 les ticks si flemmardise de coder un truc en fonction du maxlag :)
Et si on divisait le tick par le carré du max lag si ce dernier dépasse 1s? Ce serait plus efficace surtout sur de grandes valeurs.

**Comment by crabman77** [comment]
je doute que l'on puisse manipuler le tick à la volée.

**Comment by Ombridride** [comment]
Oui, et puis même si c'est possible, on va devoir coder ça, donc je change la roadmap pour y prendre en compte et aller au plus rapide.

**Comment by LeMagnesium** [comment]
> Donc un item particulier, à partir du moment où il est dans le système, est toujours aussi vite traité, MAIS moins d'items rentrent dans la machine à chaque seconde.

Alors on diminue le tick de la blinky plant et voilà.

**Comment by Cyberpangolin** [comment]
Attention, les vaccuming pipes ne sont pas activés par la blinky plant, donc ta solution n'est pas valable!

**Comment by crabman77** [comment]
Les vaccum n'aspirent que 50 items, les autres sont simplement détruit  https://github.com/MinetestForFun/server-minetestforfun/commit/9775af22f3d2b4b0944b6ecd11bb3a014cb1fc73.

**Comment by LeMagnesium** [comment]
Voilà pour les blinky plant et l'intervalle des vacuums : https://github.com/MinetestForFun/server-minetestforfun/commit/8f6ff84f4b62dd30d4f635b6f92c881a208ff018

**Comment by Ombridride** [comment]
Merci à vous, je viens d'update la roadmap

**Comment by paly2** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/8f6ff84f4b62dd30d4f635b6f92c881a208ff018
Note: plutôt que de modifier la valeur par défaut de 3 à 7 dans le code de mesecons, il vaut mieux ajouter dans le minetest.conf:
`mesecon.blinky_plant_interval = 7`

**Comment by Ombridride** [comment]
Bien vu, si c'est paramétrable depuis le minetest.conf c'est mieux, je fais la modif

**Comment by Ombridride** [comment]
Bon début et réaction rapide, il nous reste encore du travail à acccomplir, voici les tâches restantes :

### Roadmap (uniquement tâches restante)
#### No more lags from factories !

________________________________________________________________________

> 4) Ajout de condition(s) aux node breakers

- [ ] Obliger le node breaker à chercher un coffre à coté de lui et y mettre directement les items
- [ ] OU, Le changer en coffre qui "dig", si il est plein alors il s’arrête

> 5) Ajout d'un système de pause après x occurences au "node breaker"

- [ ] Mettre une limite sur le nodebreaker, quand il est à 0 il faut le ré-enclencher, ça oblige à rester à proximité. De ce fait, celui qui ne se connecte pas pendant x temps ne produit pas de lag. 
/!\ Attention à ne pas permettre un système automatiser pour le ré-enclencher (via mesecons) ! /!\

________________________________________________________________________

**Comment by Ombridride** [comment]
@crabman77 fixed all of our factories lags with the new "blinky plants" code

The "blinky plants" are now disabled when players aren't near it.

Server lag before this commit : 2sec to 3sec
Server lag now : less than 0.5sec (0.4 actually with 2 players online)

**Comment by Cyberpangolin** [comment]
Thanks a lot :D
:+1:
