### ISSUE TITLE
[idea] Engineer Class

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#438]
toto112 suggested an "engineer" class with emphasis on building/mining tools/abilities. An engineer could jump higher and reach farther when placing blocks. Maybe he can elaborate more. 

I like the idea because it would be the first and maybe only class not dedicated to war.

**Comment by Cyberpangolin** [comment]
+758437528759

**Comment by Ombridride** [comment]
+1 we will work on this in the future :)

**Comment by Ombridride** [comment]
I close this issue because I merged this new ideas with the issue https://github.com/MinetestForFun/server-minetestforfun/issues/183
