### ISSUE TITLE
turn xban into subtree like for SB

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#439]
Can someone turn xban mod into subtree like in the SB server please ?

**Comment by LeMagnesium** [comment]
> Someone can turn xban mod into subtree like in the SB server please ?

Err.. I'll just remove it as a submodule, let's not add more crappy subtrees...

**Comment by Ombridride** [comment]
I said you in IRC just copy/paste and don't do subtree or submodule thnks for reading all of my messages...

**Comment by LeMagnesium** [comment]
> thnks for reading all of my messages...

(I just clarify for those who do not have the IRC logs)
Done
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/21e2ea60a9830770dff0d36d0ee2294387613042 -> https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/9912b9241f2c387bb64af52e79cfa33f598c5c9e

**Comment by Ombridride** [comment]
Sorry for my answer if you didn't get my IRC message :/

& thank you for this issue ;)

**Comment by LeMagnesium** [comment]
XBan on classic is a normal folder; it might have been added as a subtree but it has no incidence on the way it behaves with usual git commands (plus I might have to cherry-pick out all the commits merged from xban2; which will take all eternity)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/3510efea0838c1be558ff3d94e592405d82de135
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/61444694f7aeadceeb3513b155226e1d62ca8551
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/d49c7ddcf205f1c856d1e74eea173f57f766ba00
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/af10e1164288bec00fa52135b06e74081cfd6db6
