### ISSUE TITLE
[idea] more classes

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#440]
### the merchant
the merchant walks faster (+15%?) than any other, but has less sprint (8s?).
can wear only 1 piece of armor, but his merchant clothes give him more place in his inventory.
Has a deal bonus when trading at the general market (if implemented).

### the priest
The priest is full of faith, but doesn't believe in sorcellery, so he has no mana.
The Big IGNUscius is with him, so the standard aggressive mobs won't attack if he stays peaceful with them.
His clothes give him IGNUscius's light, so he brights like a torch in the night (possible to code?) if he wears his habit.

**Comment by Ombridride** [comment]
Forget this classes for the moment,

No offense, but for now I will close this issue but i keep in mind your ideas.
