### ISSUE TITLE
Add as sound when a daily quest is completed

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#441]
Add a sound when a player completed a daily quest but add a sound only for the player that done the quest, not a sound for other players like SB.

We can take the sound from SB, @ObaniGemini made great sounds ;)

**Comment by Ombridride** [comment]
Done
Thank you @crabman77 

https://github.com/MinetestForFun/server-minetestforfun/commit/790118cf67e1132f1fa82c9eba2e740ad4e7c707

**Comment by ObaniGemini** [comment]
THose aren't my sounds
