### ISSUE TITLE
text on signs is randomly turned of 90°

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#442]
![capture du 2016-05-10 08 47 24](https://cloud.githubusercontent.com/assets/12512762/15137847/66e61162-168c-11e6-8eee-c39b30611a9d.png)
Here is how I found today signs I have put in front of the public factory entrance yesterday evening.

![capture du 2016-05-10 08 47 54](https://cloud.githubusercontent.com/assets/12512762/15137848/66e62b7a-168c-11e6-904d-f962c5352da6.png)
and how they should be.

The text seems to turn 90° at some occasion, I already noticed it before.
Note: the left of the signs on the example is oriented south, the right to the north.

**Comment by Ombridride** [comment]
This isn't a bug, it's normal after the Homedecor update since some months ago.

You need to dig the sign, and put it again and write again the text (you can copy/paste the text)

**Comment by Cyberpangolin** [comment]
Donc si je pige bien faut reposer le sign autant de fois que nécessaire jusqu'à ce que ca passe?
Je ne l'ai pas posé avant l'update il y a plusieurs mois, mais hier soir...

**Comment by farfadet46** [comment]
Je pense que tu peut lui appliquer une rotation avec le tournevis ... essayer
