### ISSUE TITLE
[Update] signs_lib

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#444]
ONLY when 0.4.14 on our servers !
Need to be applied on all of our servers

https://github.com/minetest-mods/signs_lib

**Comment by Ombridride** [comment]
All of our servers are now on Minetest 0.4.14-Release, is it possible to done this issue ?

**Comment by LeMagnesium** [comment]
Coming right up.

**Comment by Ombridride** [comment]
- [x] Classic server https://github.com/MinetestForFun/server-minetestforfun/commit/fe49c72f9c82f0bd0c5cf3de3df30893992e3798
- [ ] HG server
- [ ] Skyblock server
- [ ]  server

**Comment by Ombridride** [comment]
Not closed, 3 servers missing ^

**Comment by LeMagnesium** [comment]
I had forgotten to update the list, sorry.

**Comment by Ombridride** [comment]
Thank you for your work
