### ISSUE TITLE
[Update] sea mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#445]
Need to be applied on Classic/Creative only

https://bitbucket.org/minetest_gamers/minetest-mod-sea/overview

BE CARFUL to our changes

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/689e746366e9527c092b271a97eeb5bd9b22056b
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/0e5e4a5616422fb3e7cc581b5b6448031a363817
