### ISSUE TITLE
Pénalité du /home unique

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#447]
C'est toujours très pénalisant pour les joueurs qui n'habitent pas au spawn de ne pas pouvoir placer de point d'ancrage dans les mines. Le /sethome est réservé à une maison (à 5600 blocs du spawn pour moi). Les habitants du spawn ont une commande /spawn qui les ramène chez eux. Ils peuvent faire un /sethome dans une mine, mourir et y retourner. Pas les autres. MFF n'offre rien pour compenser ce privilège. 

-- Le Docteur, président du DAL², Direct Access to Loot x Droit Au Logement.

**Comment by Ombridride** [comment]
Oui, il faut que l'on trouve un moyen alternatif pour les joueurs qui ne logent pas au spawn

Ce point est déjà dans la Roadmap pour la facilitation du serveur, on y évoque les "téléporteur" à voir ce qu'il sera fait au final

Pour l'instant je ferme cette issue que je réfère à la Roadmap.
