### ISSUE TITLE
Mobs can spawn at bad places

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#449]
I just saw a DM spawning near me in a 2 blocks height place. It had the head into the ceiling and seemed to be unable to move, but still able to attack.

-> Before spawning, the system should check if there are 3 blocks of air.

**Comment by Ombridride** [comment]
mobs redo already check and spawn monsters not near you, we can increase a little this limited area because of lags (server side)
We will do it

**Comment by Cyberpangolin** [comment]
note: other mobs seem concerned too, I saw mese monsters spawning in a 2(height)x1(width) stair, unable to move, and even to shoot. They looked... angry. note they came exactly near a torch, aren't they supposed not to spawn near a light source?

**Comment by Ombridride** [comment]
We configures mobs to spawn even if it's an area with a little "light level"

**Comment by Cyberpangolin** [comment]
![screenshot_20160516_172927](https://cloud.githubusercontent.com/assets/12512762/15294418/7380b922-1b8c-11e6-9594-259dd5b58383.png)
do you mean... at 2 blocks of a torch and 1 if you count in diagonal?

**Comment by Ombridride** [comment]
I checked the parameters, neither the range spawn nor the minimum light at spawn are bad configured, everything is good, i closed because we can't do anything more, it's a Tenplus1 problem at this point...
