### ISSUE TITLE
flint & steel craft

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#450]
I noticed that we have now a flint & steel from fire and another from fake fire. do we really need 2 different cafting recipes and 2 different flint&steel?
I think that the flint + steel recipe is nice :)

**Comment by Ombridride** [comment]
The flint & steel from fire mod is the latest minetest_game flint & steel, we need to remove the others flint & steel from other mods

**Comment by Ombridride** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/e96e52f358e4306f0c953c02a1709cf9874c0e73
