### ISSUE TITLE
Décalage entre spawns

### ISSUE THREAD

**Issue by b91b** [MinetestForFun/server-minetestforfun#451]
Lorsque je spawn du portail nether q cote du spawn on arrive au nether avec un décalage. Et au retour, c'est pire, on tombe a coté du spawn et de tres haut, on en ,meurt en perdant tout

**Comment by LeMagnesium** [comment]
Could you retry after the server is updated? I aligned the spawns.

**Comment by Ombridride** [comment]
Nether spawn broken
![](http://i.imgur.com/UcGmlNJ.png)

**Comment by crabman77** [comment]
C'est ma faute, c'est h2omes qui interdisait d'utiliser /spawn dans le nether vu qu'on avait pas de spawn nether, mais depuis hier c'est fixé.

**Comment by Ombridride** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commits/master/mods/nether

Je merge, quelqu'un doit re-tester s'il vous plait

**Comment by crabman77** [comment]
cette fois c'est bon . https://github.com/MinetestForFun/server-minetestforfun/commit/06d5335d907baedea8435f61c71c709d480fee18

**Comment by Ombridride** [comment]
Ok je te remercie @crabman77 
Je remerge tout de suite

**Comment by LeMagnesium** [comment]
Est-ce que tout va bien maintenant?

**Comment by Ombridride** [comment]
Can someone do a test and tell us if everything works great now ?

**Comment by crabman77** [comment]
Je viens de tester et on revient bien au spawn maintenant.

**Comment by Ombridride** [comment]
Parfait, merci pour le test, je clôture.
