### ISSUE TITLE
no more home

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#452]
With the "home" -> "homes" update, we lost the old home we used to have.

In my case, it means I need to dig 1300 blocks to re-find it. Probably other players will need to re-set it.

Do we have a save for old home that could be applied as the actual home?

**Comment by Ombridride** [comment]
Yes it's normal, You need to reset it
I predicted some players will open issues about it =)

@crabman77 can answer you with technical explanations

**Comment by Ombridride** [comment]
Comme dis plus haut, c'est norma lavec le nouveau système
