### ISSUE TITLE
Homes improvement ideas

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#453]
As we now have the "homes mod", why not add a button " To spawn" in the menu?

Another idea, more complicated. add a "share" button to invite friends to your home  / pit (with a short timeout and 1 use only)

**Comment by farfadet46** [comment]
ok like "share my position" to friends ? 
Maybe we can add like a craftable crystal , where it become destroyed after use ?
when use, the player need to put the player's name to TP to ; then the crystal is destroyed.

**Comment by Ombridride** [comment]
Maybe an item, craftable with some dismonds, with only 1 use

OR 

the easier way should be the /tp /tpy command like skyblock, but with a cooldown to avoid abuse...

**Comment by crabman77** [comment]
Je viens de faire ça, ajout du bouton "spawn" puis un bouton pour se téléporter à la position qu'un joueur nous a envoyé, et le possibilité d'envoyer notre position à un joueur, avec des timer pour limiter.
![home](https://cloud.githubusercontent.com/assets/7189389/15374349/2d873170-1d4a-11e6-86c7-818913051201.png)

**Comment by Ombridride** [comment]
Bravo @crabman77 Superbe interface

Peux tu expliquer l'utilité du bouton "refresh" ?
Et peux tu mettre un petit cooldown sur la téléportation entre amis ? (5 minutes maximum) => Tout comme "home", pour éviter les flood de téléportations (un cooldown est normalement déjà défini sur home)

**Comment by crabman77** [comment]
Le bouton "refresh" c'est pour la liste des connectés, la liste est retenu dans une table qui sert pour le "dropdown", donc il faut que ça corresponde à l'index de sélection.
Les cooldown sont déja en place, 5 minutes comme le spawn.
J'ai passé le mod spawn dedans aussi, c'est juste la chatcommand "spawn", plus pratique pour les cooldown et puis se sera moins dispersé.

**Comment by Ombridride** [comment]
Parfait, ta penser à tout ! :)
