### ISSUE TITLE
Mise a jour du site 

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#457]
J'ai remarqué que le site n'est pas a jour (tout en bas de page sur l'article 
 - "qu'est ce que Minetest?" ; "... actuellement en version 0.4.13 ..."
peut être a jouter un lien vers le site officiel ?

**Comment by Ombridride** [comment]
- [x] Numéro de version corrigé 
![](http://i.imgur.com/uhitzEq.png)
