### ISSUE TITLE
Migrate database backend to Postgresql

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#458]
https://forum.minetest.net/viewtopic.php?f=7&t=14722&p=218947#p218312

Is the mapper compatible ?
It should be a good idea to discuss about this migration, if it will be a good thing, well need to discuss :)

**Comment by Ombridride** [comment]
Nobody want to explain his point of view about it ?

**Comment by Cyberpangolin** [comment]
Then I give you mine, but it probably won't be helpful:
If I look at the first post, it looks like to be all benefits: lighter and faster, but I'm not sure it's a good idea to convert an already existing server: what if there was any corruption / loss in the chests / blocks re-oriented on buildings ?
So, as a player who does'n know well how it works internally, I'd like to say ok, let's do it, but only when the disk space is full, or at the end of MFF2.

**Comment by Darcidride** [comment]
Since the hardware available ressources isn't a problme, i closed this issue.

Maybe someday we will reopen it :)
