### ISSUE TITLE
Armor depleted: bug in the hud

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#459]
My armor is depleted, as you can see into my screenshot. BUT: my hud indicates an armor at 100%.
This bug disappears with a logout-login.
Please note: I checked that I had nothing left in my armor.
![screenshot_20160527_181354](https://cloud.githubusercontent.com/assets/12512762/15615672/f6b75d76-243f-11e6-8232-e17c25c73991.png)

**Comment by Ombridride** [comment]
A corrupted value was sended/received by you client, not a mod problem is my point of view

If it's now working great, dont worry :)

I closed thei ssue (unfortunaly)
