### ISSUE TITLE
the diamond axe color doesn't match other diamonds tools

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#460]
![capture](https://cloud.githubusercontent.com/assets/11613522/15629613/f1570816-251d-11e6-8f49-7f98535fe945.PNG)
and an other little problem, the model of the showel is 90° rotated in hand ?
![screenshot_20160528_215223](https://cloud.githubusercontent.com/assets/11613522/15629653/037adcd8-251f-11e6-82e9-494995700e8a.png)

**Comment by Ombridride** [comment]
The shovel rotation is normal for me, it's like the other shovels models

For the color, I'm fixing it right now

**Comment by Ombridride** [comment]
Fixed on all servers, also I compressed without loose the tools textures.
