### ISSUE TITLE
IRC is out

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#461]
As you know, irc.inchra.net is down for now 2 days.
The bad thing is: we are really dependant of it and are now unable to communicate efficiently.

Maybe it is time to add an irc server to xorhub.com to have something reliable and that can be tweaked / managed by us. Or not. Let's start the debate!

**Comment by ObaniGemini** [comment]
just join daconcepts.com ...

**Comment by LeMagnesium** [comment]
If you with to add an irc server to xorhub, I could give you advices. We could also see with ShadowNinja, if our network is stable, if we could link with the rest of Inchra. That way we would still be on inchra but relying on our own server. Otherwise.. I doubt that having a whole network to us will be a very interesting solution.

Until then : **`daconcepts.com:6667 and daconcepts.com:6697`** to reach inchranet (I changed the code on our servers yesterday, I'm waiting for a merge)

**Comment by Ombridride** [comment]
Apparemmen qu'un serveur peut etre sur daconcepts.com, tous sont dessu et seul le premier serveur qui s'y conencte a sa place

`2016-05-30 09:27:33: ERROR[Server]: IRC: Connection error: daconcepts.com # until inchra.net is back: ...estforfun_skyblock/mods/irc_modpack/irc/irc/main.lua:87: host or service not provided, or not known -- Reconnecting in ten minutes...`

**Comment by crabman77** [comment]
Il y a un problème de parsage des "#",  irc ne doit pas ignorer vu que c'est utilisé comme argument.

> Connection error: digitalaudioconcepts.com # For when '*inchra.net' is down

**Comment by Ombridride** [comment]
Since the @crabman77 commetn, everything is fixed, thank you :)

**Comment by Ombridride** [comment]
I also re-merged all servers

**Comment by crabman77** [comment]
irc is still down 
> ERROR[Server]: IRC: Connection error: digitalaudioconcepts.com: ..main.lua:87: connection refused -- Reconnecting in ten minutes...

digitalaudioconcepts.com -->ERR_NAME_RESOLUTION_FAILED

from irc 2 days ago
> -Global- [Network Notice] ShadowNinja - Hello all!  InchraNet has a new domain!  The domain is inchra.chat, and you can use irc.inchra.chat to connect now.  Also, I've instituted a new vhost policy.  You can get a vhost by running /msg HostServ TAKE user/$account 

 Let's go back to irc.inchra.chat?

**Comment by Darcidride** [comment]
Someone can tweak the minetest.conf please ? i will merge this evening

thank you in advance !

**Comment by crabman77** [comment]
classic https://github.com/MinetestForFun/server-minetestforfun/commit/971147b48d4a3064996d163f2b2e134b08328b18
creative https://github.com/MinetestForFun/server-minetestforfun-creative/commit/8dfef5720b2ed93cbd0bdb5feef904e509f37295
skyblock https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/fc8720c17fb0f9dcafe28072b60bacc27a503be6
HG https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/9b2154b40b55fc696f1de5bff4fef55e44cffe3a

**Comment by Darcidride** [comment]
Thank you @crabman77

**Comment by Darcidride** [comment]
All servers are rebooted and up to date now, classic and SB are reconnected to the IRC

But the HG/Creative servers had a problem in the first connection to IRC : 
2016-12-02 22:52:05: ERROR[Server]: IRC: Connection error: irc.inchra.chat: ...ames/minetestforfun_hg/mods/irc_modpack/irc/irc/main.lua:87: closed -- Reconnecting in ten minutes...

Unfortunately, I can't follow this in 10 minutes, I will check it (& create tags for the merge) tomorrow
