### ISSUE TITLE
Auto replacement of blocks into the hand

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#462]
Take 1 stone brick alone into your hand, and keep a stack anywhere else into your inventory. 
Place your single stone bricks block. 
It is automagically replaced with the stack you had "anywhere else into your inventory".

Do the same with a with a default:tree
You have to choose by yourself the replacing stack.

I'm sure it's not the only affected block, but I don't have other examples. Could we make a rule to make sure it always happens as for bricks, for constancy?

**Comment by LeMagnesium** [comment]
It's some callback blocking the mod again.
*Mg goes away and curses to the heavens*

I'll investigate and fix that sh!t once more.

**Comment by crabman77** [comment]
@LeMagnesium Il faut rewrite la fonction, j'ai fait ce bout de code, par contre dans invtweak ça ne fonctionne pas, il faut rewrite dans default apparemment.

```
--minetest.rotate_node(itemstack, placer, pointed_thing)
local old_rotate_node = minetest.rotate_node
function minetest.rotate_node(itemstack, placer, pointed_thing)
	local stck_name = itemstack:get_name()
	local ret = old_rotate_node(itemstack, placer, pointed_thing)
	if not minetest.setting_getbool("creative_mode") and ret:get_count() == 0 then
		local index = placer:get_wield_index()
		local inv = placer:get_inventory()
		if inv:get_list("main") then
			for i,stack in ipairs(inv:get_list("main")) do
				if i ~= index and stack:get_name() == stck_name then
					ret:add_item(stack)
					stack:clear()
					inv:set_stack("main", i, stack)
					minetest.log("action", "Inventory Tweaks: refilled stack("..stck_name..") of "  .. placer:get_player_name()  )
					break
				end
			end
		end
	end
	return ret
end
```

**Comment by LeMagnesium** [comment]
>  il faut rewrite dans default apparemment.

Enlève juste le rotate_node, on s'en fiche après tout.

**Comment by crabman77** [comment]
bah c'est pas mal de nodes qui ont cette fonction à la place de place_node(), ça gère le sneak et tout.

> on_place = minetest.rotate_node

**Comment by LeMagnesium** [comment]
> ça gère le sneak et tout.

Ça ne gère pas le sneak, seulement le placement statique, qui n'a aucun intérêt pratique.

**Comment by crabman77** [comment]
si, la fonction appelle une autre fonction,
http://dev.minetest.net/minetest.rotate_node

> calls minetest.rotate_and_place() with infinitestacks set according to the state of the creative mode setting, and checks for "sneak" to set the invert_wall parameter.

**Comment by LeMagnesium** [comment]
I personally think we should open an issue about that and let the devs properly fix their own sh*t. It's their fault, and their problem if logging and other callbacks do not work. Who here agrees?

**Comment by crabman77** [comment]
+1 mais c'est invtweak qui se base sur le callback on_place_node pour vérifier l'inventaire, là je ne vois pas ce qu'ils peuvent faire a part faire un callback on_rotate_node.

**Comment by Ombridride** [comment]
+1 @LeMagnesium 
But we need to link the devs here :)

**Comment by Ombridride** [comment]
maptools : 
moretrees : 
multitest : 
quartz : 
homedecor : 
moreblocks : 
nether : 
default(minetest_game) :

**Comment by VanessaE** [comment]
This isn't something routine mods should ever have to consider.  Either you need to make a mod that wedges in before the rotate function to do what you're looking for, or make your changes at the subgame level.

**Comment by LeMagnesium** [comment]
> make your changes at the subgame level.

I would rather do that. Minetest's dev will apparently never find a way to go around their sh*tty forceful callback blocking system, so we'll have to fix on our repo.

And next time they complain about node placement not logged, I won't help.

**Comment by Darcidride** [comment]
Well, finally do we want to fix that on our own way or I closed this issue (players will be sad...) ?

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/3752bf2e645391afce10bdb7866406d03e95916d

**Comment by ElementW** [comment]
Moved to `_misc`: 947b3014566a611675435e3ceb6f7bc485c4199c

**Comment by HybridDog** [comment]
Can't you just simply make rotate_node call the registered on_placenode functions?
