### ISSUE TITLE
Class weapons bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#463]
![](http://i.imgur.com/iBIOaIm.png)

**Comment by crabman77** [comment]
c'est normal, moreores a été enlevé et mis dans default, tous les mod utilisant "moreores:*" sont dans les choux, le cas de pclasses.
Enfaite je viens de voir que ça a mis le bordel, parceque pleins de mods utilisent

> if minetest.get_modpath("moreores") then

**Comment by Ombridride** [comment]
Aïe, tu peux fixer rapidement s'il te plait ?

**Comment by crabman77** [comment]
heu on fait quoi pour fishing? vu que le mod est public  et fait pour moreores. si on l'adapte pour nous il ne marchera plus pour les autres, sauf si on se fait un branch pour nous.

**Comment by Ombridride** [comment]
Merde je l'avais oublié, est-ce qu'on aurait un moyen de lui dire :
si moreores mais pas de tools dedans, alors on cherche les tools de moreores dans default et on les ajoute ?
Ou encore, si moreores mais ne trouve pas les tools, met les tools avec "default:*"
ou quelque chose du genre ?

**Comment by crabman77** [comment]
depuis j'ai ce message au boot, enfait ça a cassé pas mal de truc je pense, 
>  WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition

les mod qui ajoutent des truc si le mod est présent, puis le mods qui font quelque chose en fonction du nom du node/tools.

**Comment by Ombridride** [comment]
Bon, ducoup on remet dans moreores, mais va falloir beaucoup modifier moreores, on a des valeurs bien particulière pour nos tools, et moreores n'es pas codé pour modifier les valeurs des tools

**Comment by LeMagnesium** [comment]
> Enfaite je viens de voir que ça a mis le bordel, parceque pleins de mods utilisent

On a pourtant mis des aliases, même sur les épées : 
https://github.com/MinetestForFun/server-minetestforfun/blob/master/minetestforfun_game/mods/default/aliases.lua#L89

Où peut être le problème?

**Comment by crabman77** [comment]
Oui mais les mod utilisent if get_modpath("moreores") donc il croient qu'ils n'est pas présent et pclasses enregistre "moreore:*" et check pour moreores:* sauf que le nom est default: .

je prend l'exemple de fishing, il n'enregistre plus de craft pour la perfect pole.
Soit on remet moreores, soit on fix tous les mods qui en ont besoin, mais pour fishing il faudra se faire une branche pour contourner.

**Comment by LeMagnesium** [comment]
Problem solved : https://github.com/MinetestForFun/fishing/commit/e3e58643661762fb4584d04d7d15cd239c6deacc

Maintenant revenons au problème de départ.
Je vais nettoyer le dépôt des traces de moreores.

**Comment by Ombridride** [comment]
Le sérieux problème c'est qu'il faut repasser sur tous les mods avec la méthode de mettes les tools/weapons de moreores dans default, ce n'est pas une bonne solution à mon avis.

Il serait mieux de remettre les tools/weapons de moreores dans moreores et de recoder la partie qui nous casse les pieds, nous n'aurons de ce fait pas besoin de toucher aux autres mods.

Je nous connais, avec de tel particularités, on va finir par faire des erreurs de partout... (suite à des updates)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/a364f64ab950ffe5e4c47d0a4af64c3638ece0cf

Trop tard, c'était plus simple de sed. En plus ce sont des mods évidents, avec des lists de loots ou des items particuliers qu'on connaît, les chances de se tromper sont minimes.

**Comment by Ombridride** [comment]
Ok, si c'est fix tant mieux, à voir dans le futur si l'on ne fait pas de bêtise lier à cela

En ce moment, je pense sérieusement à remplir le wiki avec une section "mods et specificity", qui permettrait de lister les particularités et choses à garder après chaque update/modif d'un mod.
Une sorte de doc interne de nos spécificités en soit, ce qui permettrait à chaque dev de checker que les points particulier soient gardés après chaque changements

**Comment by Ombridride** [comment]
Normally fixed, someone can test it and close the issue if it's ok please ?

**Comment by Ombridride** [comment]
Normally fixed, someone can test it and close the issue if it's ok please ?

**Comment by crabman77** [comment]
C'est bon les 2 épées warrior restent dans l'inventaire.
