### ISSUE TITLE
strange craft for books

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#464]
![capture](https://cloud.githubusercontent.com/assets/11613522/15807775/866eced6-2b66-11e6-9111-48929bd3f159.PNG)

**Comment by Cyberpangolin** [comment]
It's the server guide, really useful if you need to know about something. Not a book at all :)

**Comment by farfadet46** [comment]
yep sorry :/

**Comment by Cyberpangolin** [comment]
don't be sorry, asking someething is never a bad idea :)
