### ISSUE TITLE
we haven't any seed for this bushes ?

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#465]
![screenshot_20160605_214443](https://cloud.githubusercontent.com/assets/11613522/15807801/f438db96-2b66-11e6-9c8e-e1e177c5be91.png)
![screenshot_20160605_214529](https://cloud.githubusercontent.com/assets/11613522/15807802/f43dd920-2b66-11e6-9562-ee4ccef1f996.png)

**Comment by Ombridride** [comment]
No we haven't, maybe we can add them if you need it :)

**Comment by farfadet46** [comment]
yes for repopulate the grass please :) i love this bushes

**Comment by Darcidride** [comment]
@AcidNinjaFWHR 
Please , Can you do this task if you have time, of course ?

You can see with @LeMagnesium for some explanations if needed

**Comment by LeMagnesium** [comment]
I absolutely forgot I needed to do that. Fantastic, something to code.

**Comment by AcidNinjaFWHR** [comment]
@LeMagnesium is doing it ^^
