### ISSUE TITLE
we can't use the shift-click in darkage:box

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#466]
![screenshot_20160606_124427](https://cloud.githubusercontent.com/assets/11613522/15819612/87eabc9c-2be4-11e6-9374-c57f87a29104.png)
to put and get all items from and to the box

**Comment by Ombridride** [comment]
Well, need to improve the code to be 0.4.14 compatible with this kind of features

**Comment by Cyberpangolin** [comment]
!!! I didn't knew about shit + click! Sure I will use it in mass!

Maybe am I a bit greedy, but could we add to it that a shift + double-click switches as much stacks as possible of the chosen item? (very low priority idea though)

**Comment by farfadet46** [comment]
yeah but the minetest dev think it's too close from minecraft to implement this function in the core :/

**Comment by Cyberpangolin** [comment]
erf, I didn't know MC has such a feature, but if it does, it probably means it is a good idea ...

**Comment by Ombridride** [comment]
@Cyberpangolin 
You don't need to change our way of thinking, you need to change the way of thinking of the dev core team ;p
I totally agree with you, it's a good feature to add, but a feature like this can't be added with mods, it's core related

**Comment by Ombridride** [comment]
Thank you @crabman77
