### ISSUE TITLE
error in homedecors wood table craft

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#467]
i can craft stick about wood table but in very low quantity : 
![screenshot_20160606_182147](https://cloud.githubusercontent.com/assets/11613522/15829381/ddd617b2-2c13-11e6-9e6c-b58d14a094d5.png)

![screenshot_20160606_182157](https://cloud.githubusercontent.com/assets/11613522/15829379/daca614a-2c13-11e6-8af9-ace8fb1dbcff.png)

it's like if i want to craft a table ; i need round table the craft is 5 wood planks
to make a wood table it's 2 round table
if i put 3 wood table in craft i get only 4 sticks ??
i need 9 stick to get a wood planks

so homedecor isn't realy realistik :p
maybe you can just delete this craft :/

**Comment by LeMagnesium** [comment]
I just balanced them.
https://github.com/MinetestForFun/server-minetestforfun/commit/c0da57454544f237f5f94dac6dd5be8ddb31c684

1 * wood = 9 * stick
5 * wood = 15 * round
5 * 9 stick = 45 sticks = 15 * round
1 * round = 3 * stick
3 * round = 3 * 3 * stick = 9 * stick

2 * round = 2 * square
round = square = 3 * stick
3 * square = 3 * 3 * stick = 9 * stick

2 * square = 2 * large
square = large = 3 * stick
3 * large = 3 * 3 * stick = 9 * stick

Done.
