### ISSUE TITLE
Sapling craft recipe are hidden from normal players

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#468]
Sapling craft recipe are hidden from normal players

--------------------- NORMAL PLAYERS ---------------------------------------------- CREATIVE PLAYER -----------
![](http://i.imgur.com/0CFu1WU.png)

Aucun n'est craftable ? un craft similaire au SB me paraitrait une bonne chose (stick + 6 leaves du type de la sapling)

**Comment by Ombridride** [comment]
@LeMagnesium since your last commit, are all of the sapling added ?

**Comment by LeMagnesium** [comment]
Yep, they're all here : https://github.com/MinetestForFun/server-minetestforfun/commit/caa7a6ac8e0a97691f98f0c23bedf2d0b8957a3c
Can I close?

**Comment by Ombridride** [comment]
Closed, thank you for your reactivity @LeMagnesium
