### ISSUE TITLE
There is no visual difference between armor_stand

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#469]
in the craft-guide and in-game **the locked and the normal armor_stand** has the same texture :/

![screenshot_20160609_190530](https://cloud.githubusercontent.com/assets/11613522/15938855/3e94bb40-2e75-11e6-9093-19ebcec0f006.png)

**Comment by Ombridride** [comment]
Yes it's normal, the mod is made like that :)

**Comment by Ombridride** [comment]
We won't change this, if the mod upstream wants to change one of this texture, we will take it.
Linked @
