### ISSUE TITLE
Mod security breaking mods

### ISSUE THREAD

**Issue by LeMagnesium** [MinetestForFun/server-minetestforfun#47]
The rencently (this night) added mod security in minetest is a feature limitating mods' access to the system, its contents and features. It can be enabled this way : 

    secure.enable_security = true

However, some of our mods require access to the system and/or libraries. The most known example is IRC. Two mods are at the moment broken with this feature : IRC (for its libs) and apparently snow (it might be a bug, but it only appear with mod security enabled when it tries to load something in its path).
There is in fact two ways to make them work with the security feature. First, mods can require an unsecure environment with `minetest.request_unsecure_environment()`, and second, they can be added into a whitelist like this : 

    secure.trusted_mods = irc, snow

That's it.

# What we need to do :
 - ~~Update IRC~~
 - ~~Check for a fix on snow mod~~

**Comment by Ombridride** [comment]
Informations here : https://forum.minetest.net/viewtopic.php?f=18&t=12471&view=unread#p180948

**Comment by LeMagnesium** [comment]
I added a todo list related to what ShadowNinja advised people to do.

**Comment by LeMagnesium** [comment]
Have you added the line `secure.trusted_mods = irc` to the minetest.conf?

**Comment by Ombridride** [comment]
Just added now, effective for the next reboot of the server

**Comment by Ombridride** [comment]
So, the *secure.trusted_mods = irc* is activated, what should we do next ?

**Comment by LeMagnesium** [comment]
Update. Wait. Pray. That's it.

**Comment by Ombridride** [comment]
Done and it works for IRC mod.

After the next reboot of this issue, the server was booting normally. (just for the IRC mod)

The snow mod was added right now to the minetest.conf, we will see for the next reboot ! :)

**Comment by Ombridride** [comment]
Closed this issue.

The irc mod update will wait an another issue for an another problem :)
