### ISSUE TITLE
Mana sticks at 0 

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#470]
Event in the sunlight, it's impossible to have any mana point, at least as adventurer or hunter.

If they are supposed not to have mana anymore, I suggest to remove it totally from the HUD;
if it's only a loading mana bug, it needs to be fixed.

**Comment by LeMagnesium** [comment]
This is another of those insane cases of "works on local server but not on prod".
I have to find out why though.

**Comment by LeMagnesium** [comment]
I found my answer. It seems that mana's system saves the regen of players. If a player has ever been disconnected while under the earth, their regen will be at 0, and no code will bring it back to 3. @Ombridride  just needs to remove `mana.mt` from the world's directory.

**Comment by Ombridride** [comment]
I erased it, the next reboot will solve this issue.

**Comment by LeMagnesium** [comment]
I'll also work on a single-file-per-user storage system, since mana loads everyone's data (all players').
