### ISSUE TITLE
magasin fini, manque quelques petits trucs pour la mise en place définitive.

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#471]
![screenshot_20160612_011457](https://cloud.githubusercontent.com/assets/12512762/15987883/393996d0-303b-11e6-88cc-c4ff5ba6f2d8.png)

@Ombridride Voici donc notre petit magasin! 
Ce dont nous avons besoin, avec @crabman77 , pour terminer la mise en place:
- [x] un merge serveur (avec le reboot qui va bien :) )
- [x] le privilège shop (pour config le magasin)
- [x] un shared chest avec nous-mêmes dans lequel se trouvent au moins 50 minercantile: shop (a priori 40 seront utilisés) et 15 bancomatic (seront placés stratégiquement)

Coordonnées: -7 ;; 80

Merci beaucoup :)

**Comment by ObaniGemini** [comment]
Joli trvail !
Un peu trop flashy à mon gout mais quand même beau boulot :)

Sera-t-il assez grand ?

**Comment by Cyberpangolin** [comment]
On doit avoir dans les 700 m², ça devrait suffire.
Flashy? je dirais qu'il a un côté moderne, mais j'aime assez, ça change des trucs médiévaux / antiques qui font dans les gris-jaunes-rouges-noirs-bruns

**Comment by Ombridride** [comment]
Top, je serais là plus tard dans la soirée pour terminer tout ça ;)

**Comment by Ombridride** [comment]
Terminé.
