### ISSUE TITLE
Modifications of reboot script

### ISSUE THREAD

**Issue by LeMagnesium** [MinetestForFun/server-minetestforfun#472]
The following modifications were discussed and should be implemented in the reboot script :

 - [x] The killing method should be the following :

 ```bash
kill -2 $(pgrep 'minetest')
sleep 30
kill -15 $(pgrep 'minetest')
```
 - [x] All repository cloning should use `--depth=1` to (slightly) speed up cloning, and reduce data storage

**Comment by Ombridride** [comment]
Done and Done, the git clone xxx --depth=1 reduced drastically the number of file pulled ! (now 7000, before 41000)

Thank you for the suggestion

**Comment by LeMagnesium** [comment]
I just remembered that @cessna151 also proposed to move the hour at which the server update. Could we move it forward to 5AM (GMT+2)?

**Comment by Ombridride** [comment]
I scheduled the daily reboot to 6:31AM (the server is stopped between 6:29AM and 6:30AM)
The hypervisor VM backups are scheduled to 6:30AM

@LeMagnesium 
Can you tweak the shutdown messages/mod for the new reboot time please ?

**Comment by Ombridride** [comment]
Je te renvoi le ticket @LeMagnesium 

Le mod shutdown crsh le serveur à chaque message qu'il balance, voir cette issue : https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/137

**Comment by Darcidride** [comment]
Corrigé, je clos
