### ISSUE TITLE
menu classe intuitif

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#473]
créer un bouton dans l'inventaire, il aura pour but d'informer les joueurs sur les classes

Une fois le bouton cliqué, on a une présentation général du systeme de classe et 3 bouton :
Adventurer
Hunter
Warrior

Une fois l'un des 3 boutons avec le nom de la classe cliqué, une fenetre apparait pour présenter la classe, avec une ou deux petite images représentative

Une liste format texte d'avantage et d'inconvenient pour chaque classe est un plus

Si on a la place, on peu meme écrire une petite intro à la classe (un peu RP)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/09ed9098e7100c6170c0eac0cad5b5923243c45a

**Comment by Ombridride** [comment]
The fixes are perfect, i will merge this evening

**Comment by Darcidride** [comment]
It's merged. Looks really great.

but some things are missing, in my point of view :
- Some artistics pcitures, maybe some little weapons/armors on the corresponding class page 
- A picture of the worldmap to help players to find the class building corresonding to the class page

If you have more ideas, we're oepn

**Comment by Darcidride** [comment]
Up

**Comment by LeMagnesium** [comment]
I can't do any better with Minetet's inconsistent formspecs.
https://github.com/MinetestForFun/server-minetestforfun/commit/59c4c8e919183e9e45282b1ac0a8d74689f36f20

**Comment by Darcidride** [comment]
Great work @LeMagnesium i think it will be enough :)
