### ISSUE TITLE
Improve news formspec

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#474]
- [x] La fenêtre des news ne doit plus s'afficher à chaque connexion mais uniquement à la première connexion du joueur par semaine.
Exemple :
- Si le lundi le joueur ce connecte, la fenêtre apparait, si il ce reconnecte le samedi, elle ne s'affiche pas
- Si le jeudi le joueur ce connecte, la fenêtre apparait, si il ce reconnecte le vendredi, elle ne s'affiche pas

- [X] Un bouton sera mis à disposition dans l'inventaire avec un icône de "parchemin" pour envoyer à la fenêtre des news pour plus d'intuitivité.

**Comment by ElementW** [comment]
Implemented with another logic in 1f813060acfe132390196c063fb4b7568a058276 : only display news if they've been updated and the player hasn't seen the update yet.

**Comment by ObaniGemini** [comment]
Je donne mon avis :

Selon moi les news ne devraient apparaitre qu'à la demande des joueurs, c'est à dire en faisant la commande */news*, chose qui serait expliquée dans une des astucs du server (les joueurs s'intéressant aux news ne sont pas la majorité, et ils savent généralement taper une commande minetest).
De ce fait, pas besoin d'encombrer u_inv d'un nouveau raccourci, il est déjà bien rempli comme ça.

Je suis contre un timer qu'il soit d'une semaine ou d'un mois car la majorité des joueurs ne se connectent pas souvent et l'écran de news fait plus l'effet "pop-up de pub" ou "accepter les conditions d'utilisation" et on se sent obligé de le fermer, d'abord parce que sa longueur n'invite pas à la lecture, deuxièmement parce qu'il apparait à la connexion et qu'il arrive souvent qu'on ne soit pas en bonne posture pour lire un pavé à ce moment là.

**Comment by Cyberpangolin** [comment]
Ce sujet méritait largement d'être abordé.
Petite suggestion: Rajouter en gros le mot NEWS à côté de la bannière, pour que les gens ne voyent pas un "pop-up de pub".

et Merci à @ElementW d'avoir mis ça en place, je me réjouis de voir ingame!

**Comment by ObaniGemini** [comment]
Je n'ai pas dénigré le travail de @ElementW, je tenais juste à retranscrire ce dont on avait parlé sur IRC et que tu n'as pas mentionné @Ombridride.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/6a310d9f8d1b438157f4d5fc773d42cbc7c411a4
There you go, your little button.

**Comment by Darcidride** [comment]
This issue is done, thank you for your work
