### ISSUE TITLE
[Domain] minetestforfun.com 

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#476]
The domain named "minetestforfun.com" will expire in less than 7 days, we really need to replace all occurrences on :
- [x] All of our servers
- [x] Forum presentations posts
- [X] IRC welcome messages/descriptions => Done, SB was the only one with mff dot com still in its topic
- [x] Website
- [x] Github repositories => https://github.com/MinetestForFun/server-minetestforfun/commit/0f90032b485347efa5c81173596b06f7f5184117 They're all clean now
- [ ] @Cyberpangolin youtube description page

"http://minetestforfun.com" == to ==> "https://xorhub.com"

**Comment by ezamlinux** [comment]
@Cyberpangolin don't forget to change the link on your Youtube videos

**Comment by Cyberpangolin** [comment]
It will need some time... but I will at least for the next ones.

**Comment by Ombridride** [comment]
We are waiting you for closing this issue @Cyberpangolin, take your time ;)

**Comment by Darcidride** [comment]
@Cyberpangolin I will now close this issue, think about your Youtube descriptions :)
