### ISSUE TITLE
we can cook all items in locked furnace but get nothing

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#478]

**Comment by Cyberpangolin** [comment]
Maybe that could give something related to lava, that could be crafted with a bucket to make a lava bucket?

**Comment by LeMagnesium** [comment]
I can't cook stone, and I have no record of stone being cooked into another node.
What's the issue here?

**Comment by farfadet46** [comment]
if i put a stone in a furnace, the stone is destroyed
PS i use my locked furnace (i don't know if this information is necessary)

**Comment by farfadet46** [comment]
yes there is fuel, and i see an ultra-fast "arrow animation" (when the stone is burned) the stone are destroyed ultra-fast too

**Comment by LeMagnesium** [comment]
Where is that furnace? Have you tried with a new one?

**Comment by farfadet46** [comment]
the furnace is at my factory / home, if i put a cobble, it' use a coal and if i put a non burnable item when the flame is on, the item is burned .
if i put the same item without flame, it's not burned

**Comment by LeMagnesium** [comment]
Can you try to destroy it and put it back?

**Comment by farfadet46** [comment]
after replace the locked furnace, same problem, wen the furnace is active, it don't check if the item can be smelt or not, if not, the item is destroyed.

**Comment by Darcidride** [comment]
Up, Is this issue fixed ?

**Comment by LeMagnesium** [comment]
> Up, Is this issue fixed ?

I don't even understand fully what is the issue and whether or not there is one. Everything works fine for me on both the server and my local instance of it.

**Comment by Darcidride** [comment]
Well, i close this issue, @farfadet46 will reopen this issue if the problem is still here.

**Comment by AcidNinjaFWHR** [comment]
I just tested on the server and he's right.
Once my locked furnace was cooking some corn and it finished, I just put some random stuff, a wool in it while the fire was still active, and it just disappeared ! ;)

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/6d5a0d10560bb8d89667912e7dd7a5288a4c55d4

**Comment by Darcidride** [comment]
@crabman77 
Thank you for your work
This fix need to be pushed on all of our servers (except HG)
