### ISSUE TITLE
Add BIG mountains to the server (with WE)

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#48]
Take some mountains (2 or 3, maybe 4 ?) of this mod and add them to the server (with Worldedit)

Look at here for more informations : https://forum.minetest.net/viewtopic.php?f=11&t=5159&hilit=mountain)

The shematic is too big, we can't save it...

**Comment by LeMagnesium** [comment]
I have created a beta map format (raw text atm) able to be loaded/applied onto enormous areas without any single variation on the RAM occupation (on a Mb basis). I will improve it because.. well.. One node takes at least 12 characters.

**Comment by Ombridride** [comment]
Maybe it helps ? https://forum.minetest.net/viewtopic.php?f=9&t=12011&view=unread#p177396

**Comment by Ombridride** [comment]
This update was added to the server, maybe it grant us the possibility to copy mounstains now ?
We need to retry...

**Comment by LeMagnesium** [comment]
Here is my advise : 
 - Shut the server down.
 - Restart it.
 - Go on it, load only the amount of terrain you need
 - Start the load of mountains
 - Pray while your RAM is being eaten for the server not to crash

The first reboot is needed to save datas before crashing it. Indeed, crashing a server with WE doesn't trigger the shutdown callbacks : compassgps' datas are lost for last uptime duration, same with pyramids' chests, ...

**Comment by gravgun** [comment]
Switched to Watershed mapgen (#118) which *does* generate big mountains.

**Comment by Ombridride** [comment]
Not really, the mountains in the __meru__ "part mapgen" mod are 2048 + nodes !
In the other hand, the __wathershed__ mapgen is great for small mountains like a 128 max height ;)

So, the goal of this issue is to add at least 1 meru mountain, but we can add 2 or 3 mountains for more diversity

**Comment by ObaniGemini** [comment]
@Ombridride : How would it be added ? With WE it would take too long or make crash, so does a command line exist for that?

**Comment by Ombridride** [comment]
@ObaniGemini 
It's because this Issue takes so long, we need a way to add this mounstains without crash the server ;)

**Comment by ObaniGemini** [comment]
Maybe should you add a code line to set a placement instead of place it randomly on the map?

**Comment by Ombridride** [comment]
@LeMagnesium and @crabman77 
Can you explain your last discovery about your SQL_extractor script ?

**Comment by LeMagnesium** [comment]
SQLextract is a script created by crabman and improved with the help of @gravgun . It extracts informations from a SQLite3 rollback database and create a list of actions to do for the ROFL mod to apply lost actions on an old backup of a map, or a singlenode map. So if you wanna use it, turn on rollbacks logging, build the complete mountain, and we will apply the whole process with the rollback file.

**Comment by Cyberpangolin** [comment]
Now we have big amounts of land generated, maybe we can add the meru mod, but with a really tiny chance to have one. say 1/102400000

if we have a 32k * 32k map, and if my calculation is correct, it means we should have approximately 10 of them on the map, which sounds good.

Just hope this script doesn't kill the serv ;).

**Comment by LeMagnesium** [comment]
@Cyberpangolin do you have a link to that meru mod please?

**Comment by Ombridride** [comment]
@LeMagnesium 
First post : https://forum.minetest.net/viewtopic.php?f=11&t=5159&hilit=mountain

We don't want to add the meru mountain mod to our server because it's a lua mapgen mod, it's too heavy...

We just want to import some of the mounstains...

BUT, your solution isn't ininterrested and maybe we will finally add it... We will discuss about this solution.

Otherwise, Good idea ;)

**Comment by Cyberpangolin** [comment]
Thanks :)
Yes, it will slow down the game during the generation, but I think it's not that long compared with server's lifetime. In the worst case we'll lose 5 minuts, and then it should come back to a normal speed. Or maybe we could slow down the lua generation script with a "sleeping" time of 0.5second every second, or 0.1s every pass in a big slow loop. I dont'know if it's possible but it could drastically remove lag. In counterpart it would slow down generation, so we should balance it to make sure exploration is still a challenging adventure.

Note: this could apply to the world generation script, or to heavy ressources-eating rares mods only. In both case I think it would be a progress.

**Comment by Ombridride** [comment]
Up, can someone give his opinion about the @Cyberpangolin solution ? I need dev reviews

**Comment by LeMagnesium** [comment]
@Cyberpangolin's idea is to either add a mod and generate one giant mountain, whatever time we may spend to it, or otherwise to put all the placement in a buffer and place nodes, let's say, 1000 per 1000.
A mod generating a mountain at a specific position is still the best way to do that.
I'll tweak the mod he proposed to spawn a mountain at a specific position.

**Comment by LeMagnesium** [comment]
@Ombridride, give me a range of coordinates between which I could make meru generate a mountain (like 1025,1000; -900,-200, etc)

**Comment by Ombridride** [comment]
Give you areas coordinates for generated a meru mountain is difficult because :
- we need to generate meru mountain is each biome (so 4 to 6 i think)
- if i give you coordinate already generated to be sure i give you area with a certain biome, you won't can re-generate into this area...
- If i give you coordinates not already geenrated, you will maybe generate a meru mountain in water, for example...

Finally, we need tests... (and speak about this possibility on IRC for better understanding, and we will post our conclusion here)

**Comment by LeMagnesium** [comment]
You can give me coordinates or areas already generated because **you can /deleteblocks** and it will generate the same biome, same nodes, except the meru mountains. (but they will be made out of either `meru:stone` - stone - and `meru:destone` - desert stone)

**Comment by Ombridride** [comment]
Bad news, we need to implement aliases with our ressources !

**Comment by ObaniGemini** [comment]
Is it a problem if it is generated in water ? I don't think so :)
The idea is to have mountains generated in random pos, for we can find them everywhere :)
(Also, if they are generated, can there be hidden chests in it ?)

**Comment by Ombridride** [comment]
@LeMagnesium 
Can you give me a clear step by step guide for create a Meru mountain on an already generated map ?
Thank you in advance, it will do it ASAP, this issue is too old ! (and I will generate some Meru mountain)

**Comment by LeMagnesium** [comment]
> create a Meru mountain on an already generated map ?

Easy version: Wipe the map away
Detailed version :
 * pick a location
 * configure meru with a tight radius around those coordinates
 * use /deleteblocks here to spawn chuncks of the meru mountain
 * repeat about 200 times to get a structure about 160 tall
 * the full meru mountain is actually closer to 2048 in height ; repeat deleteblocks until you reach ungenerated areas
 * you should have a pretty good meru mountain

Note: It was never tested, probably doesn't work.

**Comment by Ombridride** [comment]
Ok, thank you
It clearly needs a test on the dev server or locally... I will not do this in production server if it's not 100% working :)

**Comment by LeMagnesium** [comment]
I'm currently making tests to import a meru schematic (extracted from @Cyberpangolin's Chlorine server). If it works successfully we might consider using the Python script on Classic's map..

**Comment by Ombridride** [comment]
Une d'ajouter, ça suffira, je clos
