### ISSUE TITLE
Mushrooms and protected areas

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#483]
For esthetic purpose, i think the mushrooms spawn inside protected areas should be deactivated 
(lava mushrooms are for exemple pretty boring if you put lava inside protected areas)

**Comment by ezamlinux** [comment]
good idea, maybe make the same for cow dump ? (if possible)

**Comment by Ombridride** [comment]
Well, cow dump should be a good fuel, why do you think it needs to be removed ? Maybe, there is too many cow dumps in your protected area ?

**Comment by ezamlinux** [comment]
my house is on a small island on which I picked up over 20 (while killing all the cows) in 2 days ( in game )

**Comment by Ombridride** [comment]
Well, maybe we can reduce the spawnrate of dung by 10 and increase the fuel rate by 10

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/178be5eb469400530ffb2f692eda42bff2e9db78

**Comment by crabman77** [comment]
fixed dung rate https://github.com/MinetestForFun/server-minetestforfun/commit/fae4d838ea7d2c729f61edafc2ec165c2bdfd627

**Comment by Ombridride** [comment]
Thank you @crabman77 :)

**Comment by HybridDog** [comment]
Lavashroom is from riesenpilz, not from flowers.
Anyway, you could make an electric fence mod. It avoids cows to spawn near it and they don't jump over it.
```
 _____________________________
< I don cross se thunda fenz! >
 -----------------------------
        \   ^__^
         \  (oo)\_______/\/
            (__)\       )
                ||----w |  m
                ||     || mmm
```

**Comment by ObaniGemini** [comment]
@HybridDog : cowsay ? :)
