### ISSUE TITLE
Suggestion ajout d'un home supplémentaire

### ISSUE THREAD

**Issue by Coethium** [MinetestForFun/server-minetestforfun#486]
Bonjour ;-)

Tout nouveau sur le serveur, je me permets d'apporter une suggestion :
Actuellement il y a 2 accès rapide de téléportation home et pit, si je ne compte pas le spawn. Il pourrait-être intéressant d'ajouter également un troisième (par exemple build).

Bien évidemment il est possible de modifier régulièrement le home ou le pit, cependant on peut souhaiter avoir un home fixe (avec son petit lit douillet, ses coffres etc, ...), un pit qui change peu (surtout quand on a atteind les -2000, on a peu envie de recommencer :p), mais du coup on se retrouve freiné si on veut faire de grosses constructions éloignées du spawn/home/pit. 

Un troisième lieu rapide (build) favoriserait, je pense, la construction sur une vaste étendue de la map.

Qu'en pensez-vous ? :)

**Comment by ezamlinux** [comment]
Même si je suis d'accord dans le fond, je ne pense pas que cela soit une bonne idée.

Il faut savoir que le 'pit' est arrivé récemment, afin de répondre à un premier besoin. Avant il n'y avait qu'un Home et l'on trouvait cela trop 'juste' donc un deuxième accès rapide fut ajouté. 

Si ton souhait est de pouvoir Builder loin de chez toi, sache qu'au spawn, à l'étage, tu a 4 cristaux de téléportation te permettant de te rendre aux 4 coins de la map. Cela peut te permettre de t'éloigner suffisamment de la 'Mégalopole' pour réaliser tes projets sur des "terres vierges". Grâce aux cristaux nous disposons enfaite de 7 accès rapides ( Le Home, le Pit, le Spawn et ses cristaux).

Après, cela reste mon point de vue. ;)

**Comment by Ombridride** [comment]
@ezamlinux 
Je suis d'accord avec toi, c'est suffisant.

@Coethium 
Pour moi, ton besoin correspond plus au **Return Mirror** (ou _mobs:returnmirror_)
Cet objet craftable ou droppable sur les **Mese Monsters** te permet d'ajouter un point et de t'y téléporter en échange de points de **mana**
Clique droit pour "définir" le point, et clique gauche pour "ce téléporter au point défini"
