### ISSUE TITLE
About braking rails

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#496]
ATM braking rails seem to remove a fix speed value until you stop. I suggest to simply to remove their effect if the cart speed is the lowest (ie: punch speed), it would be a big improvement.

- Why?, will say some random reader
- Because we have now really fast carts, so we need a way to be the fastest possible, brake a lot for the intersections so we can choose where to go without any trouble, then pass the brake rails for people coming from where you are going to, and the re-accelerate.

scheme: (light grey = normal rail; yellow = accelerating rail, useless when you are incoming because you are already at the may speed; hard grey = brakiong rails)
Up, what we have now. We have the choice between braking less than half your speed and keep moving too much to make a choice, or to put too much braking rails and stop

![cartscheme](https://cloud.githubusercontent.com/assets/12512762/17399708/e476129e-5a43-11e6-8b54-1194910ca8dd.png)

Down, what would happen with this correction: you slow down a lot, then you choose and turn, then you can re-accelerate after passing the brake rails.

Without this correction, all intersections must be done as much times as the number of ways you have if you want to make a choice correctlty, OR you have to stop, remove your cart, change your way, and then return on your cart, which is not that user friendly.

If really needed, maybe we could add a red stopping rail which would be the current braking rail, but I cannot imagine where they could be useful since you can simply end the railway to stop a cart.

**Comment by Darcidride** [comment]
The "brake" feature of cart mod has always been random in my point of view.

Add a new rail to totally stop the cart and wait an arrow key before send the cart in this arrow direction seems good to me.

**Comment by Coethium** [comment]
Or no need to add a new rail : the cart can stop when it detects a junction, and waits for the key.

**Comment by Darcidride** [comment]
Well, it's a possibility, but it can also be a problem, the benefit of the actual features is we don't need to do anything with our keyboard if we take a rail way only for the "main" path, with your solution, anyway we want the main path, if we met a junction, we will need to push a key.
I also think about your solution but didn't post it for this reason.

Or maybe it's what players waits/wants ? in this case let's do this

**Comment by ObaniGemini** [comment]
@Coethium : this would make the creation of roller-coasters impossible and would make places witrh many crossed railways really unconfortable

**Comment by Cyberpangolin** [comment]
I would really prefer to avoid the stops at crossings: it would be painful if we once have a big network.
Adding a slowing limit to the brakes seems to me really better.

**Comment by Coethium** [comment]
@ObaniGemini @Darcidride  Ho i see now why a new rail is better than modifying crossing rail !
@Cyberpangolin Seeing your picture, it could also be possible to add a new rail : power_brake
![carts_rail_pow_brk](https://cloud.githubusercontent.com/assets/20361482/17456641/3501ffba-5bdf-11e6-90d3-b693824bf107.png)
Acceleration/Brake depends of the direction of the cart.

**Comment by Darcidride** [comment]
@Coethium 
Let's do something simple, don't add this kind of "double features" rails, this is a bad idea, the server is already enough complicated...

I think we just need to increase the "brake/stop function" of the brake rails (let's double it, for tests, maybe it's enough)

**Comment by Coethium** [comment]
@Darcidride Ok, so you mean one brake rail (lowering speed but no stop) and a stop rail (hard stop the cart) ?

**Comment by Darcidride** [comment]
For the moment, let's keep the brake rails, but let's increase the decrease speed

**Comment by Cyberpangolin** [comment]
@Darcidride the thing is: if the brake rails don't let you pass at the slowest speed, they are useless to me.

**Comment by Darcidride** [comment]
In this case, maybe we can set a "speed value" for the brake rails, enough slowly to grant you the change direction possibility when you met crossing rails, is this solution correct for you ?

**Comment by Cyberpangolin** [comment]
Seems the best solution to me :+1:

**Comment by Darcidride** [comment]
Works great since the cart/rail patch from @Coethium thank you agian for your work @Coethium ! :)
