### ISSUE TITLE
Small cart improvments

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#501]
Good job @Coethium, the carts mod is now near perfect and not bugged at all ! :)

- [x] Reduce a little bit carts max_speed, 5/10% seems good in my point of view, the problem is the carts are too fast, we are back-teleported sometimes
- [x] Removed velocity from carts objects when we leave it, indeed, it's not useful when we leave our carts to see him run away :D

**Comment by Coethium** [comment]
I'll see the second ask later ;-)

**Comment by AcidNinjaFWHR** [comment]
I'd like to suggest another improvement

- [ ] make unable to send an empty cart when punching
- [ ] make unable a third person to punch the cart to make it go while a cart is occupied (only the driver would be allowed to do that)

**Comment by ObaniGemini** [comment]
:+1: @AcidNinjaFWHR : In clear, just allow the player inside the cart to start the cart.

**Comment by Darcidride** [comment]
@AcidNinjaFWHR @ObaniGemini 
It's already the case, just punch (="left click") the cart with your hand (naked, without any items in your hand) and it will work ;)

**Comment by Coethium** [comment]
@Darcidride second request done, I let one of you merging the pull into the upstream because i don't already know how you're doing tests.

@AcidNinjaFWHR @ObaniGemini the cart can now only be punched by the driver.

**Comment by AcidNinjaFWHR** [comment]
Awesome.

**Comment by Darcidride** [comment]
Perfect, thank you @Coethium, our carts mod is perfect now :D
Never seen this before on Minetest !
