### ISSUE TITLE
crash mesecons

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#504]
http://zerobin.qbuissondebon.info/?72023736319efcaa#rDkPvV+Po6Y4s3EHukm80J9ElzG21H1Y9P9bMxWZBW0=

**Comment by Coethium** [comment]
Seems not to be a mesecons issue : 
Mesecons justs call a Step function (to place a tree). But mods/default/nodes.lua:623 expects the function sapling_on_place(), not defined.

I found this, the function was created 28 days ago on minetest : 
[https://github.com/minetest/minetest_game/commit/0ac096991c51d664007ebb53b8117baca0271459](url)

Our mods/default/functions.lua file is not up-to-date with the corresponding mods/default/nodes.lua.

**Comment by crabman77** [comment]
fixed, merge needed.

**Comment by Darcidride** [comment]
Merged
