### ISSUE TITLE
rofl mod

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#505]
@LeMagnesium 
Why this mod isn't enable in the world.mt ? 
![](http://i.imgur.com/cKEKfCj.png)
Please enable it if needed

**Comment by LeMagnesium** [comment]
We don't nead that mod anymore since it was meant to apply the extracted rollbacks to recover MFFv1's map, and execute large copying/saving operations on the map, but libminetest was later designed to do it more efficiently..
I'll clean it up.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/ca10667a1fa9941a7fba1efebde2f21ab94ab1bf
