### ISSUE TITLE
Change creeper's way to work to a more classic way

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#509]
Actually, creeper's exploding timer is disabled if player moves away from him.

The idea would be to start the timer, and to let the creeper explode even if the player is away, as the classic creeper does, which lets the player dodge him.

**Comment by Darcidride** [comment]
To do something simple (easier to maintain), @LeMagnesium & @crabman77 can you give me you opinion about this little tweak : 
`
-- stop attacking if player or out of range
if not self.attack
or not self.attack:getpos()
or self.attack:get_hp() <= 0 then
`

The creeper explode attack is from here https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L1483 to here https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L1658

**Comment by crabman77** [comment]
No it's for all mobs.
 > if dist > self.**view_range**  (si ne le voit plus)

creepers attack start there -> https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L1509

He stop attack there -> https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mobs/api.lua#L1529

> if dist > **self.reach** then (si n'est plus à portée)

**Comment by ObaniGemini** [comment]
This part of the API will affect not affect any other monsters from what I see (excepted to pumpbooms maybe, which is not a problem).
Another tweak then would be to start the timer to closer to the player, for it doesn't become a non-dangerous mob

**Comment by Darcidride** [comment]
@crabman77 It's only for all monsters with the attack type 'explode', if i understand well the API

**Comment by ObaniGemini** [comment]
:+1: for the fixed value.

**Comment by LeMagnesium** [comment]
@Darcidride The range factor won't be hardcoded, there is one variable for that already.
Also, why would you divide the range?

@crabman77 I did the modification, I hope I didn't butcher the code.

**Comment by crabman77** [comment]
@LeMagnesium j'ai un doute sur la 1ere condition, c'est pour tous les mobs,  peut être la remettre et ajouter

> and not self.attack_type == "explode"

sinon les autre mobs risquent de ne pas s’arrêter, si un 2ème joueur passe à coté et que le 1er s’éloigne, le mobs ne changera pas de cible.
https://github.com/MinetestForFun/server-minetestforfun/commit/327694b4ea53865be389afcba4d6ff1ebac51575#diff-1a9bf31b6ac84ce577d3d5bd5a8c2adbR1483

**Comment by LeMagnesium** [comment]
@crabman77 Et là?
https://github.com/MinetestForFun/server-minetestforfun/commit/7ddebddee284d1089653fdc03d8fc65f349a876c

**Comment by crabman77** [comment]
Oui je pense que c'est bon.

**Comment by crabman77** [comment]
Je crois que le changement a apporté un bug, les pumboom se mettent à exploser a plusieurs nodes(10) de distance maintenant, dès qu'ils nous voient ils explosent au lieu de venir vers nous et exploser au plus près.

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/6fd2c789a6a1c7b081811520fc56fb7e9c600da4

**Comment by Darcidride** [comment]
Thank you @crabman77
