### ISSUE TITLE
problem with some class recipes

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#511]
![](http://i.imgur.com/5fuzBBl.png)
gauche = joueur classique
droite = admin

Les objets de craft de classe + certaines armes/armures ne sont plus visible par le joueur classique

**Comment by crabman77** [comment]
Pour l'épée c'était une typo, pour les 3 autres sur le screen c'est normal, ils n'ont pas de craft, seul l'admin peut les voir (fonctionnement de unified_inventory, surement le privs "give" qui permet de les afficher).

**Comment by Darcidride** [comment]
Ok parfait, merci pour le fix @crabman77
