### ISSUE TITLE
home/pit

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#515]
@Cyberpangolin 
Reported the /home and /pit commands doesn't work anymore, i tried them and it works in my case. Can you give us more information about your issue @Cyberpangolin ?

**Comment by crabman77** [comment]
C'est le bug des after perdu de Profnsched, action_timer ne fonctionnant plus a ce moment là, vu avec @Cyberpangolin quand on a découvert le bug, il l'avait report une semaine plus tôt.

**Comment by Darcidride** [comment]
Ok parfait, merci pour la réponse
