### ISSUE TITLE
Les saplings et les blinky plants ne fonctionnement plus

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#517]
j'attends désespérément de voir un default:sapling pousser depuis plus de  12 heure sans succès. par contre, le serv et mon client ont crash (séparément) quelques fois, ce qui me fait me demander si ce n'est pas lié.

À coté de ça, les blinky plants ne blinkent plus du tout (meme après enlevage-reposage), et j'ai repéré un four qui reste allumé en permanence, sans bouger dans le temps. je me demande donc si le tout n'est donc pas lié à un timer en panne.

voilà voilà... :)

**Comment by crabman77** [comment]
Je viens de tester les blinky et elle fonctionnent, le timer est de 7 secondes.

**Comment by crabman77** [comment]
Y avait un souci avec les trees, mauvais update https://github.com/MinetestForFun/server-minetestforfun/commit/96dea33e89fefe7944ba0bbb3eb9b655ef50a84e

Par contre les schematics ont un souci, il y a une seule épaisseur de feuilles qui est posées, mais @LeMagnesium est plus compétant que moi pour ça.

![conv-trees](https://cloud.githubusercontent.com/assets/7189389/20861235/29999c00-b98b-11e6-8c89-adfcc4972f1a.jpg)

**Comment by LeMagnesium** [comment]
Il y en a deux chez moi (arbre au centre). C'est le nouveau schematic des trees qui est comme ça. Je peux toujours le rollback vers une ancienne version.
![screenshot_20161204_161013](https://cloud.githubusercontent.com/assets/6785985/20867074/6b1d889c-ba3c-11e6-8913-0dc363eaf802.png)

**Comment by LeMagnesium** [comment]
Par contre je dois utiliser un bonemeal pour faire pousser les arbres depuis ma station aérienne. Je vais aller enquêter sur ça...

**Comment by Darcidride** [comment]
Si c'est les nouveaus schematics, je pense qu'il vaudrait mieux suivre les nouveaux default trees, merci pour le fil de discussion :)

**Comment by Cyberpangolin** [comment]
oh, ca m'intéresse, faudra que je les voie! :+1:

**Comment by Cyberpangolin** [comment]
Je double-post pour l'update: @crabman77 il semble qu'il n'y a plus de crash, par contre mon sapling (je l'ai cassé et reposé) n'a toujours pas daigné pousser, après 14 heures de temps.

**Comment by Cyberpangolin** [comment]
Ok, il était juste lent. Merci pour les corrections :+1:
