### ISSUE TITLE
scraper pas craftable

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#518]
0. assurez-vous d'avoir 4 steel dans votre inventaire
1. cherchez "scraper" dans le guide
2. cliquez pour en crafter 1. Il faut, pour cela, 3 steel en ligne horizontale, et un au dessous au milieu.
3. constatez: l'item est dans le guide, mais le craft ne produit rien.
4. pleurez un bon coup
5. faites un report sur github :+1:

**Comment by ObaniGemini** [comment]
noraj de ton reportaj. Sympa de te voir de retour dans le game :)

https://github.com/MinetestForFun/server-minetestforfun/blob/0baa0ea091695fdcfe4d25e6437613b2f79634ac/mods/multitest/crafts.lua#L68

Il faut un "handle_grip" d'après le craft. Peut-être que cet objet n'existe pas/plus ou n'as plus de textures ? @crabman77 , @LeMagnesium

**Comment by crabman77** [comment]
non l'item est bien là mais peu visible.

![scrapper](https://cloud.githubusercontent.com/assets/7189389/20893433/0f085a24-bb12-11e6-8cdc-0a2264c42cf9.png)

**Comment by Darcidride** [comment]
@Cyberpangolin 
Tristement peu visible car gris foncé sur gris foncé, mais on te promet que ça fonctionne :3

**Comment by ObaniGemini** [comment]
@Cyberpangolin : si tu veux faire un inventaire des textures d'inventaire devant être réinventées, c'est une bonne idée pour un autre ticket

**Comment by Cyberpangolin** [comment]
Hihi merci, j'avoue que je ne l'ai VRAIMENT pas vu :p
