### ISSUE TITLE
way too much bosses in their rooms

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#524]
With @ObaniGemini and sys4 we went into the pumpking and the mese dragon rooms.

-> there were way too much mobs (say more than 20), including 3 to 5 bosses. lag was making the game unplayable.

-> suggestion: double or triple check that there are no more than 1 boss and X (10?) mobs with it before spawning more of them.

**Comment by ObaniGemini** [comment]
I got a nother suggestion :
Clean the room when someone teleports to the area. I would make a special teleporter entity similar to warp to trigger this event, it would probably be better than a loop checking, and better for players.

Also, Minetest has up to 31000 blocks height. Why are the arenas so close to the ground ?

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/62fbe19f100c64ced4127f4c446ab52adc37f249
