### ISSUE TITLE
[mesecons] Microcontroller(FPGA) has same craft recipe than LUAController

### ISSUE THREAD

**Issue by sys4-fr** [MinetestForFun/server-minetestforfun#528]
Actually Microcontroller (aka FPGA) has same craft recipe than LUAController:

![recipe1](https://cloud.githubusercontent.com/assets/16238157/23822975/42d4b410-0658-11e7-85db-7233208b1683.png)

The Microcontroller should have the following craft recipe:
![recipe2](https://cloud.githubusercontent.com/assets/16238157/23822988/6a84379c-0658-11e7-96f6-b901e9cb0f83.png)

**Comment by ObaniGemini** [comment]
Just change this and get good https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/mesecons/mesecons_microcontroller/init.lua#L145

**Comment by Darcidride** [comment]
I gave my approval for the merge of the PR, thank you @sys4-fr
