### ISSUE TITLE
Piratage (Mynetest et Axinite) par WE_gui

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#534]
Dans la nuit, Mynetest et Axinite ont été piratés par une attaque LUA par WE. Le pirate a ajouté un mod sur le serv qui refuse toute connexion de joueur. Il a effacé debug.txt. WE_gui a une faille qui permet d'exécuter du code LUA sans priv. Elle avait été corrigée la veille... [Issue Mynetest avec emplacement et contenu de son mod](https://github.com/Mynetest/Mynetest-server/issues/107)

Le [thread des mesures contre cette attaque](https://forum.minetest.net/viewtopic.php?f=18&t=17601) est sur le forum Minetest.

Sur Mynetest, le pirate est revenu après le premier nettoyage du mod d'autokick on prejoin qu'il a installé. Il a kick les joueurs présents. Il a effacé 2 fois debug.txt et meme environ deux heures de l'archive des logs de l'IRC.

**Comment by Darcidride** [comment]
Salut,
merci pour la remonté d'information, on a été touché sur MFF-SB par le même soucis, sauf que le mod security n'est pas activable dans notre cas (à cause d'IRC), mais on fix tout de même

**Comment by ObaniGemini** [comment]
@mgl512 : merci de penser à ceux qui "restent "^^
