### ISSUE TITLE
touche entrée dans la recherche de craft quitte l'inventaire

### ISSUE THREAD

**Issue by matt8fr** [MinetestForFun/server-minetestforfun#535]
si on appuis sur la touche entrée après avoir tapé du texte pour faire une de craft dans l’inventaire, cela ferme l'inventaire.

**Comment by LeMagnesium** [comment]
Il n'y a rien à faire. Ce n'est pas un bug, c'est comme ça que le jeu traite les menus. Je ne peux même pas empếcher le menu de se fermer quand la touche entrée est pressée.

**Comment by matt8fr** [comment]
bizarre sur Eurythmia la touche entrée lance bien la recherche. merci quand-même d’avoir regardé.

**Comment by crabman77** [comment]
Apparement y a un truc pour empêcher un field de fermer le formspec quand on appuie sur entrée.
https://github.com/minetest-technic/unified_inventory/commit/2ea417fad0e09c43b1e3ad31924eb2d27b8876f6
par contre je peut pas le commit, là je suis sous windows et mes hdd linux sont débranchés.

**Comment by LeMagnesium** [comment]
Fixed it. https://github.com/MinetestForFun/server-minetestforfun/commit/12ee8c9dc9afc1be8b3ee322bf520b81b74f8604

**Comment by Darcidride** [comment]
Well done @LeMagnesium
