### ISSUE TITLE
MinetestForFun Logo

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#54]
Great news, thanks to the work of Obani, we are going to have our own Logo !

![Logo4](http://i.imgur.com/uOazXA5.png)

But it's still Work in Progress, we need a few more Logos because after, we want to organize a survey to let our players choose our Logo ! :D

![Logo3](https://raw.githubusercontent.com/Ombridride/minetest-minetestforfun-server/master/other_things/logos/logo3.png)

So, we're waiting your last logos Obani, keep up the good work !

![Logo2](http://i.imgur.com/GhhdQIm.png)
![Logo](http://i.imgur.com/4O7ZcoJ.png)
![Logo5](http://i.imgur.com/dXWg4fU.png)

**Comment by ObaniGemini** [comment]
Ooooops... Forgot it :p . I try to work on it again :)

**Comment by Ataron** [comment]
J'aime bien les formes de tes logos mais tu devrais essayé d'en faire un avec des couleurs moins foncées juste pour voir ce que ca donne :p

**Comment by Ombridride** [comment]
Yes @Ataron, more lighter colors can be a good idea ! :)

**Comment by ObaniGemini** [comment]
I made a new concept for the logo... What do you think of it?

![mffconceptnew](https://cloud.githubusercontent.com/assets/11649956/8023357/b118bf9c-0d09-11e5-838a-4c93b32b2528.png)

**Comment by ObaniGemini** [comment]
The problem is I'm really fond of black and white mix :p

**Comment by paly2** [comment]
My choice is the second logo (red) !

**Comment by Ombridride** [comment]
@ObaniGemini 
The new concept is interrresting and beautiful, but we really need colors (website color chart for exemple)

@paly2 
Thank you for your answer, but the survey isn't on this topic, we will create a big/good survey on the website (section event/événements) when we have more choice for logos !
(so, the players decided, not only the devs ;))

**Comment by ObaniGemini** [comment]
Even more concepts !!!! And with colors !!!
![mffconceptnew2](https://cloud.githubusercontent.com/assets/11649956/8037115/36ae1ea2-0dfc-11e5-8c6b-34364d7415a6.png)

**Comment by paly2** [comment]
Yeah, very good Obani !

**Comment by Ataron** [comment]
Right This one is beautiful.

**Comment by Ombridride** [comment]
@ObaniGemini 
Can you add the text MinetestForFun to your logos ?
I will create a survey as soon as i have your different logos with our name ! :)

The best is to palce the "MinetestForFun" text to the right of the logo, like this :

https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.minimall.fr%2F4264-thickbox%2Ftatouage-rond-dcer.jpg&f=1 MinetestForFun

**Comment by Cyberpangolin** [comment]
I want a try too. please wait unitl tomorrow.

**Comment by Ombridride** [comment]
Ok @Cyberpangolin, I will wait your logo(s ?) :)

**Comment by Cyberpangolin** [comment]
Here is a try:
![banniere](https://cloud.githubusercontent.com/assets/12512762/8753611/72a64d82-2cbd-11e5-902f-367f47bdacc7.png)
WTFPL

**Comment by Ombridride** [comment]
Interresting concepts, my favorite is the second you show us @Cyberpangolin, the bucket of the third try disturbs me, the first has just too many details compacted for be pleasant to read.

But i think i need say you 2 or 3 things :
- The logo needs to respect the chart design of the site (colors), 
- your logo is very interresting but i have trouble to read correctly the "MINETESTFORFUN" text,

Your logo is interresting because it looks really attractive and we immediately understand that is a game logo, it's a good point !

**Comment by Cyberpangolin** [comment]
![mfflogov4](https://cloud.githubusercontent.com/assets/12512762/8757570/a69d4b72-2cdb-11e5-979b-951d85e99dd0.png)

I hope you like them more.
The dark background is the color already used on the site. 
I assume that the lightened background is slightly on yellow-green, because full white kills my eyes. It can be changed anyway, and I will when I am back home with my true color screen.
Maybe you can see a difference between the reds, the goal is to have a good contrast without pain in the eyes. It stays in the colors we use.

Uh. maybe we should keep a dark banner for the website and a lightened for the ingame menus (like in the news).

**Comment by Ombridride** [comment]
Please get a try on use the red color of the website for the text and, the green "title article color" for the background of the banner, this for respect the chart design of the website

For the moment, we prefer (ayame and me) the third and the fourth you made i think it's because of the writing design of the text.

But i don't see any other players leave their comments about your logo... :(

Oh and a last thing, maybe it's too much to ask but, the vine you place around the background, it's a good idea, but it's maybe too much repetitive, maybe add some trees ? or flowers ? or aynthing other that is different :D

**Comment by Cyberpangolin** [comment]
Okay, here is a new try.
You already know 3 and 4
5 is with the website's background green
6 is 5 with the website's text color.

![3456](https://cloud.githubusercontent.com/assets/12512762/8761383/a4635256-2d4f-11e5-834e-a1a1457dca61.png)


I had already tried with these red and green, I didn't think they are that good and did not present them. To be - really - honest, I think 5 is ugly and 6 awful.

About the red: the only place you see it is on the logo that will replace it. --> Not that important I think.

About the wines: I may change, but with the green you can almost not see them... And removing is not a solution, it looks empty.

**Comment by Cyberpangolin** [comment]
After discussion on IRC with Ombriride;

- Added a floating island around the logo.
- slightly moved the axe on the shield
- changed the wines with saplings, flowers, etc.
![imageforfun](https://cloud.githubusercontent.com/assets/12512762/8761738/19e6779a-2d61-11e5-9117-77761a83ed80.png)

**Comment by Ombridride** [comment]
My point of view : the island isn't very beautiful
Maybe it can help you ? 
![island](http://i.imgur.com/qOnG1vd.png)

**Comment by Cyberpangolin** [comment]
![logomffdefinitif](https://cloud.githubusercontent.com/assets/12512762/8767598/d2baa1be-2e61-11e5-951e-7567a1344306.png)

And I hope this can please you :)

**Comment by Ombridride** [comment]
Great ! On the website right now :)

But i think the mini-lgoo needs to be more bigger (try 300*60 px)
![website_right_now](http://i.imgur.com/MxbXF0d.png)

**Comment by Cyberpangolin** [comment]
300x60 is not possible. I've done a 300x50.

**Comment by Ombridride** [comment]
Ok, i think it's fine

**Comment by Ombridride** [comment]
The logos are integrated to the wesbite/forum.
I think i can closed the issue, thank you for your time & work, you can re-opened the issue if you need it.

**Comment by ObaniGemini** [comment]
What the hell happends when I'm noy here? O.o

**Comment by Ombridride** [comment]
Just read the entire issue and you will understand :D (also visit www.minetestforfun.com)

**Comment by ObaniGemini** [comment]
Question réthorique

**Comment by Ombridride** [comment]
Obani, comme je te le disais, si tu souhaites l'améliorer ou tester des choses et nous les montrer, tu as à ta disposition le .svp, libre a toi de nous monrter ton travail :)

**Comment by ObaniGemini** [comment]
Je ne pourrais pas avant plusieurs jours

**Comment by Ombridride** [comment]
Obani, qu'est il advenu de ton idée d'améliorer le logo actuel ?

**Comment by ObaniGemini** [comment]
On ne peut pas faire une belle image à partir d'une image ratée. On ne peut qu'affiner une image belle à l'origine.

**Comment by Ombridride** [comment]
@ObaniGemini Il te faut donc repartir de zéro si l'on en suit ta loguique, tu te plaint beaucoup de nombreuses textures, mais je ne te vois pas en proposer... :)

**Comment by LeMagnesium** [comment]
@Ombridride : Juste pour te rappeler, @ObaniGemini a proposé pas mal de textures dans ce ticket, et je ne suis pas sûr qu'il ait accès en ce moment ou dans un futur très proche à tout ses outils graphiques.
Sois just patient.

**Comment by ObaniGemini** [comment]
À vrai dire j'ai ouvert mon ordi pour la première fois depuis 2 semaines pour des raisons que vous ignorez surement pour cause d'oubli de vous en avertir. La première et dernière chose que j'y ait faite fut de lire les notifications sur Github et de poster des commentaires.
Donc non, je n'ai pas eu accès à mes outils.
De plus, je suis en train de tenter une approche du monde extérieur plus approfondie et d'ainsi m'éloigner du monde vidéo-ludique (cela me permettrait par exemple de ne pas briller au soleil).

De ce fait, je continuerais à travailler sur de la musique et de l'image, mais en étant beaucoup moins présent qu'à l'usuelle, quitte à m'ennuyer. Cela me permettra aussi de reprendre réellement la musique et d'avoir des rapports sociaux avec des gens dont je peux voir le facies en Retina. Si j'échoue dans ma tache, je serais alors surement plus présent et apte à me connecter durablement sur IRC et in-game ^^.
Mais je pense tout de même qu'un retour au vrai monde réel de la réalité véritablement véridique me permettrait de m'améliorer dans les matières sociales et artistiques, étant donné que la programmation a du mal à m'attirer et que à part améliorer mes squillzes sur des jeux vidéos ou parler avec d'éventuels kikoos, je ne fais pas grand chose sur mon petit pécé.

Voila voila, sur ce, bisous virtuels virtuoses !

**Comment by Ombridride** [comment]
Up, i will closed this issue in one week, if you don't send us a logo soon :)

**Comment by ObaniGemini** [comment]
Actually the first one of this page was great. The rest was just to have fun.

**Comment by Ombridride** [comment]
We need to see "MinetestForFun" on the logo, with a pixel policy if it's possible, that's a must have.

Second, we need two banners, one small (left top of the website, news/irc/... ingame background) and a big one (first banner of the website and forum presentation) the size need to be rectangular, but easy to tweak if you add "MinetestForFun" i thing...

**Comment by ObaniGemini** [comment]
The one I made was in circle, so easy to put in a square or circle form like in the website experiment of davedevils. For the MInetestForFun font, I remember you that I'm not on my usual computer and that I will have more difficulties to do things I would do on my normal computer. Also, I don't understand why we should take a font and why it should be pixelized. Most part of the fonts are boring or bad for logos.

**Comment by Ombridride** [comment]
Closed this issue.
No answer since 1 month.
