### ISSUE TITLE
Improved [death_message] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#58]
With the lastest added feature of "minetest_game" we can now collect the punch damage on a player so we can now improves the "death_message" mod with :
 -  [x]  _player_ death message against players (with the player killer name if it's possible) => https://github.com/MinetestForFun/server-minetestforfun/commit/592ac4fa1218dc1a460366fb5b9f7983c16eadf3
 -  [x]  _player_ death message against monsters (with the monster name if it's possible) => https://github.com/MinetestForFun/server-minetestforfun/commit/d347ba484ab365ecb071bd5443e67dfd6520e123
 -  [x]  Write all death messages entries in a *.txt file on the ~/world/ folder => https://github.com/MinetestForFun/server-minetestforfun/commit/8990897e53368ff0ed6cca5059e7e30c58eda59e

EDIT : Need to wait the "0.4.13-Release" Minetest version, add a tag for 0.4.13 features

**Comment by LeMagnesium** [comment]
> With the lastest added feature of "minetest_game"

This is an engine feature, and the server can't use it at the moment. I will do it when the server will be at 0.4.13 .

**Comment by Ombridride** [comment]
Indeed it's a new engine feature, we fight for its integration in the core game mounths ago and they did it ! https://forum.minetest.net/viewtopic.php?f=47&t=11278&hilit=punch+event

Now we need to wait the  Minetest 0.4.13 Stable next Release

**Comment by ObaniGemini** [comment]
I think we shall find other jokes that would be more internationnal now it's gonna be traduced :p

**Comment by LeMagnesium** [comment]
I've done the first one of those three. I'll be doing the other ones soon.

**Comment by ObaniGemini** [comment]
=> https://github.com/MinetestForFun/server-minetestforfun/issues/265

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/592ac4fa1218dc1a460366fb5b9f7983c16eadf3 https://github.com/MinetestForFun/server-minetestforfun/commit/d347ba484ab365ecb071bd5443e67dfd6520e123 https://github.com/MinetestForFun/server-minetestforfun/commit/8990897e53368ff0ed6cca5059e7e30c58eda59e
We should be okay with this now.
