### ISSUE TITLE
Updated and improved MinetestMapper

### ISSUE THREAD

**Issue by Darcidride** [MinetestForFun/server-minetestforfun#71]
Our Worldmap works with the "MinetestMapper" project. 
This project was updated since 2 mounths and include new features very interresting :
- [x] Update the Mapper
- [x] Players real time position https://github.com/Ombridride/minetest-minetestforfun-server/commit/cc06c4c783eb818a785f68bff49245aa350ee474 https://github.com/Ombridride/minetest-minetestforfun-server/commit/930e3ad666d31f24ea2bd1028edccd229e0c2f5e
- [x] Players layer checked by default
- [ ] Use reverseproxy special configuration for websocket => **Need latest apache 2.4 version from Debian Jessie to do this**

Refer to this post : https://forum.minetest.net/viewtopic.php?f=14&t=10278&view=unread#p180266

**Comment by ObaniGemini** [comment]
The players RT pos is a very interesting feature ! I hope this will be added to the website :)
(Maybe you should add an option to show players or not)

**Comment by Ombridride** [comment]
The Players real time position is added, i can see and read the file **mt_players_fifo** in the world directory, all data into it seems to be good :

```
I will add lines from the "mt_players_fifo" here
```

Like the modder says, i launch the mtwebmapper before the server, but I can't see the Players real time positions on the mapper... Maybe i mistake something ?

**Comment by s-l-teichmann** [comment]
Hi! Does the problem still exist? When I look at
http://qbuissondebon.info:8808/#7/686.000/-295.000
I see players.

**Comment by Ombridride** [comment]
You're right, and i can easily explain you where my mistake was :

I've made abad merge job with the old _web_ folder with the new _web_ folder ! Since this afternoon, i've re-merged properly this folders and it's work...

Sorry for the disturbance :)

**Comment by Ombridride** [comment]
#### Tweaks wich need to be done
- [ ] POI (Point Of Interest) => merker OK, group OK, but problems with the icons/shadows
- [ ] install and activated the websocket support
- [ ] check by default the "players" field
 
@s-l-teichmann, i have many difficulties to do this tweaks, can you help me ? (maybe a irc discussion can help ?)

**Comment by crabman77** [comment]
"but problems with the icons/shadows"
I think found 

var spawn = L.marker([1, -10],{
             icon: L.AwesomeMarkers.icon({
                 icon: 'male',
                 iconColor: 'black',
                 prefix: 'fa',
                 markerColor: 'green'
             }),
}).bindPopup('Tour du Spawn')


var island_b91b = L.marker([1, -20],{
             icon: L.AwesomeMarkers.icon({
                 icon: 'male',
                 iconColor: 'black',
                 prefix: 'fa',
                 markerColor: 'green'
             }),
}).bindPopup('Ile de b91b')


var house_ataron = L.marker([1, -30],{
             icon: L.AwesomeMarkers.icon({
                 icon: 'male',
                 iconColor: 'black',
                 prefix: 'fa',
                 markerColor: 'green'
             }),
}).bindPopup('Maison de Ataron')


var house_cyberpangolin = L.marker([1, -40],{
             icon: L.AwesomeMarkers.icon({
                 icon: 'male',
                 iconColor: 'black',
                 prefix: 'fa',
                 markerColor: 'green'
             }),
}).bindPopup('Maison de Cyberpangolin')

var group_poi = L.layerGroup([spawn, island_b91b, house_ataron, house_cyberpangolin]);
![capture-16](https://cloud.githubusercontent.com/assets/7189389/8737464/aa6be8b2-2c22-11e5-8f44-e7e325565d7e.png)

**Comment by Ombridride** [comment]
Your code seems to be correct, i try it right now

**Comment by Ombridride** [comment]
#### Tweaks wich need to be done

- [ ] install and activated the websocket support => installed with npm, launched with the mtwebmapper with this command :

index.html
```
var useWebsocket = true;
```


crontab
```
# MINETEST MAPPER + MINETEST SERVER
#
# On kill tous les screens minetestmapper - le lundi à 3h31 du matin
31 3 * * 1 screen -S mtredisalize -X quit
31 3 * * 1 screen -S mtseeder -X quit
31 3 * * 1 screen -S mtwebmapper -X quit
# Kill du screen contenant le minetest serveur le lundi, jeudi et samedi à 3h31
31 3 * * 1,4,6 screen -S minetest -X quit
# Redisalize - le lundi à 3h33 du matin
33 3 * * 1 screen -dmS mtredisalize /home/quentinbd/gopath/bin/mtredisalize -host=localhost -interleaved=true -change-url=http://localhost:8808/update -change-duration=15s /home/quentinbd/minetest/worlds/minetestforfun/map.db
# Seeder - le lundi à 3h34 - dure 10min
35 3 * * 1 screen -dmS mtseeder /home/quentinbd/gopath/bin/mtseeder -colors=/home/quentinbd/minetest/worlds/minetestforfun/colors.txt -output-dir=/home/quentinbd/minetest/worlds/minetestforfun/map.db -workers=3 -transparent=true
# Webmapper - le lundi à 3h45
50 3 * * 1 screen -dmS mtwebmapper /home/quentinbd/gopath/bin/mtwebmapper -colors=/home/quentinbd/minetest/worlds/minetestforfun/colors.txt -web-host="" -map=/home/quentinbd/minetest/worlds/minetestforfun/map.db -web=/var/www/mtsatellite -redis-host=localhost -workers=2 -transparent=true -websockets=true -players=/home/quentinbd/minetest/worlds/minetestforfun/mt_players_fifo
# Lancement du minetest serveur le lundi, jeudi et samedi à 3h36
52 3 * * 1,4,6 screen -dmS minetest /home/quentinbd/script/start02.sh
```

- [ ] check by default the "players" field
 
@s-l-teichmann, i have many difficulties to do this tweaks, can you help me ? (maybe a irc discussion can help ?)

**Comment by s-l-teichmann** [comment]
The configuration looks correct. I'll try to hang out in the minetest irc channel tomorrow (sunday).

**Comment by Ombridride** [comment]
Come on our minetest IRC channel when you want (not now i go to my bed) => irc.inchra.net #minetestforfun-dev

**Comment by Ombridride** [comment]
For the websocket, indeed i need a Squid/HAproxy, i will install and parameter it when i've more time...

**Comment by Ombridride** [comment]
Apparently i don't need a squid/haproxy for the reverseproxy of the websocket :)

Indeed, the websocket support works it i visit the URL with the :8808 port, so the reverse proxy doestn't work BUT the websocket move from the external through the firewall to the right computer !

So i've maybe find a solution, i need to try it http://stackoverflow.com/questions/30079471/apache-websockets-reverse-proxy and http://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel

The Apache2 reverse proxy needs a special configuration to be activated :
- [ ] make the Apache2 reverse proxy for websocket support working

**Comment by s-l-teichmann** [comment]
@Ombridride  I've looked at your map and I've seen that you have already managed to have the players layer activated by default. Is there something else I can do?

**Comment by Ombridride** [comment]
For the moment you can't d noting more, your presence was helpful !

For the websocket, i need to try the apache "special" reverseproxy configuration.

For the transparency deep tweakable for the sea, i didn't check your tweak in your repository for the moment, i need to work a little on the mapper soon :)

Anyway, thank you for your help

**Comment by Ombridride** [comment]
Until i test a solution / find a solution, the worldmap link will be http://qbuissondebon.info:8808 (I changed it right now on the website)

**Comment by Ombridride** [comment]
The reverse proxy will be added to the webmappers links when we will upgrade the Debian 7 to Debian 8 and update Apache2 to the latest version. 
In fact, the actual Apache2 version we have can't works with websocket.

**Comment by Ombridride** [comment]
Upgrade the main web server server to Apache 2.4, need some improvments, but the reverseproxy for websocket seesm to work great 

=> http://158.69.114.146:8808/#7/398.000/-460.000

**Comment by Darcidride** [comment]
Everything is OK, i closed this issue.
