### ISSUE TITLE
[Fishing] in Rivers?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#98]
With the arrival of the new fishing mod by @crabman77 and the arrival of the river water in the mapgen, I think it would be a good idea to have some kinds of fishes/objects in water_sources and some other kinds of fishes/objects in river_water_wources.

What would you think of it?

**Comment by crabman77** [comment]
there are only 5 fish, it'll be a bit complicated
little fish: fish, clownfish, bluefish
big fish: shark, pike
But if you found other fish so why not

**Comment by Ombridride** [comment]
@crabman77 
Ok, you have 5 fishs.

How do you think about : 
- 3 fish generated in both water oceans and water rivers (salt water + pure water)
- 1 fish generated only in oceans (salt water) => shark
- 1 fish generated only in water rivers (pure water) => bluefish

if you think my idea is good, feel free to integrate it :D

**Comment by crabman77** [comment]
feature added https://github.com/MinetestForFun/fishing/commit/14bdc521f2d5d5a7dadb8ffda01e961a2aa51f0b
